@ Thumb->ARM interworking veneer for the ARM sound routine SoundMixAll.
@ In the original build this was generated by the linker (.glue_7t).
	.include "asm/macros.inc"
	.syntax unified
	.text

	thumb_func_start __sub_0807EAD0_from_thumb
__sub_0807EAD0_from_thumb: @ 0x08080A18
	bx pc
	nop
	.arm
	b SoundMixAll
	.size __sub_0807EAD0_from_thumb, .-__sub_0807EAD0_from_thumb
