@ Thumb->ARM interworking veneer for the ARM sound routine sub_0807EAD0.
@ In the original build this was generated by the linker (.glue_7t).
	.include "asm/macros.inc"
	.syntax unified
	.text

	thumb_func_start __sub_0807EAD0_from_thumb
__sub_0807EAD0_from_thumb: @ 0x08080A18
	bx pc
	nop
	.arm
	b sub_0807EAD0
	.size __sub_0807EAD0_from_thumb, .-__sub_0807EAD0_from_thumb
