@ Generated by tools/assets.py gen-data from config/assets.tsv. Do not edit.
@ Each asset is built from assets/ into build/assets/ (see tools/assets.py).

	.section .rodata

@ sound/se_table (bin)
	.global gUnk_08087FD0
gUnk_08087FD0: @ 0x08087FD0
	.incbin "build/assets/sound__se_table.bin", 0x0, 0x540
@ sound/se_tracks (bin)
	.incbin "build/assets/sound__se_tracks.bin", 0x0, 0x510
@ sound/pcm_bank1_table (bin)
	.global gUnk_08088A20
gUnk_08088A20: @ 0x08088A20
	.incbin "build/assets/sound__pcm_bank1_table.bin", 0x0, 0x70
@ sound/pcm_bank1_samples (bin)
	.incbin "build/assets/sound__pcm_bank1_samples.bin", 0x0, 0x57F40
@ sound/song_table (bin)
	.global gUnk_080E09D0
gUnk_080E09D0: @ 0x080E09D0
	.incbin "build/assets/sound__song_table.bin", 0x0, 0x570
@ sound/song_tracks (bin)
	.incbin "build/assets/sound__song_tracks.bin", 0x0, 0x3A4E0
@ sound/pcm_bank0_table (bin)
	.global gUnk_0811B420
gUnk_0811B420: @ 0x0811B420
	.incbin "build/assets/sound__pcm_bank0_table.bin", 0x0, 0x90
@ sound/pcm_bank0_samples (bin)
	.incbin "build/assets/sound__pcm_bank0_samples.bin", 0x0, 0x1E0A0
@ sound/wave_ram_patterns (bin)
	.global gUnk_08139550
gUnk_08139550: @ 0x08139550
	.incbin "build/assets/sound__wave_ram_patterns.bin", 0x0, 0xA00
@ sound/unk_08139F50 (bin)
	.global gUnk_08139F50
gUnk_08139F50: @ 0x08139F50
	.incbin "build/assets/sound__unk_08139F50.bin", 0x0, 0xC
@ tables/dialogue_box_pointers (bin)
	.global gUnk_08139F5C
gUnk_08139F5C: @ 0x08139F5C
	.incbin "build/assets/tables__dialogue_box_pointers.bin", 0x0, 0x8
@ text/duelists.json (duelists)
	.global gUnk_08139F64
gUnk_08139F64: @ 0x08139F64
	.incbin "build/assets/text__duelists.json.bin", 0x0, 0x4
	.global gUnk_08139F68
gUnk_08139F68: @ 0x08139F68
	.incbin "build/assets/text__duelists.json.bin", 0x4, 0xE6C
@ tables/dialogue_box_steps (bin)
	.global gUnk_0813ADD4
gUnk_0813ADD4: @ 0x0813ADD4
	.incbin "build/assets/tables__dialogue_box_steps.bin", 0x0, 0x20
@ text/dialogue.json (dialogue)
	.global gUnk_0813ADF4
gUnk_0813ADF4: @ 0x0813ADF4
	.incbin "build/assets/text__dialogue.json.bin", 0x0, 0x4
	.global gUnk_0813ADF8
gUnk_0813ADF8: @ 0x0813ADF8
	.incbin "build/assets/text__dialogue.json.bin", 0x4, 0x5C5A4
@ text/dialogue_end (bin)
	.incbin "build/assets/text__dialogue_end.bin", 0x0, 0x304
@ gfx/scene_sets (bin)
	.global gUnk_081976A0
gUnk_081976A0: @ 0x081976A0
	.incbin "build/assets/gfx__scene_sets.bin", 0x0, 0x14
	.global gUnk_081976B4
gUnk_081976B4: @ 0x081976B4
	.incbin "build/assets/gfx__scene_sets.bin", 0x14, 0x14
	.global gUnk_081976C8
gUnk_081976C8: @ 0x081976C8
	.incbin "build/assets/gfx__scene_sets.bin", 0x28, 0x14
	.global gUnk_081976DC
gUnk_081976DC: @ 0x081976DC
	.incbin "build/assets/gfx__scene_sets.bin", 0x3C, 0x14
	.global gUnk_081976F0
gUnk_081976F0: @ 0x081976F0
	.incbin "build/assets/gfx__scene_sets.bin", 0x50, 0x14
	.global gUnk_08197704
gUnk_08197704: @ 0x08197704
	.incbin "build/assets/gfx__scene_sets.bin", 0x64, 0x14
	.global gUnk_08197718
gUnk_08197718: @ 0x08197718
	.incbin "build/assets/gfx__scene_sets.bin", 0x78, 0x14
	.global gUnk_0819772C
gUnk_0819772C: @ 0x0819772C
	.incbin "build/assets/gfx__scene_sets.bin", 0x8C, 0x14
	.global gUnk_08197740
gUnk_08197740: @ 0x08197740
	.incbin "build/assets/gfx__scene_sets.bin", 0xA0, 0x14
	.global gUnk_08197754
gUnk_08197754: @ 0x08197754
	.incbin "build/assets/gfx__scene_sets.bin", 0xB4, 0x14
	.global gUnk_08197768
gUnk_08197768: @ 0x08197768
	.incbin "build/assets/gfx__scene_sets.bin", 0xC8, 0x14
	.global gUnk_0819777C
gUnk_0819777C: @ 0x0819777C
	.incbin "build/assets/gfx__scene_sets.bin", 0xDC, 0x14
	.global gUnk_08197790
gUnk_08197790: @ 0x08197790
	.incbin "build/assets/gfx__scene_sets.bin", 0xF0, 0x14
	.global gUnk_081977A4
gUnk_081977A4: @ 0x081977A4
	.incbin "build/assets/gfx__scene_sets.bin", 0x104, 0x14
	.global gUnk_081977B8
gUnk_081977B8: @ 0x081977B8
	.incbin "build/assets/gfx__scene_sets.bin", 0x118, 0x14
	.global gUnk_081977CC
gUnk_081977CC: @ 0x081977CC
	.incbin "build/assets/gfx__scene_sets.bin", 0x12C, 0x14
	.global gUnk_081977E0
gUnk_081977E0: @ 0x081977E0
	.incbin "build/assets/gfx__scene_sets.bin", 0x140, 0x14
	.global gUnk_081977F4
gUnk_081977F4: @ 0x081977F4
	.incbin "build/assets/gfx__scene_sets.bin", 0x154, 0x14
	.global gUnk_08197808
gUnk_08197808: @ 0x08197808
	.incbin "build/assets/gfx__scene_sets.bin", 0x168, 0x14
	.global gUnk_0819781C
gUnk_0819781C: @ 0x0819781C
	.incbin "build/assets/gfx__scene_sets.bin", 0x17C, 0x14
	.global gUnk_08197830
gUnk_08197830: @ 0x08197830
	.incbin "build/assets/gfx__scene_sets.bin", 0x190, 0x14
	.global gUnk_08197844
gUnk_08197844: @ 0x08197844
	.incbin "build/assets/gfx__scene_sets.bin", 0x1A4, 0x14
	.global gUnk_08197858
gUnk_08197858: @ 0x08197858
	.incbin "build/assets/gfx__scene_sets.bin", 0x1B8, 0x14
	.global gUnk_0819786C
gUnk_0819786C: @ 0x0819786C
	.incbin "build/assets/gfx__scene_sets.bin", 0x1CC, 0x14
	.global gUnk_08197880
gUnk_08197880: @ 0x08197880
	.incbin "build/assets/gfx__scene_sets.bin", 0x1E0, 0x14
	.global gUnk_08197894
gUnk_08197894: @ 0x08197894
	.incbin "build/assets/gfx__scene_sets.bin", 0x1F4, 0x14
	.global gUnk_081978A8
gUnk_081978A8: @ 0x081978A8
	.incbin "build/assets/gfx__scene_sets.bin", 0x208, 0x14
	.global gUnk_081978BC
gUnk_081978BC: @ 0x081978BC
	.incbin "build/assets/gfx__scene_sets.bin", 0x21C, 0x14
	.global gUnk_081978D0
gUnk_081978D0: @ 0x081978D0
	.incbin "build/assets/gfx__scene_sets.bin", 0x230, 0x14
	.global gUnk_081978E4
gUnk_081978E4: @ 0x081978E4
	.incbin "build/assets/gfx__scene_sets.bin", 0x244, 0x14
	.global gUnk_081978F8
gUnk_081978F8: @ 0x081978F8
	.incbin "build/assets/gfx__scene_sets.bin", 0x258, 0x14
@ tables/scene_scripts_and_lists (bin)
	.incbin "build/assets/tables__scene_scripts_and_lists.bin", 0x0, 0x7C8
	.global gUnk_081980D4
gUnk_081980D4: @ 0x081980D4
	.incbin "build/assets/tables__scene_scripts_and_lists.bin", 0x7C8, 0x264
	.global gUnk_08198338
gUnk_08198338: @ 0x08198338
	.incbin "build/assets/tables__scene_scripts_and_lists.bin", 0xA2C, 0x14
	.global gUnk_0819834C
gUnk_0819834C: @ 0x0819834C
	.incbin "build/assets/tables__scene_scripts_and_lists.bin", 0xA40, 0x34
	.global gUnk_08198380
gUnk_08198380: @ 0x08198380
	.incbin "build/assets/tables__scene_scripts_and_lists.bin", 0xA74, 0x2C
	.global gUnk_081983AC
gUnk_081983AC: @ 0x081983AC
	.incbin "build/assets/tables__scene_scripts_and_lists.bin", 0xAA0, 0x14
	.global gUnk_081983C0
gUnk_081983C0: @ 0x081983C0
	.incbin "build/assets/tables__scene_scripts_and_lists.bin", 0xAB4, 0x80
	.global gUnk_08198440
gUnk_08198440: @ 0x08198440
	.incbin "build/assets/tables__scene_scripts_and_lists.bin", 0xB34, 0x28
	.global gUnk_08198468
gUnk_08198468: @ 0x08198468
	.incbin "build/assets/tables__scene_scripts_and_lists.bin", 0xB5C, 0x64
	.global gUnk_081984CC
gUnk_081984CC: @ 0x081984CC
	.incbin "build/assets/tables__scene_scripts_and_lists.bin", 0xBC0, 0xC
	.global gUnk_081984D8
gUnk_081984D8: @ 0x081984D8
	.incbin "build/assets/tables__scene_scripts_and_lists.bin", 0xBCC, 0x1C
	.global gUnk_081984F4
gUnk_081984F4: @ 0x081984F4
	.incbin "build/assets/tables__scene_scripts_and_lists.bin", 0xBE8, 0x14
	.global gUnk_08198508
gUnk_08198508: @ 0x08198508
	.incbin "build/assets/tables__scene_scripts_and_lists.bin", 0xBFC, 0x80
	.global gUnk_08198588
gUnk_08198588: @ 0x08198588
	.incbin "build/assets/tables__scene_scripts_and_lists.bin", 0xC7C, 0x18
	.global gUnk_081985A0
gUnk_081985A0: @ 0x081985A0
	.incbin "build/assets/tables__scene_scripts_and_lists.bin", 0xC94, 0x64
	.global gUnk_08198604
gUnk_08198604: @ 0x08198604
	.incbin "build/assets/tables__scene_scripts_and_lists.bin", 0xCF8, 0x14
	.global gUnk_08198618
gUnk_08198618: @ 0x08198618
	.incbin "build/assets/tables__scene_scripts_and_lists.bin", 0xD0C, 0x10
	.global gUnk_08198628
gUnk_08198628: @ 0x08198628
	.incbin "build/assets/tables__scene_scripts_and_lists.bin", 0xD1C, 0x11C
	.global gUnk_08198744
gUnk_08198744: @ 0x08198744
	.incbin "build/assets/tables__scene_scripts_and_lists.bin", 0xE38, 0x58
	.global gUnk_0819879C
gUnk_0819879C: @ 0x0819879C
	.incbin "build/assets/tables__scene_scripts_and_lists.bin", 0xE90, 0x94
	.global gUnk_08198830
gUnk_08198830: @ 0x08198830
	.incbin "build/assets/tables__scene_scripts_and_lists.bin", 0xF24, 0x80
	.global gUnk_081988B0
gUnk_081988B0: @ 0x081988B0
	.incbin "build/assets/tables__scene_scripts_and_lists.bin", 0xFA4, 0x20
	.global gUnk_081988D0
gUnk_081988D0: @ 0x081988D0
	.incbin "build/assets/tables__scene_scripts_and_lists.bin", 0xFC4, 0x64
	.global gUnk_08198934
gUnk_08198934: @ 0x08198934
	.incbin "build/assets/tables__scene_scripts_and_lists.bin", 0x1028, 0x1C
	.global gUnk_08198950
gUnk_08198950: @ 0x08198950
	.incbin "build/assets/tables__scene_scripts_and_lists.bin", 0x1044, 0x2C
	.global gUnk_0819897C
gUnk_0819897C: @ 0x0819897C
	.incbin "build/assets/tables__scene_scripts_and_lists.bin", 0x1070, 0x2C
	.global gUnk_081989A8
gUnk_081989A8: @ 0x081989A8
	.incbin "build/assets/tables__scene_scripts_and_lists.bin", 0x109C, 0x28
	.global gUnk_081989D0
gUnk_081989D0: @ 0x081989D0
	.incbin "build/assets/tables__scene_scripts_and_lists.bin", 0x10C4, 0x1C
	.global gUnk_081989EC
gUnk_081989EC: @ 0x081989EC
	.incbin "build/assets/tables__scene_scripts_and_lists.bin", 0x10E0, 0x64
	.global gUnk_08198A50
gUnk_08198A50: @ 0x08198A50
	.incbin "build/assets/tables__scene_scripts_and_lists.bin", 0x1144, 0x300
	.global gUnk_08198D50
gUnk_08198D50: @ 0x08198D50
	.incbin "build/assets/tables__scene_scripts_and_lists.bin", 0x1444, 0xC
	.global gUnk_08198D5C
gUnk_08198D5C: @ 0x08198D5C
	.incbin "build/assets/tables__scene_scripts_and_lists.bin", 0x1450, 0xC
	.global gUnk_08198D68
gUnk_08198D68: @ 0x08198D68
	.incbin "build/assets/tables__scene_scripts_and_lists.bin", 0x145C, 0x24
	.global gUnk_08198D8C
gUnk_08198D8C: @ 0x08198D8C
	.incbin "build/assets/tables__scene_scripts_and_lists.bin", 0x1480, 0x40
	.global gUnk_08198DCC
gUnk_08198DCC: @ 0x08198DCC
	.incbin "build/assets/tables__scene_scripts_and_lists.bin", 0x14C0, 0x18
	.global gUnk_08198DE4
gUnk_08198DE4: @ 0x08198DE4
	.incbin "build/assets/tables__scene_scripts_and_lists.bin", 0x14D8, 0x98
	.global gUnk_08198E7C
gUnk_08198E7C: @ 0x08198E7C
	.incbin "build/assets/tables__scene_scripts_and_lists.bin", 0x1570, 0x30
	.global gUnk_08198EAC
gUnk_08198EAC: @ 0x08198EAC
	.incbin "build/assets/tables__scene_scripts_and_lists.bin", 0x15A0, 0x30
	.global gUnk_08198EDC
gUnk_08198EDC: @ 0x08198EDC
	.incbin "build/assets/tables__scene_scripts_and_lists.bin", 0x15D0, 0x1C
	.global gUnk_08198EF8
gUnk_08198EF8: @ 0x08198EF8
	.incbin "build/assets/tables__scene_scripts_and_lists.bin", 0x15EC, 0x1C
	.global gUnk_08198F14
gUnk_08198F14: @ 0x08198F14
	.incbin "build/assets/tables__scene_scripts_and_lists.bin", 0x1608, 0xC
	.global gUnk_08198F20
gUnk_08198F20: @ 0x08198F20
	.incbin "build/assets/tables__scene_scripts_and_lists.bin", 0x1614, 0x60
	.global gUnk_08198F80
gUnk_08198F80: @ 0x08198F80
	.incbin "build/assets/tables__scene_scripts_and_lists.bin", 0x1674, 0x2C
	.global gUnk_08198FAC
gUnk_08198FAC: @ 0x08198FAC
	.incbin "build/assets/tables__scene_scripts_and_lists.bin", 0x16A0, 0xA40
	.global gUnk_081999EC
gUnk_081999EC: @ 0x081999EC
	.incbin "build/assets/tables__scene_scripts_and_lists.bin", 0x20E0, 0xC
	.global gUnk_081999F8
gUnk_081999F8: @ 0x081999F8
	.incbin "build/assets/tables__scene_scripts_and_lists.bin", 0x20EC, 0xC
	.global gUnk_08199A04
gUnk_08199A04: @ 0x08199A04
	.incbin "build/assets/tables__scene_scripts_and_lists.bin", 0x20F8, 0xC
	.global gUnk_08199A10
gUnk_08199A10: @ 0x08199A10
	.incbin "build/assets/tables__scene_scripts_and_lists.bin", 0x2104, 0x18
	.global gUnk_08199A28
gUnk_08199A28: @ 0x08199A28
	.incbin "build/assets/tables__scene_scripts_and_lists.bin", 0x211C, 0x18
	.global gUnk_08199A40
gUnk_08199A40: @ 0x08199A40
	.incbin "build/assets/tables__scene_scripts_and_lists.bin", 0x2134, 0x18
	.global gUnk_08199A58
gUnk_08199A58: @ 0x08199A58
	.incbin "build/assets/tables__scene_scripts_and_lists.bin", 0x214C, 0x18
	.global gUnk_08199A70
gUnk_08199A70: @ 0x08199A70
	.incbin "build/assets/tables__scene_scripts_and_lists.bin", 0x2164, 0x258
	.global gUnk_08199CC8
gUnk_08199CC8: @ 0x08199CC8
	.incbin "build/assets/tables__scene_scripts_and_lists.bin", 0x23BC, 0xAC
	.global gUnk_08199D74
gUnk_08199D74: @ 0x08199D74
	.incbin "build/assets/tables__scene_scripts_and_lists.bin", 0x2468, 0x28
	.global gUnk_08199D9C
gUnk_08199D9C: @ 0x08199D9C
	.incbin "build/assets/tables__scene_scripts_and_lists.bin", 0x2490, 0x8
	.global gUnk_08199DA4
gUnk_08199DA4: @ 0x08199DA4
	.incbin "build/assets/tables__scene_scripts_and_lists.bin", 0x2498, 0x28
	.global gUnk_08199DCC
gUnk_08199DCC: @ 0x08199DCC
	.incbin "build/assets/tables__scene_scripts_and_lists.bin", 0x24C0, 0x30
	.global gUnk_08199DFC
gUnk_08199DFC: @ 0x08199DFC
	.incbin "build/assets/tables__scene_scripts_and_lists.bin", 0x24F0, 0x89C
	.global gUnk_0819A698
gUnk_0819A698: @ 0x0819A698
	.incbin "build/assets/tables__scene_scripts_and_lists.bin", 0x2D8C, 0x18
	.global gUnk_0819A6B0
gUnk_0819A6B0: @ 0x0819A6B0
	.incbin "build/assets/tables__scene_scripts_and_lists.bin", 0x2DA4, 0x20
	.global gUnk_0819A6D0
gUnk_0819A6D0: @ 0x0819A6D0
	.incbin "build/assets/tables__scene_scripts_and_lists.bin", 0x2DC4, 0x48
	.global gUnk_0819A718
gUnk_0819A718: @ 0x0819A718
	.incbin "build/assets/tables__scene_scripts_and_lists.bin", 0x2E0C, 0x14
	.global gUnk_0819A72C
gUnk_0819A72C: @ 0x0819A72C
	.incbin "build/assets/tables__scene_scripts_and_lists.bin", 0x2E20, 0x10
	.global gUnk_0819A73C
gUnk_0819A73C: @ 0x0819A73C
	.incbin "build/assets/tables__scene_scripts_and_lists.bin", 0x2E30, 0x44
	.global gUnk_0819A780
gUnk_0819A780: @ 0x0819A780
	.incbin "build/assets/tables__scene_scripts_and_lists.bin", 0x2E74, 0x8
	.global gUnk_0819A788
gUnk_0819A788: @ 0x0819A788
	.incbin "build/assets/tables__scene_scripts_and_lists.bin", 0x2E7C, 0x30
	.global gUnk_0819A7B8
gUnk_0819A7B8: @ 0x0819A7B8
	.incbin "build/assets/tables__scene_scripts_and_lists.bin", 0x2EAC, 0x10
	.global gUnk_0819A7C8
gUnk_0819A7C8: @ 0x0819A7C8
	.incbin "build/assets/tables__scene_scripts_and_lists.bin", 0x2EBC, 0x1A8
	.global gUnk_0819A970
gUnk_0819A970: @ 0x0819A970
	.incbin "build/assets/tables__scene_scripts_and_lists.bin", 0x3064, 0x20
	.global gUnk_0819A990
gUnk_0819A990: @ 0x0819A990
	.incbin "build/assets/tables__scene_scripts_and_lists.bin", 0x3084, 0x44
@ tables/card_effect_handlers (bin)
	.global gUnk_0819A9D4
gUnk_0819A9D4: @ 0x0819A9D4
	.incbin "build/assets/tables__card_effect_handlers.bin", 0x0, 0x27F0
@ tables/pointer_tables (bin)
	.global gUnk_0819D1C4
gUnk_0819D1C4: @ 0x0819D1C4
	.incbin "build/assets/tables__pointer_tables.bin", 0x0, 0x14
	.global gUnk_0819D1D8
gUnk_0819D1D8: @ 0x0819D1D8
	.incbin "build/assets/tables__pointer_tables.bin", 0x14, 0x3C
	.global gUnk_0819D214
gUnk_0819D214: @ 0x0819D214
	.incbin "build/assets/tables__pointer_tables.bin", 0x50, 0x50
	.global gUnk_0819D264
gUnk_0819D264: @ 0x0819D264
	.incbin "build/assets/tables__pointer_tables.bin", 0xA0, 0x18
	.global gUnk_0819D27C
gUnk_0819D27C: @ 0x0819D27C
	.incbin "build/assets/tables__pointer_tables.bin", 0xB8, 0x4
	.global gUnk_0819D280
gUnk_0819D280: @ 0x0819D280
	.incbin "build/assets/tables__pointer_tables.bin", 0xBC, 0x7C
	.global gUnk_0819D2FC
gUnk_0819D2FC: @ 0x0819D2FC
	.incbin "build/assets/tables__pointer_tables.bin", 0x138, 0x1A
	.global gUnk_0819D316
gUnk_0819D316: @ 0x0819D316
	.incbin "build/assets/tables__pointer_tables.bin", 0x152, 0x36
@ tables/deck_lists (bin)
	.incbin "build/assets/tables__deck_lists.bin", 0x0, 0x920
	.global gUnk_0819DC6C
gUnk_0819DC6C: @ 0x0819DC6C
	.incbin "build/assets/tables__deck_lists.bin", 0x920, 0xC8
	.global gUnk_0819DD34
gUnk_0819DD34: @ 0x0819DD34
	.incbin "build/assets/tables__deck_lists.bin", 0x9E8, 0x30
@ tables/rodata2 (bin)
	.global gUnk_0819DD64
gUnk_0819DD64: @ 0x0819DD64
	.incbin "build/assets/tables__rodata2.bin", 0x0, 0x8
	.global gUnk_0819DD6C
gUnk_0819DD6C: @ 0x0819DD6C
	.incbin "build/assets/tables__rodata2.bin", 0x8, 0x28
	.global gUnk_0819DD94
gUnk_0819DD94: @ 0x0819DD94
	.incbin "build/assets/tables__rodata2.bin", 0x30, 0x2800
	.global gUnk_081A0594
gUnk_081A0594: @ 0x081A0594
	.incbin "build/assets/tables__rodata2.bin", 0x2830, 0x2800
	.global gUnk_081A2D94
gUnk_081A2D94: @ 0x081A2D94
	.incbin "build/assets/tables__rodata2.bin", 0x5030, 0x1400
	.global gUnk_081A4194
gUnk_081A4194: @ 0x081A4194
	.incbin "build/assets/tables__rodata2.bin", 0x6430, 0x10
	.global gUnk_081A41A4
gUnk_081A41A4: @ 0x081A41A4
	.incbin "build/assets/tables__rodata2.bin", 0x6440, 0x54
	.global gUnk_081A41F8
gUnk_081A41F8: @ 0x081A41F8
	.incbin "build/assets/tables__rodata2.bin", 0x6494, 0x1C
	.global gUnk_081A4214
gUnk_081A4214: @ 0x081A4214
	.incbin "build/assets/tables__rodata2.bin", 0x64B0, 0x28
	.global gUnk_081A423C
gUnk_081A423C: @ 0x081A423C
	.incbin "build/assets/tables__rodata2.bin", 0x64D8, 0x40
	.global gUnk_081A427C
gUnk_081A427C: @ 0x081A427C
	.incbin "build/assets/tables__rodata2.bin", 0x6518, 0x20
	.global gUnk_081A429C
gUnk_081A429C: @ 0x081A429C
	.incbin "build/assets/tables__rodata2.bin", 0x6538, 0x8
	.global gUnk_081A42A4
gUnk_081A42A4: @ 0x081A42A4
	.incbin "build/assets/tables__rodata2.bin", 0x6540, 0x100
	.global gUnk_081A43A4
gUnk_081A43A4: @ 0x081A43A4
	.incbin "build/assets/tables__rodata2.bin", 0x6640, 0x40
	.global gUnk_081A43E4
gUnk_081A43E4: @ 0x081A43E4
	.incbin "build/assets/tables__rodata2.bin", 0x6680, 0x40
	.global gUnk_081A4424
gUnk_081A4424: @ 0x081A4424
	.incbin "build/assets/tables__rodata2.bin", 0x66C0, 0x20
	.global gUnk_081A4444
gUnk_081A4444: @ 0x081A4444
	.incbin "build/assets/tables__rodata2.bin", 0x66E0, 0x10
	.global gUnk_081A4454
gUnk_081A4454: @ 0x081A4454
	.incbin "build/assets/tables__rodata2.bin", 0x66F0, 0x20
	.global gUnk_081A4474
gUnk_081A4474: @ 0x081A4474
	.incbin "build/assets/tables__rodata2.bin", 0x6710, 0x60
	.global gUnk_081A44D4
gUnk_081A44D4: @ 0x081A44D4
	.incbin "build/assets/tables__rodata2.bin", 0x6770, 0x28
	.global gUnk_081A44FC
gUnk_081A44FC: @ 0x081A44FC
	.incbin "build/assets/tables__rodata2.bin", 0x6798, 0x20
	.global gUnk_081A451C
gUnk_081A451C: @ 0x081A451C
	.incbin "build/assets/tables__rodata2.bin", 0x67B8, 0x1110
	.global gUnk_081A562C
gUnk_081A562C: @ 0x081A562C
	.incbin "build/assets/tables__rodata2.bin", 0x78C8, 0xE0
	.global gUnk_081A570C
gUnk_081A570C: @ 0x081A570C
	.incbin "build/assets/tables__rodata2.bin", 0x79A8, 0x20
	.global gUnk_081A572C
gUnk_081A572C: @ 0x081A572C
	.incbin "build/assets/tables__rodata2.bin", 0x79C8, 0x2C
	.global gUnk_081A5758
gUnk_081A5758: @ 0x081A5758
	.incbin "build/assets/tables__rodata2.bin", 0x79F4, 0x9C0
	.global gUnk_081A6118
gUnk_081A6118: @ 0x081A6118
	.incbin "build/assets/tables__rodata2.bin", 0x83B4, 0x40C
	.global gUnk_081A6524
gUnk_081A6524: @ 0x081A6524
	.incbin "build/assets/tables__rodata2.bin", 0x87C0, 0x860
	.global gUnk_081A6D84
gUnk_081A6D84: @ 0x081A6D84
	.incbin "build/assets/tables__rodata2.bin", 0x9020, 0x8
	.global gUnk_081A6D8C
gUnk_081A6D8C: @ 0x081A6D8C
	.incbin "build/assets/tables__rodata2.bin", 0x9028, 0x118
	.global gUnk_081A6EA4
gUnk_081A6EA4: @ 0x081A6EA4
	.incbin "build/assets/tables__rodata2.bin", 0x9140, 0x8
	.global gUnk_081A6EAC
gUnk_081A6EAC: @ 0x081A6EAC
	.incbin "build/assets/tables__rodata2.bin", 0x9148, 0x8
	.global gUnk_081A6EB4
gUnk_081A6EB4: @ 0x081A6EB4
	.incbin "build/assets/tables__rodata2.bin", 0x9150, 0x240
	.global gUnk_081A70F4
gUnk_081A70F4: @ 0x081A70F4
	.incbin "build/assets/tables__rodata2.bin", 0x9390, 0x8
	.global gUnk_081A70FC
gUnk_081A70FC: @ 0x081A70FC
	.incbin "build/assets/tables__rodata2.bin", 0x9398, 0x48
	.global gUnk_081A7144
gUnk_081A7144: @ 0x081A7144
	.incbin "build/assets/tables__rodata2.bin", 0x93E0, 0x18
	.global gUnk_081A715C
gUnk_081A715C: @ 0x081A715C
	.incbin "build/assets/tables__rodata2.bin", 0x93F8, 0x70
	.global gUnk_081A71CC
gUnk_081A71CC: @ 0x081A71CC
	.incbin "build/assets/tables__rodata2.bin", 0x9468, 0x70
	.global gUnk_081A723C
gUnk_081A723C: @ 0x081A723C
	.incbin "build/assets/tables__rodata2.bin", 0x94D8, 0x10
	.global gUnk_081A724C
gUnk_081A724C: @ 0x081A724C
	.incbin "build/assets/tables__rodata2.bin", 0x94E8, 0x10
	.global gUnk_081A725C
gUnk_081A725C: @ 0x081A725C
	.incbin "build/assets/tables__rodata2.bin", 0x94F8, 0x44
	.global gUnk_081A72A0
gUnk_081A72A0: @ 0x081A72A0
	.incbin "build/assets/tables__rodata2.bin", 0x953C, 0x44
	.global gUnk_081A72E4
gUnk_081A72E4: @ 0x081A72E4
	.incbin "build/assets/tables__rodata2.bin", 0x9580, 0x4C
	.global gUnk_081A7330
gUnk_081A7330: @ 0x081A7330
	.incbin "build/assets/tables__rodata2.bin", 0x95CC, 0x44
	.global gUnk_081A7374
gUnk_081A7374: @ 0x081A7374
	.incbin "build/assets/tables__rodata2.bin", 0x9610, 0xE
	.global gUnk_081A7382
gUnk_081A7382: @ 0x081A7382
	.incbin "build/assets/tables__rodata2.bin", 0x961E, 0xE
	.global gUnk_081A7390
gUnk_081A7390: @ 0x081A7390
	.incbin "build/assets/tables__rodata2.bin", 0x962C, 0x10
	.global gUnk_081A73A0
gUnk_081A73A0: @ 0x081A73A0
	.incbin "build/assets/tables__rodata2.bin", 0x963C, 0x2EC
	.global gUnk_081A768C
gUnk_081A768C: @ 0x081A768C
	.incbin "build/assets/tables__rodata2.bin", 0x9928, 0x14
	.global gUnk_081A76A0
gUnk_081A76A0: @ 0x081A76A0
	.incbin "build/assets/tables__rodata2.bin", 0x993C, 0xC0
	.global gUnk_081A7760
gUnk_081A7760: @ 0x081A7760
	.incbin "build/assets/tables__rodata2.bin", 0x99FC, 0x4
	.global gUnk_081A7764
gUnk_081A7764: @ 0x081A7764
	.incbin "build/assets/tables__rodata2.bin", 0x9A00, 0x20
	.global gUnk_081A7784
gUnk_081A7784: @ 0x081A7784
	.incbin "build/assets/tables__rodata2.bin", 0x9A20, 0x24
	.global gUnk_081A77A8
gUnk_081A77A8: @ 0x081A77A8
	.incbin "build/assets/tables__rodata2.bin", 0x9A44, 0x100
	.global gUnk_081A78A8
gUnk_081A78A8: @ 0x081A78A8
	.incbin "build/assets/tables__rodata2.bin", 0x9B44, 0xC
	.global gUnk_081A78B4
gUnk_081A78B4: @ 0x081A78B4
	.incbin "build/assets/tables__rodata2.bin", 0x9B50, 0xBC
	.global gUnk_081A7970
gUnk_081A7970: @ 0x081A7970
	.incbin "build/assets/tables__rodata2.bin", 0x9C0C, 0x34
	.global gUnk_081A79A4
gUnk_081A79A4: @ 0x081A79A4
	.incbin "build/assets/tables__rodata2.bin", 0x9C40, 0x44
	.global gUnk_081A79E8
gUnk_081A79E8: @ 0x081A79E8
	.incbin "build/assets/tables__rodata2.bin", 0x9C84, 0x11
	.global gUnk_081A79F9
gUnk_081A79F9: @ 0x081A79F9
	.incbin "build/assets/tables__rodata2.bin", 0x9C95, 0x13
@ sound/lookup_tables (bin)
	.incbin "build/assets/sound__lookup_tables.bin", 0x0, 0x1C00
	.global gUnk_081A960C
gUnk_081A960C: @ 0x081A960C
	.incbin "build/assets/sound__lookup_tables.bin", 0x1C00, 0xC00
	.global gUnk_081AA20C
gUnk_081AA20C: @ 0x081AA20C
	.incbin "build/assets/sound__lookup_tables.bin", 0x2800, 0x1A40
@ tables/sine (bin)
	.global gUnk_081ABC4C
gUnk_081ABC4C: @ 0x081ABC4C
	.incbin "build/assets/tables__sine.bin", 0x0, 0x200
@ padding_081ABE4C (zero)
	.space 0x141B4
@ fonts/kanji_8x8.png (font1bpp)
	.global gUnk_081C0000
gUnk_081C0000: @ 0x081C0000
	.incbin "build/assets/fonts__kanji_8x8.png.bin", 0x0, 0x10200
@ fonts/kanji_10x10.png (font1bpp)
	.global gUnk_081D0200
gUnk_081D0200: @ 0x081D0200
	.incbin "build/assets/fonts__kanji_10x10.png.bin", 0x0, 0x28500
@ fonts/kanji_12x12.png (font1bpp)
	.global gUnk_081F8700
gUnk_081F8700: @ 0x081F8700
	.incbin "build/assets/fonts__kanji_12x12.png.bin", 0x0, 0x30600
@ fonts/latin_8x8.png (font1bpp)
	.global gUnk_08228D00
gUnk_08228D00: @ 0x08228D00
	.incbin "build/assets/fonts__latin_8x8.png.bin", 0x0, 0x800
@ fonts/latin_8x10.png (font1bpp)
	.global gUnk_08229500
gUnk_08229500: @ 0x08229500
	.incbin "build/assets/fonts__latin_8x10.png.bin", 0x0, 0xA00
@ fonts/latin_8x12.png (font1bpp)
	.global gUnk_08229F00
gUnk_08229F00: @ 0x08229F00
	.incbin "build/assets/fonts__latin_8x12.png.bin", 0x0, 0xC00
@ fonts/latin_8x16.png (font1bpp)
	.global gUnk_0822AB00
gUnk_0822AB00: @ 0x0822AB00
	.incbin "build/assets/fonts__latin_8x16.png.bin", 0x0, 0x1000
@ fonts/latin_8x8_bold.png (font1bpp)
	.global gUnk_0822BB00
gUnk_0822BB00: @ 0x0822BB00
	.incbin "build/assets/fonts__latin_8x8_bold.png.bin", 0x0, 0x800
@ gfx/system.pal (palette)
	.global gUnk_0822C300
gUnk_0822C300: @ 0x0822C300
	.incbin "build/assets/gfx__system.pal.bin", 0x0, 0x20
@ gfx/system_tiles.png (tiles4bpp)
	.global gUnk_0822C320
gUnk_0822C320: @ 0x0822C320
	.incbin "build/assets/gfx__system_tiles.png.bin", 0x0, 0x40
	.global gUnk_0822C360
gUnk_0822C360: @ 0x0822C360
	.incbin "build/assets/gfx__system_tiles.png.bin", 0x40, 0x3C0
@ cards/names.json (strings)
	.global gUnk_0822C720
gUnk_0822C720: @ 0x0822C720
	.incbin "build/assets/cards__names.json.bin", 0x0, 0xCD40
@ cards/unused_name_bank (zero)
	.space 0xCD40
@ cards/descriptions.json (strings)
	.global gUnk_082461A0
gUnk_082461A0: @ 0x082461A0
	.incbin "build/assets/cards__descriptions.json.bin", 0x0, 0x60360
@ cards/art (card_art)
	.global gUnk_082A6500
gUnk_082A6500: @ 0x082A6500
	.incbin "build/assets/cards__art.bin", 0x0, 0x361E60
	.global gUnk_08608360
gUnk_08608360: @ 0x08608360
	.incbin "build/assets/cards__art.bin", 0x361E60, 0x19A80
@ cards/stats.csv (card_stats)
	.global gUnk_08621DE0
gUnk_08621DE0: @ 0x08621DE0
	.incbin "build/assets/cards__stats.csv.bin", 0x0, 0xCD4
@ cards/id_to_number.json (u16)
	.global gUnk_08622AB4
gUnk_08622AB4: @ 0x08622AB4
	.incbin "build/assets/cards__id_to_number.json.bin", 0x0, 0x66A
	.global gUnk_0862311E
gUnk_0862311E: @ 0x0862311E
	.incbin "build/assets/cards__id_to_number.json.bin", 0x66A, 0x2
@ cards/passwords (bin)
	.global gUnk_08623120
gUnk_08623120: @ 0x08623120
	.incbin "build/assets/cards__passwords.bin", 0x0, 0x206
	.global gUnk_08623326
gUnk_08623326: @ 0x08623326
	.incbin "build/assets/cards__passwords.bin", 0x206, 0xACE
@ cards/number_to_id.json (u16)
	.global gUnk_08623DF4
gUnk_08623DF4: @ 0x08623DF4
	.incbin "build/assets/cards__number_to_id.json.bin", 0x0, 0x1C
	.global gUnk_08623E10
gUnk_08623E10: @ 0x08623E10
	.incbin "build/assets/cards__number_to_id.json.bin", 0x1C, 0xE
	.global gUnk_08623E1E
gUnk_08623E1E: @ 0x08623E1E
	.incbin "build/assets/cards__number_to_id.json.bin", 0x2A, 0x1A
	.global gUnk_08623E38
gUnk_08623E38: @ 0x08623E38
	.incbin "build/assets/cards__number_to_id.json.bin", 0x44, 0x6
	.global gUnk_08623E3E
gUnk_08623E3E: @ 0x08623E3E
	.incbin "build/assets/cards__number_to_id.json.bin", 0x4A, 0x6
	.global gUnk_08623E44
gUnk_08623E44: @ 0x08623E44
	.incbin "build/assets/cards__number_to_id.json.bin", 0x50, 0x22
	.global gUnk_08623E66
gUnk_08623E66: @ 0x08623E66
	.incbin "build/assets/cards__number_to_id.json.bin", 0x72, 0x8
	.global gUnk_08623E6E
gUnk_08623E6E: @ 0x08623E6E
	.incbin "build/assets/cards__number_to_id.json.bin", 0x7A, 0x4
	.global gUnk_08623E72
gUnk_08623E72: @ 0x08623E72
	.incbin "build/assets/cards__number_to_id.json.bin", 0x7E, 0xA
	.global gUnk_08623E7C
gUnk_08623E7C: @ 0x08623E7C
	.incbin "build/assets/cards__number_to_id.json.bin", 0x88, 0xC2
	.global gUnk_08623F3E
gUnk_08623F3E: @ 0x08623F3E
	.incbin "build/assets/cards__number_to_id.json.bin", 0x14A, 0xE0
	.global gUnk_0862401E
gUnk_0862401E: @ 0x0862401E
	.incbin "build/assets/cards__number_to_id.json.bin", 0x22A, 0x34
	.global gUnk_08624052
gUnk_08624052: @ 0x08624052
	.incbin "build/assets/cards__number_to_id.json.bin", 0x25E, 0x32
	.global gUnk_08624084
gUnk_08624084: @ 0x08624084
	.incbin "build/assets/cards__number_to_id.json.bin", 0x290, 0x4A
	.global gUnk_086240CE
gUnk_086240CE: @ 0x086240CE
	.incbin "build/assets/cards__number_to_id.json.bin", 0x2DA, 0x2C
	.global gUnk_086240FA
gUnk_086240FA: @ 0x086240FA
	.incbin "build/assets/cards__number_to_id.json.bin", 0x306, 0x4
	.global gUnk_086240FE
gUnk_086240FE: @ 0x086240FE
	.incbin "build/assets/cards__number_to_id.json.bin", 0x30A, 0xAA
	.global gUnk_086241A8
gUnk_086241A8: @ 0x086241A8
	.incbin "build/assets/cards__number_to_id.json.bin", 0x3B4, 0x9C
	.global gUnk_08624244
gUnk_08624244: @ 0x08624244
	.incbin "build/assets/cards__number_to_id.json.bin", 0x450, 0xD8
	.global gUnk_0862431C
gUnk_0862431C: @ 0x0862431C
	.incbin "build/assets/cards__number_to_id.json.bin", 0x528, 0xAC
	.global gUnk_086243C8
gUnk_086243C8: @ 0x086243C8
	.incbin "build/assets/cards__number_to_id.json.bin", 0x5D4, 0x20
	.global gUnk_086243E8
gUnk_086243E8: @ 0x086243E8
	.incbin "build/assets/cards__number_to_id.json.bin", 0x5F4, 0xA6
	.global gUnk_0862448E
gUnk_0862448E: @ 0x0862448E
	.incbin "build/assets/cards__number_to_id.json.bin", 0x69A, 0xDA
	.global gUnk_08624568
gUnk_08624568: @ 0x08624568
	.incbin "build/assets/cards__number_to_id.json.bin", 0x774, 0x14
	.global gUnk_0862457C
gUnk_0862457C: @ 0x0862457C
	.incbin "build/assets/cards__number_to_id.json.bin", 0x788, 0x4E
	.global gUnk_086245CA
gUnk_086245CA: @ 0x086245CA
	.incbin "build/assets/cards__number_to_id.json.bin", 0x7D6, 0xA
	.global gUnk_086245D4
gUnk_086245D4: @ 0x086245D4
	.incbin "build/assets/cards__number_to_id.json.bin", 0x7E0, 0xA6
	.global gUnk_0862467A
gUnk_0862467A: @ 0x0862467A
	.incbin "build/assets/cards__number_to_id.json.bin", 0x886, 0x42
	.global gUnk_086246BC
gUnk_086246BC: @ 0x086246BC
	.incbin "build/assets/cards__number_to_id.json.bin", 0x8C8, 0x48
	.global gUnk_08624704
gUnk_08624704: @ 0x08624704
	.incbin "build/assets/cards__number_to_id.json.bin", 0x910, 0x2C
	.global gUnk_08624730
gUnk_08624730: @ 0x08624730
	.incbin "build/assets/cards__number_to_id.json.bin", 0x93C, 0x28
	.global gUnk_08624758
gUnk_08624758: @ 0x08624758
	.incbin "build/assets/cards__number_to_id.json.bin", 0x964, 0x10
	.global gUnk_08624768
gUnk_08624768: @ 0x08624768
	.incbin "build/assets/cards__number_to_id.json.bin", 0x974, 0x42
	.global gUnk_086247AA
gUnk_086247AA: @ 0x086247AA
	.incbin "build/assets/cards__number_to_id.json.bin", 0x9B6, 0xC
	.global gUnk_086247B6
gUnk_086247B6: @ 0x086247B6
	.incbin "build/assets/cards__number_to_id.json.bin", 0x9C2, 0x12
	.global gUnk_086247C8
gUnk_086247C8: @ 0x086247C8
	.incbin "build/assets/cards__number_to_id.json.bin", 0x9D4, 0x7A
	.global gUnk_08624842
gUnk_08624842: @ 0x08624842
	.incbin "build/assets/cards__number_to_id.json.bin", 0xA4E, 0x6
	.global gUnk_08624848
gUnk_08624848: @ 0x08624848
	.incbin "build/assets/cards__number_to_id.json.bin", 0xA54, 0x24
	.global gUnk_0862486C
gUnk_0862486C: @ 0x0862486C
	.incbin "build/assets/cards__number_to_id.json.bin", 0xA78, 0x82
	.global gUnk_086248EE
gUnk_086248EE: @ 0x086248EE
	.incbin "build/assets/cards__number_to_id.json.bin", 0xAFA, 0xDA
	.global gUnk_086249C8
gUnk_086249C8: @ 0x086249C8
	.incbin "build/assets/cards__number_to_id.json.bin", 0xBD4, 0xC
	.global gUnk_086249D4
gUnk_086249D4: @ 0x086249D4
	.incbin "build/assets/cards__number_to_id.json.bin", 0xBE0, 0x1A
	.global gUnk_086249EE
gUnk_086249EE: @ 0x086249EE
	.incbin "build/assets/cards__number_to_id.json.bin", 0xBFA, 0x6
	.global gUnk_086249F4
gUnk_086249F4: @ 0x086249F4
	.incbin "build/assets/cards__number_to_id.json.bin", 0xC00, 0x4
	.global gUnk_086249F8
gUnk_086249F8: @ 0x086249F8
	.incbin "build/assets/cards__number_to_id.json.bin", 0xC04, 0x12
	.global gUnk_08624A0A
gUnk_08624A0A: @ 0x08624A0A
	.incbin "build/assets/cards__number_to_id.json.bin", 0xC16, 0x2
	.global gUnk_08624A0C
gUnk_08624A0C: @ 0x08624A0C
	.incbin "build/assets/cards__number_to_id.json.bin", 0xC18, 0x2C2
	.global gUnk_08624CCE
gUnk_08624CCE: @ 0x08624CCE
	.incbin "build/assets/cards__number_to_id.json.bin", 0xEDA, 0x2
	.global gUnk_08624CD0
gUnk_08624CD0: @ 0x08624CD0
	.incbin "build/assets/cards__number_to_id.json.bin", 0xEDC, 0x2
	.global gUnk_08624CD2
gUnk_08624CD2: @ 0x08624CD2
	.incbin "build/assets/cards__number_to_id.json.bin", 0xEDE, 0x22
	.global gUnk_08624CF4
gUnk_08624CF4: @ 0x08624CF4
	.incbin "build/assets/cards__number_to_id.json.bin", 0xF00, 0x100
@ cards/sort_keys.json (u16)
	.incbin "build/assets/cards__sort_keys.json.bin", 0x0, 0x66C
@ gfx/card_frames (bin)
	.global gUnk_08625460
gUnk_08625460: @ 0x08625460
	.incbin "build/assets/gfx__card_frames.bin", 0x0, 0x2698
	.global gUnk_08627AF8
gUnk_08627AF8: @ 0x08627AF8
	.incbin "build/assets/gfx__card_frames.bin", 0x2698, 0x2698
	.global gUnk_0862A190
gUnk_0862A190: @ 0x0862A190
	.incbin "build/assets/gfx__card_frames.bin", 0x4D30, 0x2698
	.global gUnk_0862C828
gUnk_0862C828: @ 0x0862C828
	.incbin "build/assets/gfx__card_frames.bin", 0x73C8, 0x2698
	.global gUnk_0862EEC0
gUnk_0862EEC0: @ 0x0862EEC0
	.incbin "build/assets/gfx__card_frames.bin", 0x9A60, 0x2698
	.global gUnk_08631558
gUnk_08631558: @ 0x08631558
	.incbin "build/assets/gfx__card_frames.bin", 0xC0F8, 0x2698
	.global gUnk_08633BF0
gUnk_08633BF0: @ 0x08633BF0
	.incbin "build/assets/gfx__card_frames.bin", 0xE790, 0x2698
@ gfx/bank_a (bin)
	.incbin "build/assets/gfx__bank_a.bin", 0x0, 0xC0
	.global gUnk_08636348
gUnk_08636348: @ 0x08636348
	.incbin "build/assets/gfx__bank_a.bin", 0xC0, 0x20
	.global gUnk_08636368
gUnk_08636368: @ 0x08636368
	.incbin "build/assets/gfx__bank_a.bin", 0xE0, 0x20
	.global gUnk_08636388
gUnk_08636388: @ 0x08636388
	.incbin "build/assets/gfx__bank_a.bin", 0x100, 0x320
	.global gUnk_086366A8
gUnk_086366A8: @ 0x086366A8
	.incbin "build/assets/gfx__bank_a.bin", 0x420, 0x80
	.global gUnk_08636728
gUnk_08636728: @ 0x08636728
	.incbin "build/assets/gfx__bank_a.bin", 0x4A0, 0x80
	.global gUnk_086367A8
gUnk_086367A8: @ 0x086367A8
	.incbin "build/assets/gfx__bank_a.bin", 0x520, 0x530
	.global gUnk_08636CD8
gUnk_08636CD8: @ 0x08636CD8
	.incbin "build/assets/gfx__bank_a.bin", 0xA50, 0xC8
	.global gUnk_08636DA0
gUnk_08636DA0: @ 0x08636DA0
	.incbin "build/assets/gfx__bank_a.bin", 0xB18, 0x5D4
	.global gUnk_08637374
gUnk_08637374: @ 0x08637374
	.incbin "build/assets/gfx__bank_a.bin", 0x10EC, 0x20
	.global gUnk_08637394
gUnk_08637394: @ 0x08637394
	.incbin "build/assets/gfx__bank_a.bin", 0x110C, 0xC0
	.global gUnk_08637454
gUnk_08637454: @ 0x08637454
	.incbin "build/assets/gfx__bank_a.bin", 0x11CC, 0xFB8
	.global gUnk_0863840C
gUnk_0863840C: @ 0x0863840C
	.incbin "build/assets/gfx__bank_a.bin", 0x2184, 0x20
	.global gUnk_0863842C
gUnk_0863842C: @ 0x0863842C
	.incbin "build/assets/gfx__bank_a.bin", 0x21A4, 0x140
	.global gUnk_0863856C
gUnk_0863856C: @ 0x0863856C
	.incbin "build/assets/gfx__bank_a.bin", 0x22E4, 0x20
	.global gUnk_0863858C
gUnk_0863858C: @ 0x0863858C
	.incbin "build/assets/gfx__bank_a.bin", 0x2304, 0x20
	.global gUnk_086385AC
gUnk_086385AC: @ 0x086385AC
	.incbin "build/assets/gfx__bank_a.bin", 0x2324, 0x20
	.global gUnk_086385CC
gUnk_086385CC: @ 0x086385CC
	.incbin "build/assets/gfx__bank_a.bin", 0x2344, 0x60
	.global gUnk_0863862C
gUnk_0863862C: @ 0x0863862C
	.incbin "build/assets/gfx__bank_a.bin", 0x23A4, 0x1130
	.global gUnk_0863975C
gUnk_0863975C: @ 0x0863975C
	.incbin "build/assets/gfx__bank_a.bin", 0x34D4, 0x6A0
	.global gUnk_08639DFC
gUnk_08639DFC: @ 0x08639DFC
	.incbin "build/assets/gfx__bank_a.bin", 0x3B74, 0x20
	.global gUnk_08639E1C
gUnk_08639E1C: @ 0x08639E1C
	.incbin "build/assets/gfx__bank_a.bin", 0x3B94, 0x2C00
	.global gUnk_0863CA1C
gUnk_0863CA1C: @ 0x0863CA1C
	.incbin "build/assets/gfx__bank_a.bin", 0x6794, 0x80
	.global gUnk_0863CA9C
gUnk_0863CA9C: @ 0x0863CA9C
	.incbin "build/assets/gfx__bank_a.bin", 0x6814, 0x20
	.global gUnk_0863CABC
gUnk_0863CABC: @ 0x0863CABC
	.incbin "build/assets/gfx__bank_a.bin", 0x6834, 0x80
	.global gUnk_0863CB3C
gUnk_0863CB3C: @ 0x0863CB3C
	.incbin "build/assets/gfx__bank_a.bin", 0x68B4, 0x20
	.global gUnk_0863CB5C
gUnk_0863CB5C: @ 0x0863CB5C
	.incbin "build/assets/gfx__bank_a.bin", 0x68D4, 0x120
	.global gUnk_0863CC7C
gUnk_0863CC7C: @ 0x0863CC7C
	.incbin "build/assets/gfx__bank_a.bin", 0x69F4, 0x200
	.global gUnk_0863CE7C
gUnk_0863CE7C: @ 0x0863CE7C
	.incbin "build/assets/gfx__bank_a.bin", 0x6BF4, 0x40
	.global gUnk_0863CEBC
gUnk_0863CEBC: @ 0x0863CEBC
	.incbin "build/assets/gfx__bank_a.bin", 0x6C34, 0x40
	.global gUnk_0863CEFC
gUnk_0863CEFC: @ 0x0863CEFC
	.incbin "build/assets/gfx__bank_a.bin", 0x6C74, 0x40
	.global gUnk_0863CF3C
gUnk_0863CF3C: @ 0x0863CF3C
	.incbin "build/assets/gfx__bank_a.bin", 0x6CB4, 0x1F0
	.global gUnk_0863D12C
gUnk_0863D12C: @ 0x0863D12C
	.incbin "build/assets/gfx__bank_a.bin", 0x6EA4, 0x1270
	.global gUnk_0863E39C
gUnk_0863E39C: @ 0x0863E39C
	.incbin "build/assets/gfx__bank_a.bin", 0x8114, 0x11B0
	.global gUnk_0863F54C
gUnk_0863F54C: @ 0x0863F54C
	.incbin "build/assets/gfx__bank_a.bin", 0x92C4, 0x383F0
	.global gUnk_0867793C
gUnk_0867793C: @ 0x0867793C
	.incbin "build/assets/gfx__bank_a.bin", 0x416B4, 0x20
	.global gUnk_0867795C
gUnk_0867795C: @ 0x0867795C
	.incbin "build/assets/gfx__bank_a.bin", 0x416D4, 0x20
	.global gUnk_0867797C
gUnk_0867797C: @ 0x0867797C
	.incbin "build/assets/gfx__bank_a.bin", 0x416F4, 0x800
	.global gUnk_0867817C
gUnk_0867817C: @ 0x0867817C
	.incbin "build/assets/gfx__bank_a.bin", 0x41EF4, 0x800
	.global gUnk_0867897C
gUnk_0867897C: @ 0x0867897C
	.incbin "build/assets/gfx__bank_a.bin", 0x426F4, 0x800
	.global gUnk_0867917C
gUnk_0867917C: @ 0x0867917C
	.incbin "build/assets/gfx__bank_a.bin", 0x42EF4, 0x800
	.global gUnk_0867997C
gUnk_0867997C: @ 0x0867997C
	.incbin "build/assets/gfx__bank_a.bin", 0x436F4, 0x800
	.global gUnk_0867A17C
gUnk_0867A17C: @ 0x0867A17C
	.incbin "build/assets/gfx__bank_a.bin", 0x43EF4, 0x800
	.global gUnk_0867A97C
gUnk_0867A97C: @ 0x0867A97C
	.incbin "build/assets/gfx__bank_a.bin", 0x446F4, 0x800
	.global gUnk_0867B17C
gUnk_0867B17C: @ 0x0867B17C
	.incbin "build/assets/gfx__bank_a.bin", 0x44EF4, 0x800
	.global gUnk_0867B97C
gUnk_0867B97C: @ 0x0867B97C
	.incbin "build/assets/gfx__bank_a.bin", 0x456F4, 0x200
	.global gUnk_0867BB7C
gUnk_0867BB7C: @ 0x0867BB7C
	.incbin "build/assets/gfx__bank_a.bin", 0x458F4, 0x2450
	.global gUnk_0867DFCC
gUnk_0867DFCC: @ 0x0867DFCC
	.incbin "build/assets/gfx__bank_a.bin", 0x47D44, 0x4F0
	.global gUnk_0867E4BC
gUnk_0867E4BC: @ 0x0867E4BC
	.incbin "build/assets/gfx__bank_a.bin", 0x48234, 0x200
	.global gUnk_0867E6BC
gUnk_0867E6BC: @ 0x0867E6BC
	.incbin "build/assets/gfx__bank_a.bin", 0x48434, 0x780
	.global gUnk_0867EE3C
gUnk_0867EE3C: @ 0x0867EE3C
	.incbin "build/assets/gfx__bank_a.bin", 0x48BB4, 0x20
	.global gUnk_0867EE5C
gUnk_0867EE5C: @ 0x0867EE5C
	.incbin "build/assets/gfx__bank_a.bin", 0x48BD4, 0x40
	.global gUnk_0867EE9C
gUnk_0867EE9C: @ 0x0867EE9C
	.incbin "build/assets/gfx__bank_a.bin", 0x48C14, 0x180
	.global gUnk_0867F01C
gUnk_0867F01C: @ 0x0867F01C
	.incbin "build/assets/gfx__bank_a.bin", 0x48D94, 0x20
	.global gUnk_0867F03C
gUnk_0867F03C: @ 0x0867F03C
	.incbin "build/assets/gfx__bank_a.bin", 0x48DB4, 0x600
	.global gUnk_0867F63C
gUnk_0867F63C: @ 0x0867F63C
	.incbin "build/assets/gfx__bank_a.bin", 0x493B4, 0x600
	.global gUnk_0867FC3C
gUnk_0867FC3C: @ 0x0867FC3C
	.incbin "build/assets/gfx__bank_a.bin", 0x499B4, 0x20
	.global gUnk_0867FC5C
gUnk_0867FC5C: @ 0x0867FC5C
	.incbin "build/assets/gfx__bank_a.bin", 0x499D4, 0x800
	.global gUnk_0868045C
gUnk_0868045C: @ 0x0868045C
	.incbin "build/assets/gfx__bank_a.bin", 0x4A1D4, 0x20
	.global gUnk_0868047C
gUnk_0868047C: @ 0x0868047C
	.incbin "build/assets/gfx__bank_a.bin", 0x4A1F4, 0x1000
	.global gUnk_0868147C
gUnk_0868147C: @ 0x0868147C
	.incbin "build/assets/gfx__bank_a.bin", 0x4B1F4, 0x20
	.global gUnk_0868149C
gUnk_0868149C: @ 0x0868149C
	.incbin "build/assets/gfx__bank_a.bin", 0x4B214, 0x1E0
	.global gUnk_0868167C
gUnk_0868167C: @ 0x0868167C
	.incbin "build/assets/gfx__bank_a.bin", 0x4B3F4, 0x200
	.global gUnk_0868187C
gUnk_0868187C: @ 0x0868187C
	.incbin "build/assets/gfx__bank_a.bin", 0x4B5F4, 0x500
	.global gUnk_08681D7C
gUnk_08681D7C: @ 0x08681D7C
	.incbin "build/assets/gfx__bank_a.bin", 0x4BAF4, 0x100
	.global gUnk_08681E7C
gUnk_08681E7C: @ 0x08681E7C
	.incbin "build/assets/gfx__bank_a.bin", 0x4BBF4, 0x600
	.global gUnk_0868247C
gUnk_0868247C: @ 0x0868247C
	.incbin "build/assets/gfx__bank_a.bin", 0x4C1F4, 0x200
	.global gUnk_0868267C
gUnk_0868267C: @ 0x0868267C
	.incbin "build/assets/gfx__bank_a.bin", 0x4C3F4, 0x2000
	.global gUnk_0868467C
gUnk_0868467C: @ 0x0868467C
	.incbin "build/assets/gfx__bank_a.bin", 0x4E3F4, 0x200
	.global gUnk_0868487C
gUnk_0868487C: @ 0x0868487C
	.incbin "build/assets/gfx__bank_a.bin", 0x4E5F4, 0x180
	.global gUnk_086849FC
gUnk_086849FC: @ 0x086849FC
	.incbin "build/assets/gfx__bank_a.bin", 0x4E774, 0x180
	.global gUnk_08684B7C
gUnk_08684B7C: @ 0x08684B7C
	.incbin "build/assets/gfx__bank_a.bin", 0x4E8F4, 0x380
	.global gUnk_08684EFC
gUnk_08684EFC: @ 0x08684EFC
	.incbin "build/assets/gfx__bank_a.bin", 0x4EC74, 0x680
	.global gUnk_0868557C
gUnk_0868557C: @ 0x0868557C
	.incbin "build/assets/gfx__bank_a.bin", 0x4F2F4, 0x20
	.global gUnk_0868559C
gUnk_0868559C: @ 0x0868559C
	.incbin "build/assets/gfx__bank_a.bin", 0x4F314, 0x2600
	.global gUnk_08687B9C
gUnk_08687B9C: @ 0x08687B9C
	.incbin "build/assets/gfx__bank_a.bin", 0x51914, 0x20
	.global gUnk_08687BBC
gUnk_08687BBC: @ 0x08687BBC
	.incbin "build/assets/gfx__bank_a.bin", 0x51934, 0x400
	.global gUnk_08687FBC
gUnk_08687FBC: @ 0x08687FBC
	.incbin "build/assets/gfx__bank_a.bin", 0x51D34, 0x400
	.global gUnk_086883BC
gUnk_086883BC: @ 0x086883BC
	.incbin "build/assets/gfx__bank_a.bin", 0x52134, 0x400
	.global gUnk_086887BC
gUnk_086887BC: @ 0x086887BC
	.incbin "build/assets/gfx__bank_a.bin", 0x52534, 0x400
	.global gUnk_08688BBC
gUnk_08688BBC: @ 0x08688BBC
	.incbin "build/assets/gfx__bank_a.bin", 0x52934, 0x400
	.global gUnk_08688FBC
gUnk_08688FBC: @ 0x08688FBC
	.incbin "build/assets/gfx__bank_a.bin", 0x52D34, 0x1C
	.global gUnk_08688FD8
gUnk_08688FD8: @ 0x08688FD8
	.incbin "build/assets/gfx__bank_a.bin", 0x52D50, 0x400
	.global gUnk_086893D8
gUnk_086893D8: @ 0x086893D8
	.incbin "build/assets/gfx__bank_a.bin", 0x53150, 0x36E8
	.global gUnk_0868CAC0
gUnk_0868CAC0: @ 0x0868CAC0
	.incbin "build/assets/gfx__bank_a.bin", 0x56838, 0x10D4
	.global gUnk_0868DB94
gUnk_0868DB94: @ 0x0868DB94
	.incbin "build/assets/gfx__bank_a.bin", 0x5790C, 0x10A4
	.global gUnk_0868EC38
gUnk_0868EC38: @ 0x0868EC38
	.incbin "build/assets/gfx__bank_a.bin", 0x589B0, 0x20D4
	.global gUnk_08690D0C
gUnk_08690D0C: @ 0x08690D0C
	.incbin "build/assets/gfx__bank_a.bin", 0x5AA84, 0x419C
	.global gUnk_08694EA8
gUnk_08694EA8: @ 0x08694EA8
	.incbin "build/assets/gfx__bank_a.bin", 0x5EC20, 0x2874
	.global gUnk_0869771C
gUnk_0869771C: @ 0x0869771C
	.incbin "build/assets/gfx__bank_a.bin", 0x61494, 0x1560
	.global gUnk_08698C7C
gUnk_08698C7C: @ 0x08698C7C
	.incbin "build/assets/gfx__bank_a.bin", 0x629F4, 0x20
	.global gUnk_08698C9C
gUnk_08698C9C: @ 0x08698C9C
	.incbin "build/assets/gfx__bank_a.bin", 0x62A14, 0x2080
	.global gUnk_0869AD1C
gUnk_0869AD1C: @ 0x0869AD1C
	.incbin "build/assets/gfx__bank_a.bin", 0x64A94, 0x20
	.global gUnk_0869AD3C
gUnk_0869AD3C: @ 0x0869AD3C
	.incbin "build/assets/gfx__bank_a.bin", 0x64AB4, 0x800
	.global gUnk_0869B53C
gUnk_0869B53C: @ 0x0869B53C
	.incbin "build/assets/gfx__bank_a.bin", 0x652B4, 0x20
	.global gUnk_0869B55C
gUnk_0869B55C: @ 0x0869B55C
	.incbin "build/assets/gfx__bank_a.bin", 0x652D4, 0xF00
	.global gUnk_0869C45C
gUnk_0869C45C: @ 0x0869C45C
	.incbin "build/assets/gfx__bank_a.bin", 0x661D4, 0x12FC
	.global gUnk_0869D758
gUnk_0869D758: @ 0x0869D758
	.incbin "build/assets/gfx__bank_a.bin", 0x674D0, 0x118C
	.global gUnk_0869E8E4
gUnk_0869E8E4: @ 0x0869E8E4
	.incbin "build/assets/gfx__bank_a.bin", 0x6865C, 0x5E8
	.global gUnk_0869EECC
gUnk_0869EECC: @ 0x0869EECC
	.incbin "build/assets/gfx__bank_a.bin", 0x68C44, 0x20
	.global gUnk_0869EEEC
gUnk_0869EEEC: @ 0x0869EEEC
	.incbin "build/assets/gfx__bank_a.bin", 0x68C64, 0x2400
	.global gUnk_086A12EC
gUnk_086A12EC: @ 0x086A12EC
	.incbin "build/assets/gfx__bank_a.bin", 0x6B064, 0x9600
	.global gUnk_086AA8EC
gUnk_086AA8EC: @ 0x086AA8EC
	.incbin "build/assets/gfx__bank_a.bin", 0x74664, 0x200
	.global gUnk_086AAAEC
gUnk_086AAAEC: @ 0x086AAAEC
	.incbin "build/assets/gfx__bank_a.bin", 0x74864, 0x14
	.global gUnk_086AAB00
gUnk_086AAB00: @ 0x086AAB00
	.incbin "build/assets/gfx__bank_a.bin", 0x74878, 0x20
	.global gUnk_086AAB20
gUnk_086AAB20: @ 0x086AAB20
	.incbin "build/assets/gfx__bank_a.bin", 0x74898, 0x20
	.global gUnk_086AAB40
gUnk_086AAB40: @ 0x086AAB40
	.incbin "build/assets/gfx__bank_a.bin", 0x748B8, 0x20
	.global gUnk_086AAB60
gUnk_086AAB60: @ 0x086AAB60
	.incbin "build/assets/gfx__bank_a.bin", 0x748D8, 0x20
	.global gUnk_086AAB80
gUnk_086AAB80: @ 0x086AAB80
	.incbin "build/assets/gfx__bank_a.bin", 0x748F8, 0x20
	.global gUnk_086AABA0
gUnk_086AABA0: @ 0x086AABA0
	.incbin "build/assets/gfx__bank_a.bin", 0x74918, 0x1C
	.global gUnk_086AABBC
gUnk_086AABBC: @ 0x086AABBC
	.incbin "build/assets/gfx__bank_a.bin", 0x74934, 0x20
	.global gUnk_086AABDC
gUnk_086AABDC: @ 0x086AABDC
	.incbin "build/assets/gfx__bank_a.bin", 0x74954, 0x24
	.global gUnk_086AAC00
gUnk_086AAC00: @ 0x086AAC00
	.incbin "build/assets/gfx__bank_a.bin", 0x74978, 0x20
	.global gUnk_086AAC20
gUnk_086AAC20: @ 0x086AAC20
	.incbin "build/assets/gfx__bank_a.bin", 0x74998, 0x8
	.global gUnk_086AAC28
gUnk_086AAC28: @ 0x086AAC28
	.incbin "build/assets/gfx__bank_a.bin", 0x749A0, 0x400
	.global gUnk_086AB028
gUnk_086AB028: @ 0x086AB028
	.incbin "build/assets/gfx__bank_a.bin", 0x74DA0, 0x400
	.global gUnk_086AB428
gUnk_086AB428: @ 0x086AB428
	.incbin "build/assets/gfx__bank_a.bin", 0x751A0, 0x400
	.global gUnk_086AB828
gUnk_086AB828: @ 0x086AB828
	.incbin "build/assets/gfx__bank_a.bin", 0x755A0, 0x800
	.global gUnk_086AC028
gUnk_086AC028: @ 0x086AC028
	.incbin "build/assets/gfx__bank_a.bin", 0x75DA0, 0x800
	.global gUnk_086AC828
gUnk_086AC828: @ 0x086AC828
	.incbin "build/assets/gfx__bank_a.bin", 0x765A0, 0x800
	.global gUnk_086AD028
gUnk_086AD028: @ 0x086AD028
	.incbin "build/assets/gfx__bank_a.bin", 0x76DA0, 0x800
	.global gUnk_086AD828
gUnk_086AD828: @ 0x086AD828
	.incbin "build/assets/gfx__bank_a.bin", 0x775A0, 0x800
	.global gUnk_086AE028
gUnk_086AE028: @ 0x086AE028
	.incbin "build/assets/gfx__bank_a.bin", 0x77DA0, 0x800
	.global gUnk_086AE828
gUnk_086AE828: @ 0x086AE828
	.incbin "build/assets/gfx__bank_a.bin", 0x785A0, 0x800
	.global gUnk_086AF028
gUnk_086AF028: @ 0x086AF028
	.incbin "build/assets/gfx__bank_a.bin", 0x78DA0, 0x800
	.global gUnk_086AF828
gUnk_086AF828: @ 0x086AF828
	.incbin "build/assets/gfx__bank_a.bin", 0x795A0, 0x200
	.global gUnk_086AFA28
gUnk_086AFA28: @ 0x086AFA28
	.incbin "build/assets/gfx__bank_a.bin", 0x797A0, 0x20
	.global gUnk_086AFA48
gUnk_086AFA48: @ 0x086AFA48
	.incbin "build/assets/gfx__bank_a.bin", 0x797C0, 0x200
	.global gUnk_086AFC48
gUnk_086AFC48: @ 0x086AFC48
	.incbin "build/assets/gfx__bank_a.bin", 0x799C0, 0x200
	.global gUnk_086AFE48
gUnk_086AFE48: @ 0x086AFE48
	.incbin "build/assets/gfx__bank_a.bin", 0x79BC0, 0x200
	.global gUnk_086B0048
gUnk_086B0048: @ 0x086B0048
	.incbin "build/assets/gfx__bank_a.bin", 0x79DC0, 0x200
	.global gUnk_086B0248
gUnk_086B0248: @ 0x086B0248
	.incbin "build/assets/gfx__bank_a.bin", 0x79FC0, 0x200
	.global gUnk_086B0448
gUnk_086B0448: @ 0x086B0448
	.incbin "build/assets/gfx__bank_a.bin", 0x7A1C0, 0x200
	.global gUnk_086B0648
gUnk_086B0648: @ 0x086B0648
	.incbin "build/assets/gfx__bank_a.bin", 0x7A3C0, 0x200
	.global gUnk_086B0848
gUnk_086B0848: @ 0x086B0848
	.incbin "build/assets/gfx__bank_a.bin", 0x7A5C0, 0x200
	.global gUnk_086B0A48
gUnk_086B0A48: @ 0x086B0A48
	.incbin "build/assets/gfx__bank_a.bin", 0x7A7C0, 0x200
	.global gUnk_086B0C48
gUnk_086B0C48: @ 0x086B0C48
	.incbin "build/assets/gfx__bank_a.bin", 0x7A9C0, 0x200
	.global gUnk_086B0E48
gUnk_086B0E48: @ 0x086B0E48
	.incbin "build/assets/gfx__bank_a.bin", 0x7ABC0, 0x200
	.global gUnk_086B1048
gUnk_086B1048: @ 0x086B1048
	.incbin "build/assets/gfx__bank_a.bin", 0x7ADC0, 0x200
	.global gUnk_086B1248
gUnk_086B1248: @ 0x086B1248
	.incbin "build/assets/gfx__bank_a.bin", 0x7AFC0, 0x200
	.global gUnk_086B1448
gUnk_086B1448: @ 0x086B1448
	.incbin "build/assets/gfx__bank_a.bin", 0x7B1C0, 0x200
	.global gUnk_086B1648
gUnk_086B1648: @ 0x086B1648
	.incbin "build/assets/gfx__bank_a.bin", 0x7B3C0, 0x200
	.global gUnk_086B1848
gUnk_086B1848: @ 0x086B1848
	.incbin "build/assets/gfx__bank_a.bin", 0x7B5C0, 0x200
	.global gUnk_086B1A48
gUnk_086B1A48: @ 0x086B1A48
	.incbin "build/assets/gfx__bank_a.bin", 0x7B7C0, 0x200
	.global gUnk_086B1C48
gUnk_086B1C48: @ 0x086B1C48
	.incbin "build/assets/gfx__bank_a.bin", 0x7B9C0, 0x200
	.global gUnk_086B1E48
gUnk_086B1E48: @ 0x086B1E48
	.incbin "build/assets/gfx__bank_a.bin", 0x7BBC0, 0x80
	.global gUnk_086B1EC8
gUnk_086B1EC8: @ 0x086B1EC8
	.incbin "build/assets/gfx__bank_a.bin", 0x7BC40, 0x80
	.global gUnk_086B1F48
gUnk_086B1F48: @ 0x086B1F48
	.incbin "build/assets/gfx__bank_a.bin", 0x7BCC0, 0x80
	.global gUnk_086B1FC8
gUnk_086B1FC8: @ 0x086B1FC8
	.incbin "build/assets/gfx__bank_a.bin", 0x7BD40, 0x80
	.global gUnk_086B2048
gUnk_086B2048: @ 0x086B2048
	.incbin "build/assets/gfx__bank_a.bin", 0x7BDC0, 0x80
	.global gUnk_086B20C8
gUnk_086B20C8: @ 0x086B20C8
	.incbin "build/assets/gfx__bank_a.bin", 0x7BE40, 0x80
	.global gUnk_086B2148
gUnk_086B2148: @ 0x086B2148
	.incbin "build/assets/gfx__bank_a.bin", 0x7BEC0, 0x20
	.global gUnk_086B2168
gUnk_086B2168: @ 0x086B2168
	.incbin "build/assets/gfx__bank_a.bin", 0x7BEE0, 0x2000
	.global gUnk_086B4168
gUnk_086B4168: @ 0x086B4168
	.incbin "build/assets/gfx__bank_a.bin", 0x7DEE0, 0x2000
	.global gUnk_086B6168
gUnk_086B6168: @ 0x086B6168
	.incbin "build/assets/gfx__bank_a.bin", 0x7FEE0, 0x200
	.global gUnk_086B6368
gUnk_086B6368: @ 0x086B6368
	.incbin "build/assets/gfx__bank_a.bin", 0x800E0, 0x200
	.global gUnk_086B6568
gUnk_086B6568: @ 0x086B6568
	.incbin "build/assets/gfx__bank_a.bin", 0x802E0, 0x2000
	.global gUnk_086B8568
gUnk_086B8568: @ 0x086B8568
	.incbin "build/assets/gfx__bank_a.bin", 0x822E0, 0x9600
	.global gUnk_086C1B68
gUnk_086C1B68: @ 0x086C1B68
	.incbin "build/assets/gfx__bank_a.bin", 0x8B8E0, 0x200
	.global gUnk_086C1D68
gUnk_086C1D68: @ 0x086C1D68
	.incbin "build/assets/gfx__bank_a.bin", 0x8BAE0, 0x2000
	.global gUnk_086C3D68
gUnk_086C3D68: @ 0x086C3D68
	.incbin "build/assets/gfx__bank_a.bin", 0x8DAE0, 0x2000
	.global gUnk_086C5D68
gUnk_086C5D68: @ 0x086C5D68
	.incbin "build/assets/gfx__bank_a.bin", 0x8FAE0, 0x2000
	.global gUnk_086C7D68
gUnk_086C7D68: @ 0x086C7D68
	.incbin "build/assets/gfx__bank_a.bin", 0x91AE0, 0x2000
	.global gUnk_086C9D68
gUnk_086C9D68: @ 0x086C9D68
	.incbin "build/assets/gfx__bank_a.bin", 0x93AE0, 0x4B0
	.global gUnk_086CA218
gUnk_086CA218: @ 0x086CA218
	.incbin "build/assets/gfx__bank_a.bin", 0x93F90, 0x4B0
	.global gUnk_086CA6C8
gUnk_086CA6C8: @ 0x086CA6C8
	.incbin "build/assets/gfx__bank_a.bin", 0x94440, 0x4B0
	.global gUnk_086CAB78
gUnk_086CAB78: @ 0x086CAB78
	.incbin "build/assets/gfx__bank_a.bin", 0x948F0, 0x200
	.global gUnk_086CAD78
gUnk_086CAD78: @ 0x086CAD78
	.incbin "build/assets/gfx__bank_a.bin", 0x94AF0, 0x2000
	.global gUnk_086CCD78
gUnk_086CCD78: @ 0x086CCD78
	.incbin "build/assets/gfx__bank_a.bin", 0x96AF0, 0x2000
	.global gUnk_086CED78
gUnk_086CED78: @ 0x086CED78
	.incbin "build/assets/gfx__bank_a.bin", 0x98AF0, 0xA00
	.global gUnk_086CF778
gUnk_086CF778: @ 0x086CF778
	.incbin "build/assets/gfx__bank_a.bin", 0x994F0, 0xA00
	.global gUnk_086D0178
gUnk_086D0178: @ 0x086D0178
	.incbin "build/assets/gfx__bank_a.bin", 0x99EF0, 0x2000
	.global gUnk_086D2178
gUnk_086D2178: @ 0x086D2178
	.incbin "build/assets/gfx__bank_a.bin", 0x9BEF0, 0x2000
	.global gUnk_086D4178
gUnk_086D4178: @ 0x086D4178
	.incbin "build/assets/gfx__bank_a.bin", 0x9DEF0, 0x2000
	.global gUnk_086D6178
gUnk_086D6178: @ 0x086D6178
	.incbin "build/assets/gfx__bank_a.bin", 0x9FEF0, 0x2000
	.global gUnk_086D8178
gUnk_086D8178: @ 0x086D8178
	.incbin "build/assets/gfx__bank_a.bin", 0xA1EF0, 0x2000
	.global gUnk_086DA178
gUnk_086DA178: @ 0x086DA178
	.incbin "build/assets/gfx__bank_a.bin", 0xA3EF0, 0x2000
	.global gUnk_086DC178
gUnk_086DC178: @ 0x086DC178
	.incbin "build/assets/gfx__bank_a.bin", 0xA5EF0, 0x2000
	.global gUnk_086DE178
gUnk_086DE178: @ 0x086DE178
	.incbin "build/assets/gfx__bank_a.bin", 0xA7EF0, 0x302C
	.global gUnk_086E11A4
gUnk_086E11A4: @ 0x086E11A4
	.incbin "build/assets/gfx__bank_a.bin", 0xAAF1C, 0xAC8
	.global gUnk_086E1C6C
gUnk_086E1C6C: @ 0x086E1C6C
	.incbin "build/assets/gfx__bank_a.bin", 0xAB9E4, 0x564
	.global gUnk_086E21D0
gUnk_086E21D0: @ 0x086E21D0
	.incbin "build/assets/gfx__bank_a.bin", 0xABF48, 0x100
	.global gUnk_086E22D0
gUnk_086E22D0: @ 0x086E22D0
	.incbin "build/assets/gfx__bank_a.bin", 0xAC048, 0x200
	.global gUnk_086E24D0
gUnk_086E24D0: @ 0x086E24D0
	.incbin "build/assets/gfx__bank_a.bin", 0xAC248, 0x200
	.global gUnk_086E26D0
gUnk_086E26D0: @ 0x086E26D0
	.incbin "build/assets/gfx__bank_a.bin", 0xAC448, 0x960
	.global gUnk_086E3030
gUnk_086E3030: @ 0x086E3030
	.incbin "build/assets/gfx__bank_a.bin", 0xACDA8, 0x2000
	.global gUnk_086E5030
gUnk_086E5030: @ 0x086E5030
	.incbin "build/assets/gfx__bank_a.bin", 0xAEDA8, 0x2000
	.global gUnk_086E7030
gUnk_086E7030: @ 0x086E7030
	.incbin "build/assets/gfx__bank_a.bin", 0xB0DA8, 0x2000
	.global gUnk_086E9030
gUnk_086E9030: @ 0x086E9030
	.incbin "build/assets/gfx__bank_a.bin", 0xB2DA8, 0x2000
	.global gUnk_086EB030
gUnk_086EB030: @ 0x086EB030
	.incbin "build/assets/gfx__bank_a.bin", 0xB4DA8, 0x2000
	.global gUnk_086ED030
gUnk_086ED030: @ 0x086ED030
	.incbin "build/assets/gfx__bank_a.bin", 0xB6DA8, 0x80
	.global gUnk_086ED0B0
gUnk_086ED0B0: @ 0x086ED0B0
	.incbin "build/assets/gfx__bank_a.bin", 0xB6E28, 0xE0
	.global gUnk_086ED190
gUnk_086ED190: @ 0x086ED190
	.incbin "build/assets/gfx__bank_a.bin", 0xB6F08, 0x20
	.global gUnk_086ED1B0
gUnk_086ED1B0: @ 0x086ED1B0
	.incbin "build/assets/gfx__bank_a.bin", 0xB6F28, 0x200
	.global gUnk_086ED3B0
gUnk_086ED3B0: @ 0x086ED3B0
	.incbin "build/assets/gfx__bank_a.bin", 0xB7128, 0x2000
	.global gUnk_086EF3B0
gUnk_086EF3B0: @ 0x086EF3B0
	.incbin "build/assets/gfx__bank_a.bin", 0xB9128, 0x1C00
	.global gUnk_086F0FB0
gUnk_086F0FB0: @ 0x086F0FB0
	.incbin "build/assets/gfx__bank_a.bin", 0xBAD28, 0x400
	.global gUnk_086F13B0
gUnk_086F13B0: @ 0x086F13B0
	.incbin "build/assets/gfx__bank_a.bin", 0xBB128, 0x400
	.global gUnk_086F17B0
gUnk_086F17B0: @ 0x086F17B0
	.incbin "build/assets/gfx__bank_a.bin", 0xBB528, 0x24
	.global gUnk_086F17D4
gUnk_086F17D4: @ 0x086F17D4
	.incbin "build/assets/gfx__bank_a.bin", 0xBB54C, 0xC
	.global gUnk_086F17E0
gUnk_086F17E0: @ 0x086F17E0
	.incbin "build/assets/gfx__bank_a.bin", 0xBB558, 0x8
	.global gUnk_086F17E8
gUnk_086F17E8: @ 0x086F17E8
	.incbin "build/assets/gfx__bank_a.bin", 0xBB560, 0x328
	.global gUnk_086F1B10
gUnk_086F1B10: @ 0x086F1B10
	.incbin "build/assets/gfx__bank_a.bin", 0xBB888, 0x150
	.global gUnk_086F1C60
gUnk_086F1C60: @ 0x086F1C60
	.incbin "build/assets/gfx__bank_a.bin", 0xBB9D8, 0x200
	.global gUnk_086F1E60
gUnk_086F1E60: @ 0x086F1E60
	.incbin "build/assets/gfx__bank_a.bin", 0xBBBD8, 0x200
	.global gUnk_086F2060
gUnk_086F2060: @ 0x086F2060
	.incbin "build/assets/gfx__bank_a.bin", 0xBBDD8, 0x2000
	.global gUnk_086F4060
gUnk_086F4060: @ 0x086F4060
	.incbin "build/assets/gfx__bank_a.bin", 0xBDDD8, 0x140
	.global gUnk_086F41A0
gUnk_086F41A0: @ 0x086F41A0
	.incbin "build/assets/gfx__bank_a.bin", 0xBDF18, 0x1EC0
	.global gUnk_086F6060
gUnk_086F6060: @ 0x086F6060
	.incbin "build/assets/gfx__bank_a.bin", 0xBFDD8, 0x2000
	.global gUnk_086F8060
gUnk_086F8060: @ 0x086F8060
	.incbin "build/assets/gfx__bank_a.bin", 0xC1DD8, 0x2000
	.global gUnk_086FA060
gUnk_086FA060: @ 0x086FA060
	.incbin "build/assets/gfx__bank_a.bin", 0xC3DD8, 0x2000
	.global gUnk_086FC060
gUnk_086FC060: @ 0x086FC060
	.incbin "build/assets/gfx__bank_a.bin", 0xC5DD8, 0x80
	.global gUnk_086FC0E0
gUnk_086FC0E0: @ 0x086FC0E0
	.incbin "build/assets/gfx__bank_a.bin", 0xC5E58, 0x4B0
	.global gUnk_086FC590
gUnk_086FC590: @ 0x086FC590
	.incbin "build/assets/gfx__bank_a.bin", 0xC6308, 0x4B0
	.global gUnk_086FCA40
gUnk_086FCA40: @ 0x086FCA40
	.incbin "build/assets/gfx__bank_a.bin", 0xC67B8, 0x690
	.global gUnk_086FD0D0
gUnk_086FD0D0: @ 0x086FD0D0
	.incbin "build/assets/gfx__bank_a.bin", 0xC6E48, 0x4B0
	.global gUnk_086FD580
gUnk_086FD580: @ 0x086FD580
	.incbin "build/assets/gfx__bank_a.bin", 0xC72F8, 0x2D0
	.global gUnk_086FD850
gUnk_086FD850: @ 0x086FD850
	.incbin "build/assets/gfx__bank_a.bin", 0xC75C8, 0xD4
	.global gUnk_086FD924
gUnk_086FD924: @ 0x086FD924
	.incbin "build/assets/gfx__bank_a.bin", 0xC769C, 0x200
	.global gUnk_086FDB24
gUnk_086FDB24: @ 0x086FDB24
	.incbin "build/assets/gfx__bank_a.bin", 0xC789C, 0x2000
	.global gUnk_086FFB24
gUnk_086FFB24: @ 0x086FFB24
	.incbin "build/assets/gfx__bank_a.bin", 0xC989C, 0x2000
	.global gUnk_08701B24
gUnk_08701B24: @ 0x08701B24
	.incbin "build/assets/gfx__bank_a.bin", 0xCB89C, 0x80
	.global gUnk_08701BA4
gUnk_08701BA4: @ 0x08701BA4
	.incbin "build/assets/gfx__bank_a.bin", 0xCB91C, 0x4B0
	.global gUnk_08702054
gUnk_08702054: @ 0x08702054
	.incbin "build/assets/gfx__bank_a.bin", 0xCBDCC, 0x4B0
	.global gUnk_08702504
gUnk_08702504: @ 0x08702504
	.incbin "build/assets/gfx__bank_a.bin", 0xCC27C, 0xD4
	.global gUnk_087025D8
gUnk_087025D8: @ 0x087025D8
	.incbin "build/assets/gfx__bank_a.bin", 0xCC350, 0x4B0
	.global gUnk_08702A88
gUnk_08702A88: @ 0x08702A88
	.incbin "build/assets/gfx__bank_a.bin", 0xCC800, 0x80
	.global gUnk_08702B08
gUnk_08702B08: @ 0x08702B08
	.incbin "build/assets/gfx__bank_a.bin", 0xCC880, 0xE0
	.global gUnk_08702BE8
gUnk_08702BE8: @ 0x08702BE8
	.incbin "build/assets/gfx__bank_a.bin", 0xCC960, 0x20
	.global gUnk_08702C08
gUnk_08702C08: @ 0x08702C08
	.incbin "build/assets/gfx__bank_a.bin", 0xCC980, 0x2140
	.global gUnk_08704D48
gUnk_08704D48: @ 0x08704D48
	.incbin "build/assets/gfx__bank_a.bin", 0xCEAC0, 0xA0
	.global gUnk_08704DE8
gUnk_08704DE8: @ 0x08704DE8
	.incbin "build/assets/gfx__bank_a.bin", 0xCEB60, 0xA0
	.global gUnk_08704E88
gUnk_08704E88: @ 0x08704E88
	.incbin "build/assets/gfx__bank_a.bin", 0xCEC00, 0x60
	.global gUnk_08704EE8
gUnk_08704EE8: @ 0x08704EE8
	.incbin "build/assets/gfx__bank_a.bin", 0xCEC60, 0xC0
	.global gUnk_08704FA8
gUnk_08704FA8: @ 0x08704FA8
	.incbin "build/assets/gfx__bank_a.bin", 0xCED20, 0xA0
	.global gUnk_08705048
gUnk_08705048: @ 0x08705048
	.incbin "build/assets/gfx__bank_a.bin", 0xCEDC0, 0x140
	.global gUnk_08705188
gUnk_08705188: @ 0x08705188
	.incbin "build/assets/gfx__bank_a.bin", 0xCEF00, 0x140
	.global gUnk_087052C8
gUnk_087052C8: @ 0x087052C8
	.incbin "build/assets/gfx__bank_a.bin", 0xCF040, 0x140
	.global gUnk_08705408
gUnk_08705408: @ 0x08705408
	.incbin "build/assets/gfx__bank_a.bin", 0xCF180, 0x220
	.global gUnk_08705628
gUnk_08705628: @ 0x08705628
	.incbin "build/assets/gfx__bank_a.bin", 0xCF3A0, 0xA0
	.global gUnk_087056C8
gUnk_087056C8: @ 0x087056C8
	.incbin "build/assets/gfx__bank_a.bin", 0xCF440, 0xA0
	.global gUnk_08705768
gUnk_08705768: @ 0x08705768
	.incbin "build/assets/gfx__bank_a.bin", 0xCF4E0, 0xA0
	.global gUnk_08705808
gUnk_08705808: @ 0x08705808
	.incbin "build/assets/gfx__bank_a.bin", 0xCF580, 0xA0
	.global gUnk_087058A8
gUnk_087058A8: @ 0x087058A8
	.incbin "build/assets/gfx__bank_a.bin", 0xCF620, 0xA0
	.global gUnk_08705948
gUnk_08705948: @ 0x08705948
	.incbin "build/assets/gfx__bank_a.bin", 0xCF6C0, 0xA0
	.global gUnk_087059E8
gUnk_087059E8: @ 0x087059E8
	.incbin "build/assets/gfx__bank_a.bin", 0xCF760, 0xA0
	.global gUnk_08705A88
gUnk_08705A88: @ 0x08705A88
	.incbin "build/assets/gfx__bank_a.bin", 0xCF800, 0xA0
	.global gUnk_08705B28
gUnk_08705B28: @ 0x08705B28
	.incbin "build/assets/gfx__bank_a.bin", 0xCF8A0, 0xA0
	.global gUnk_08705BC8
gUnk_08705BC8: @ 0x08705BC8
	.incbin "build/assets/gfx__bank_a.bin", 0xCF940, 0xA0
	.global gUnk_08705C68
gUnk_08705C68: @ 0x08705C68
	.incbin "build/assets/gfx__bank_a.bin", 0xCF9E0, 0xA0
	.global gUnk_08705D08
gUnk_08705D08: @ 0x08705D08
	.incbin "build/assets/gfx__bank_a.bin", 0xCFA80, 0xA0
	.global gUnk_08705DA8
gUnk_08705DA8: @ 0x08705DA8
	.incbin "build/assets/gfx__bank_a.bin", 0xCFB20, 0xA0
	.global gUnk_08705E48
gUnk_08705E48: @ 0x08705E48
	.incbin "build/assets/gfx__bank_a.bin", 0xCFBC0, 0xA0
	.global gUnk_08705EE8
gUnk_08705EE8: @ 0x08705EE8
	.incbin "build/assets/gfx__bank_a.bin", 0xCFC60, 0xA0
	.global gUnk_08705F88
gUnk_08705F88: @ 0x08705F88
	.incbin "build/assets/gfx__bank_a.bin", 0xCFD00, 0xA0
	.global gUnk_08706028
gUnk_08706028: @ 0x08706028
	.incbin "build/assets/gfx__bank_a.bin", 0xCFDA0, 0xA0
	.global gUnk_087060C8
gUnk_087060C8: @ 0x087060C8
	.incbin "build/assets/gfx__bank_a.bin", 0xCFE40, 0xA0
	.global gUnk_08706168
gUnk_08706168: @ 0x08706168
	.incbin "build/assets/gfx__bank_a.bin", 0xCFEE0, 0xA0
	.global gUnk_08706208
gUnk_08706208: @ 0x08706208
	.incbin "build/assets/gfx__bank_a.bin", 0xCFF80, 0xA0
	.global gUnk_087062A8
gUnk_087062A8: @ 0x087062A8
	.incbin "build/assets/gfx__bank_a.bin", 0xD0020, 0xA0
	.global gUnk_08706348
gUnk_08706348: @ 0x08706348
	.incbin "build/assets/gfx__bank_a.bin", 0xD00C0, 0xA0
	.global gUnk_087063E8
gUnk_087063E8: @ 0x087063E8
	.incbin "build/assets/gfx__bank_a.bin", 0xD0160, 0x140
	.global gUnk_08706528
gUnk_08706528: @ 0x08706528
	.incbin "build/assets/gfx__bank_a.bin", 0xD02A0, 0x140
	.global gUnk_08706668
gUnk_08706668: @ 0x08706668
	.incbin "build/assets/gfx__bank_a.bin", 0xD03E0, 0x140
	.global gUnk_087067A8
gUnk_087067A8: @ 0x087067A8
	.incbin "build/assets/gfx__bank_a.bin", 0xD0520, 0x140
	.global gUnk_087068E8
gUnk_087068E8: @ 0x087068E8
	.incbin "build/assets/gfx__bank_a.bin", 0xD0660, 0x140
	.global gUnk_08706A28
gUnk_08706A28: @ 0x08706A28
	.incbin "build/assets/gfx__bank_a.bin", 0xD07A0, 0x140
	.global gUnk_08706B68
gUnk_08706B68: @ 0x08706B68
	.incbin "build/assets/gfx__bank_a.bin", 0xD08E0, 0x140
	.global gUnk_08706CA8
gUnk_08706CA8: @ 0x08706CA8
	.incbin "build/assets/gfx__bank_a.bin", 0xD0A20, 0x140
	.global gUnk_08706DE8
gUnk_08706DE8: @ 0x08706DE8
	.incbin "build/assets/gfx__bank_a.bin", 0xD0B60, 0x140
	.global gUnk_08706F28
gUnk_08706F28: @ 0x08706F28
	.incbin "build/assets/gfx__bank_a.bin", 0xD0CA0, 0x180
	.global gUnk_087070A8
gUnk_087070A8: @ 0x087070A8
	.incbin "build/assets/gfx__bank_a.bin", 0xD0E20, 0x180
	.global gUnk_08707228
gUnk_08707228: @ 0x08707228
	.incbin "build/assets/gfx__bank_a.bin", 0xD0FA0, 0x180
	.global gUnk_087073A8
gUnk_087073A8: @ 0x087073A8
	.incbin "build/assets/gfx__bank_a.bin", 0xD1120, 0x180
	.global gUnk_08707528
gUnk_08707528: @ 0x08707528
	.incbin "build/assets/gfx__bank_a.bin", 0xD12A0, 0x180
	.global gUnk_087076A8
gUnk_087076A8: @ 0x087076A8
	.incbin "build/assets/gfx__bank_a.bin", 0xD1420, 0x180
	.global gUnk_08707828
gUnk_08707828: @ 0x08707828
	.incbin "build/assets/gfx__bank_a.bin", 0xD15A0, 0x80
	.global gUnk_087078A8
gUnk_087078A8: @ 0x087078A8
	.incbin "build/assets/gfx__bank_a.bin", 0xD1620, 0x80
	.global gUnk_08707928
gUnk_08707928: @ 0x08707928
	.incbin "build/assets/gfx__bank_a.bin", 0xD16A0, 0x80
	.global gUnk_087079A8
gUnk_087079A8: @ 0x087079A8
	.incbin "build/assets/gfx__bank_a.bin", 0xD1720, 0x80
	.global gUnk_08707A28
gUnk_08707A28: @ 0x08707A28
	.incbin "build/assets/gfx__bank_a.bin", 0xD17A0, 0x80
	.global gUnk_08707AA8
gUnk_08707AA8: @ 0x08707AA8
	.incbin "build/assets/gfx__bank_a.bin", 0xD1820, 0x80
	.global gUnk_08707B28
gUnk_08707B28: @ 0x08707B28
	.incbin "build/assets/gfx__bank_a.bin", 0xD18A0, 0x1AB8
	.global gUnk_087095E0
gUnk_087095E0: @ 0x087095E0
	.incbin "build/assets/gfx__bank_a.bin", 0xD3358, 0x1000
	.global gUnk_0870A5E0
gUnk_0870A5E0: @ 0x0870A5E0
	.incbin "build/assets/gfx__bank_a.bin", 0xD4358, 0x1000
	.global gUnk_0870B5E0
gUnk_0870B5E0: @ 0x0870B5E0
	.incbin "build/assets/gfx__bank_a.bin", 0xD5358, 0x20
	.global gUnk_0870B600
gUnk_0870B600: @ 0x0870B600
	.incbin "build/assets/gfx__bank_a.bin", 0xD5378, 0x20
	.global gUnk_0870B620
gUnk_0870B620: @ 0x0870B620
	.incbin "build/assets/gfx__bank_a.bin", 0xD5398, 0x1000
	.global gUnk_0870C620
gUnk_0870C620: @ 0x0870C620
	.incbin "build/assets/gfx__bank_a.bin", 0xD6398, 0x20
@ gfx/scene_sets_0_4 (bin)
	.incbin "build/assets/gfx__scene_sets_0_4.bin", 0x0, 0xF010
@ gfx/small_graphics (bin)
	.global gUnk_0871B650
gUnk_0871B650: @ 0x0871B650
	.incbin "build/assets/gfx__small_graphics.bin", 0x0, 0x200
	.global gUnk_0871B850
gUnk_0871B850: @ 0x0871B850
	.incbin "build/assets/gfx__small_graphics.bin", 0x200, 0x1000
	.global gUnk_0871C850
gUnk_0871C850: @ 0x0871C850
	.incbin "build/assets/gfx__small_graphics.bin", 0x1200, 0x200
	.global gUnk_0871CA50
gUnk_0871CA50: @ 0x0871CA50
	.incbin "build/assets/gfx__small_graphics.bin", 0x1400, 0x140
	.global gUnk_0871CB90
gUnk_0871CB90: @ 0x0871CB90
	.incbin "build/assets/gfx__small_graphics.bin", 0x1540, 0x2C0
@ gfx/mode4_bitmaps (bin)
	.incbin "build/assets/gfx__mode4_bitmaps.bin", 0x0, 0x2F800
@ gfx/dialogue_box (bin)
	.incbin "build/assets/gfx__dialogue_box.bin", 0x0, 0xF60
	.global gUnk_0874D5B0
gUnk_0874D5B0: @ 0x0874D5B0
	.incbin "build/assets/gfx__dialogue_box.bin", 0xF60, 0x2
	.global gUnk_0874D5B2
gUnk_0874D5B2: @ 0x0874D5B2
	.incbin "build/assets/gfx__dialogue_box.bin", 0xF62, 0x2
	.global gUnk_0874D5B4
gUnk_0874D5B4: @ 0x0874D5B4
	.incbin "build/assets/gfx__dialogue_box.bin", 0xF64, 0xB50
	.global gUnk_0874E104
gUnk_0874E104: @ 0x0874E104
	.incbin "build/assets/gfx__dialogue_box.bin", 0x1AB4, 0x200
	.global gUnk_0874E304
gUnk_0874E304: @ 0x0874E304
	.incbin "build/assets/gfx__dialogue_box.bin", 0x1CB4, 0x20
@ gfx/scene_sets_5_30 (bin)
	.incbin "build/assets/gfx__scene_sets_5_30.bin", 0x0, 0x6F784
@ gfx/bank_b (bin)
	.global gUnk_087BDAA8
gUnk_087BDAA8: @ 0x087BDAA8
	.incbin "build/assets/gfx__bank_b.bin", 0x0, 0x2AC4
	.global gUnk_087C056C
gUnk_087C056C: @ 0x087C056C
	.incbin "build/assets/gfx__bank_b.bin", 0x2AC4, 0x768
	.global gUnk_087C0CD4
gUnk_087C0CD4: @ 0x087C0CD4
	.incbin "build/assets/gfx__bank_b.bin", 0x322C, 0x10F8
	.global gUnk_087C1DCC
gUnk_087C1DCC: @ 0x087C1DCC
	.incbin "build/assets/gfx__bank_b.bin", 0x4324, 0xC08
	.global gUnk_087C29D4
gUnk_087C29D4: @ 0x087C29D4
	.incbin "build/assets/gfx__bank_b.bin", 0x4F2C, 0x9600
	.global gUnk_087CBFD4
gUnk_087CBFD4: @ 0x087CBFD4
	.incbin "build/assets/gfx__bank_b.bin", 0xE52C, 0x200
	.global gUnk_087CC1D4
gUnk_087CC1D4: @ 0x087CC1D4
	.incbin "build/assets/gfx__bank_b.bin", 0xE72C, 0x4000
	.global gUnk_087D01D4
gUnk_087D01D4: @ 0x087D01D4
	.incbin "build/assets/gfx__bank_b.bin", 0x1272C, 0x20
	.global gUnk_087D01F4
gUnk_087D01F4: @ 0x087D01F4
	.incbin "build/assets/gfx__bank_b.bin", 0x1274C, 0x2738
	.global gUnk_087D292C
gUnk_087D292C: @ 0x087D292C
	.incbin "build/assets/gfx__bank_b.bin", 0x14E84, 0x21F8
	.global gUnk_087D4B24
gUnk_087D4B24: @ 0x087D4B24
	.incbin "build/assets/gfx__bank_b.bin", 0x1707C, 0x9D34
	.global gUnk_087DE858
gUnk_087DE858: @ 0x087DE858
	.incbin "build/assets/gfx__bank_b.bin", 0x20DB0, 0x20
	.global gUnk_087DE878
gUnk_087DE878: @ 0x087DE878
	.incbin "build/assets/gfx__bank_b.bin", 0x20DD0, 0x4000
	.global gUnk_087E2878
gUnk_087E2878: @ 0x087E2878
	.incbin "build/assets/gfx__bank_b.bin", 0x24DD0, 0x200
	.global gUnk_087E2A78
gUnk_087E2A78: @ 0x087E2A78
	.incbin "build/assets/gfx__bank_b.bin", 0x24FD0, 0x200
	.global gUnk_087E2C78
gUnk_087E2C78: @ 0x087E2C78
	.incbin "build/assets/gfx__bank_b.bin", 0x251D0, 0x200
	.global gUnk_087E2E78
gUnk_087E2E78: @ 0x087E2E78
	.incbin "build/assets/gfx__bank_b.bin", 0x253D0, 0x200
	.global gUnk_087E3078
gUnk_087E3078: @ 0x087E3078
	.incbin "build/assets/gfx__bank_b.bin", 0x255D0, 0x200
	.global gUnk_087E3278
gUnk_087E3278: @ 0x087E3278
	.incbin "build/assets/gfx__bank_b.bin", 0x257D0, 0x200
	.global gUnk_087E3478
gUnk_087E3478: @ 0x087E3478
	.incbin "build/assets/gfx__bank_b.bin", 0x259D0, 0x140
	.global gUnk_087E35B8
gUnk_087E35B8: @ 0x087E35B8
	.incbin "build/assets/gfx__bank_b.bin", 0x25B10, 0xCC8
	.global gUnk_087E4280
gUnk_087E4280: @ 0x087E4280
	.incbin "build/assets/gfx__bank_b.bin", 0x267D8, 0x1024
	.global gUnk_087E52A4
gUnk_087E52A4: @ 0x087E52A4
	.incbin "build/assets/gfx__bank_b.bin", 0x277FC, 0xA50
	.global gUnk_087E5CF4
gUnk_087E5CF4: @ 0x087E5CF4
	.incbin "build/assets/gfx__bank_b.bin", 0x2824C, 0x1AC0
	.global gUnk_087E77B4
gUnk_087E77B4: @ 0x087E77B4
	.incbin "build/assets/gfx__bank_b.bin", 0x29D0C, 0x2F64
	.global gUnk_087EA718
gUnk_087EA718: @ 0x087EA718
	.incbin "build/assets/gfx__bank_b.bin", 0x2CC70, 0x7080
	.global gUnk_087F1798
gUnk_087F1798: @ 0x087F1798
	.incbin "build/assets/gfx__bank_b.bin", 0x33CF0, 0x2580
	.global gUnk_087F3D18
gUnk_087F3D18: @ 0x087F3D18
	.incbin "build/assets/gfx__bank_b.bin", 0x36270, 0x200
	.global gUnk_087F3F18
gUnk_087F3F18: @ 0x087F3F18
	.incbin "build/assets/gfx__bank_b.bin", 0x36470, 0x200
	.global gUnk_087F4118
gUnk_087F4118: @ 0x087F4118
	.incbin "build/assets/gfx__bank_b.bin", 0x36670, 0xC00
	.global gUnk_087F4D18
gUnk_087F4D18: @ 0x087F4D18
	.incbin "build/assets/gfx__bank_b.bin", 0x37270, 0xC0
	.global gUnk_087F4DD8
gUnk_087F4DD8: @ 0x087F4DD8
	.incbin "build/assets/gfx__bank_b.bin", 0x37330, 0x1000
	.global gUnk_087F5DD8
gUnk_087F5DD8: @ 0x087F5DD8
	.incbin "build/assets/gfx__bank_b.bin", 0x38330, 0x20
	.global gUnk_087F5DF8
gUnk_087F5DF8: @ 0x087F5DF8
	.incbin "build/assets/gfx__bank_b.bin", 0x38350, 0x2000
	.global gUnk_087F7DF8
gUnk_087F7DF8: @ 0x087F7DF8
	.incbin "build/assets/gfx__bank_b.bin", 0x3A350, 0x20
	.global gUnk_087F7E18
gUnk_087F7E18: @ 0x087F7E18
	.incbin "build/assets/gfx__bank_b.bin", 0x3A370, 0x750
@ padding_end (zero)
	.space 0x7A98
