@ Generated by tools/assets.py gen-data from config/assets.tsv. Do not edit.
@ Each asset is built from assets/ into build/assets/ (see tools/assets.py).

	.section .rodata

@ sound/se_table.json (sound_seq_se_table)
	.global gSeTable
gSeTable: @ 0x08087FD0
	.incbin "build/assets/sound__se_table.json.bin", 0x0, 0x540
@ sound/se_tracks (sound_seq_se_tracks)
	.incbin "build/assets/sound__se_tracks.bin", 0x0, 0x510
@ sound/pcm_bank1_table.json (sound_samples_table)
	.global gPcmSampleTable2
gPcmSampleTable2: @ 0x08088A20
	.incbin "build/assets/sound__pcm_bank1_table.json.bin", 0x0, 0x70
@ sound/pcm_bank1_samples (sound_samples_pcm)
	.incbin "build/assets/sound__pcm_bank1_samples.bin", 0x0, 0x57F40
@ sound/song_table.json (sound_seq_song_table)
	.global gSongTable
gSongTable: @ 0x080E09D0
	.incbin "build/assets/sound__song_table.json.bin", 0x0, 0x570
@ sound/song_tracks (sound_seq_song_tracks)
	.incbin "build/assets/sound__song_tracks.bin", 0x0, 0x3A4E0
@ sound/pcm_bank0_table.json (sound_samples_table)
	.global gPcmSampleTable
gPcmSampleTable: @ 0x0811B420
	.incbin "build/assets/sound__pcm_bank0_table.json.bin", 0x0, 0x90
@ sound/pcm_bank0_samples (sound_samples_pcm)
	.incbin "build/assets/sound__pcm_bank0_samples.bin", 0x0, 0x1E0A0
@ sound/wave_ram_patterns.json (sound_samples_waveram)
	.global gWaveRamPatterns
gWaveRamPatterns: @ 0x08139550
	.incbin "build/assets/sound__wave_ram_patterns.json.bin", 0x0, 0xA00
@ sound/noise_table.json (sound_samples_noise)
	.global gNoiseTable
gNoiseTable: @ 0x08139F50
	.incbin "build/assets/sound__noise_table.json.bin", 0x0, 0xC
@ tables/dialogue_box_pointers.json (gfx_scenes_ptrs)
	.global gDialogueBoxGfx
gDialogueBoxGfx: @ 0x08139F5C
	.incbin "build/assets/tables__dialogue_box_pointers.json.bin", 0x0, 0x8
@ text/duelists.json (duelists)
	.global gDuelists
gDuelists: @ 0x08139F64
	.incbin "build/assets/text__duelists.json.bin", 0x0, 0x4
	.global gUnk_08139F68
gUnk_08139F68: @ 0x08139F68
	.incbin "build/assets/text__duelists.json.bin", 0x4, 0xE6C
@ tables/dialogue_box_steps.json (gfx_scenes_ptrs)
	.global gBustupSteps
gBustupSteps: @ 0x0813ADD4
	.incbin "build/assets/tables__dialogue_box_steps.json.bin", 0x0, 0x20
@ text/dialogue.json (dialogue)
	.global gDialogueTable
gDialogueTable: @ 0x0813ADF4
	.incbin "build/assets/text__dialogue.json.bin", 0x0, 0x4
	.global gDialogueTableText
gDialogueTableText: @ 0x0813ADF8
	.incbin "build/assets/text__dialogue.json.bin", 0x4, 0x5C5A4
@ text/dialogue_end.json (tables_game_dialogue_end)
	.incbin "build/assets/text__dialogue_end.json.bin", 0x0, 0x304
@ gfx/scene_sets.json (gfx_scenes_table)
	.global gSceneSets
gSceneSets: @ 0x081976A0
	.incbin "build/assets/gfx__scene_sets.json.bin", 0x0, 0x14
	.global gUnk_081976B4
gUnk_081976B4: @ 0x081976B4
	.incbin "build/assets/gfx__scene_sets.json.bin", 0x14, 0x14
	.global gUnk_081976C8
gUnk_081976C8: @ 0x081976C8
	.incbin "build/assets/gfx__scene_sets.json.bin", 0x28, 0x14
	.global gUnk_081976DC
gUnk_081976DC: @ 0x081976DC
	.incbin "build/assets/gfx__scene_sets.json.bin", 0x3C, 0x14
	.global gUnk_081976F0
gUnk_081976F0: @ 0x081976F0
	.incbin "build/assets/gfx__scene_sets.json.bin", 0x50, 0x14
	.global gUnk_08197704
gUnk_08197704: @ 0x08197704
	.incbin "build/assets/gfx__scene_sets.json.bin", 0x64, 0x14
	.global gUnk_08197718
gUnk_08197718: @ 0x08197718
	.incbin "build/assets/gfx__scene_sets.json.bin", 0x78, 0x14
	.global gUnk_0819772C
gUnk_0819772C: @ 0x0819772C
	.incbin "build/assets/gfx__scene_sets.json.bin", 0x8C, 0x14
	.global gUnk_08197740
gUnk_08197740: @ 0x08197740
	.incbin "build/assets/gfx__scene_sets.json.bin", 0xA0, 0x14
	.global gUnk_08197754
gUnk_08197754: @ 0x08197754
	.incbin "build/assets/gfx__scene_sets.json.bin", 0xB4, 0x14
	.global gUnk_08197768
gUnk_08197768: @ 0x08197768
	.incbin "build/assets/gfx__scene_sets.json.bin", 0xC8, 0x14
	.global gUnk_0819777C
gUnk_0819777C: @ 0x0819777C
	.incbin "build/assets/gfx__scene_sets.json.bin", 0xDC, 0x14
	.global gUnk_08197790
gUnk_08197790: @ 0x08197790
	.incbin "build/assets/gfx__scene_sets.json.bin", 0xF0, 0x14
	.global gUnk_081977A4
gUnk_081977A4: @ 0x081977A4
	.incbin "build/assets/gfx__scene_sets.json.bin", 0x104, 0x14
	.global gUnk_081977B8
gUnk_081977B8: @ 0x081977B8
	.incbin "build/assets/gfx__scene_sets.json.bin", 0x118, 0x14
	.global gUnk_081977CC
gUnk_081977CC: @ 0x081977CC
	.incbin "build/assets/gfx__scene_sets.json.bin", 0x12C, 0x14
	.global gUnk_081977E0
gUnk_081977E0: @ 0x081977E0
	.incbin "build/assets/gfx__scene_sets.json.bin", 0x140, 0x14
	.global gUnk_081977F4
gUnk_081977F4: @ 0x081977F4
	.incbin "build/assets/gfx__scene_sets.json.bin", 0x154, 0x14
	.global gUnk_08197808
gUnk_08197808: @ 0x08197808
	.incbin "build/assets/gfx__scene_sets.json.bin", 0x168, 0x14
	.global gUnk_0819781C
gUnk_0819781C: @ 0x0819781C
	.incbin "build/assets/gfx__scene_sets.json.bin", 0x17C, 0x14
	.global gUnk_08197830
gUnk_08197830: @ 0x08197830
	.incbin "build/assets/gfx__scene_sets.json.bin", 0x190, 0x14
	.global gUnk_08197844
gUnk_08197844: @ 0x08197844
	.incbin "build/assets/gfx__scene_sets.json.bin", 0x1A4, 0x14
	.global gUnk_08197858
gUnk_08197858: @ 0x08197858
	.incbin "build/assets/gfx__scene_sets.json.bin", 0x1B8, 0x14
	.global gUnk_0819786C
gUnk_0819786C: @ 0x0819786C
	.incbin "build/assets/gfx__scene_sets.json.bin", 0x1CC, 0x14
	.global gUnk_08197880
gUnk_08197880: @ 0x08197880
	.incbin "build/assets/gfx__scene_sets.json.bin", 0x1E0, 0x14
	.global gUnk_08197894
gUnk_08197894: @ 0x08197894
	.incbin "build/assets/gfx__scene_sets.json.bin", 0x1F4, 0x14
	.global gUnk_081978A8
gUnk_081978A8: @ 0x081978A8
	.incbin "build/assets/gfx__scene_sets.json.bin", 0x208, 0x14
	.global gUnk_081978BC
gUnk_081978BC: @ 0x081978BC
	.incbin "build/assets/gfx__scene_sets.json.bin", 0x21C, 0x14
	.global gUnk_081978D0
gUnk_081978D0: @ 0x081978D0
	.incbin "build/assets/gfx__scene_sets.json.bin", 0x230, 0x14
	.global gUnk_081978E4
gUnk_081978E4: @ 0x081978E4
	.incbin "build/assets/gfx__scene_sets.json.bin", 0x244, 0x14
	.global gUnk_081978F8
gUnk_081978F8: @ 0x081978F8
	.incbin "build/assets/gfx__scene_sets.json.bin", 0x258, 0x14
@ tables/scene_scripts_and_lists (tables_code_layout)
	.incbin "build/assets/tables__scene_scripts_and_lists.bin", 0x0, 0x7C8
	.global gCalendarEvents
gCalendarEvents: @ 0x081980D4
	.incbin "build/assets/tables__scene_scripts_and_lists.bin", 0x7C8, 0x264
	.global gCalendarSteps
gCalendarSteps: @ 0x08198338
	.incbin "build/assets/tables__scene_scripts_and_lists.bin", 0xA2C, 0x14
	.global gOpponentSelectDuelists
gOpponentSelectDuelists: @ 0x0819834C
	.incbin "build/assets/tables__scene_scripts_and_lists.bin", 0xA40, 0x34
	.global gOpponentSelectSteps
gOpponentSelectSteps: @ 0x08198380
	.incbin "build/assets/tables__scene_scripts_and_lists.bin", 0xA74, 0x2C
	.global gOpponentSelectSlotPos
gOpponentSelectSlotPos: @ 0x081983AC
	.incbin "build/assets/tables__scene_scripts_and_lists.bin", 0xAA0, 0x14
	.global gOpponentCursorWobble
gOpponentCursorWobble: @ 0x081983C0
	.incbin "build/assets/tables__scene_scripts_and_lists.bin", 0xAB4, 0x80
	.global gOpponentSelectPageBgs
gOpponentSelectPageBgs: @ 0x08198440
	.incbin "build/assets/tables__scene_scripts_and_lists.bin", 0xB34, 0x28
	.global gOpponentSelectNames
gOpponentSelectNames: @ 0x08198468
	.incbin "build/assets/tables__scene_scripts_and_lists.bin", 0xB5C, 0x64
	.global gWinLoseDrawLabels
gWinLoseDrawLabels: @ 0x081984CC
	.incbin "build/assets/tables__scene_scripts_and_lists.bin", 0xBC0, 0xC
	.global gMainMenuTable
gMainMenuTable: @ 0x081984D8
	.incbin "build/assets/tables__scene_scripts_and_lists.bin", 0xBCC, 0x1C
	.global gMainMenuSteps
gMainMenuSteps: @ 0x081984F4
	.incbin "build/assets/tables__scene_scripts_and_lists.bin", 0xBE8, 0x14
	.global gRecordScrollHofs
gRecordScrollHofs: @ 0x08198508
	.incbin "build/assets/tables__scene_scripts_and_lists.bin", 0xBFC, 0x80
	.global gRecordSteps
gRecordSteps: @ 0x08198588
	.incbin "build/assets/tables__scene_scripts_and_lists.bin", 0xC7C, 0x18
	.global gRecordPortraitImages
gRecordPortraitImages: @ 0x081985A0
	.incbin "build/assets/tables__scene_scripts_and_lists.bin", 0xC94, 0x64
	.global gRecordPageNameImages
gRecordPageNameImages: @ 0x08198604
	.incbin "build/assets/tables__scene_scripts_and_lists.bin", 0xCF8, 0x14
	.global gRecordMarkerAnimTiles
gRecordMarkerAnimTiles: @ 0x08198618
	.incbin "build/assets/tables__scene_scripts_and_lists.bin", 0xD0C, 0x10
	.global gDaysPerMonth
gDaysPerMonth: @ 0x08198628
	.incbin "build/assets/tables__scene_scripts_and_lists.bin", 0xD1C, 0x11C
	.global gStarterDeckPools
gStarterDeckPools: @ 0x08198744
	.incbin "build/assets/tables__scene_scripts_and_lists.bin", 0xE38, 0x58
	.global gLicenseSteps
gLicenseSteps: @ 0x0819879C
	.incbin "build/assets/tables__scene_scripts_and_lists.bin", 0xE90, 0x94
	.global gTitleLogoWave
gTitleLogoWave: @ 0x08198830
	.incbin "build/assets/tables__scene_scripts_and_lists.bin", 0xF24, 0x80
	.global gTitleSteps
gTitleSteps: @ 0x081988B0
	.incbin "build/assets/tables__scene_scripts_and_lists.bin", 0xFA4, 0x20
	.global gCardTypeNames
gCardTypeNames: @ 0x081988D0
	.incbin "build/assets/tables__scene_scripts_and_lists.bin", 0xFC4, 0x64
	.global gSpellTrapSubtypeSuffixes
gSpellTrapSubtypeSuffixes: @ 0x08198934
	.incbin "build/assets/tables__scene_scripts_and_lists.bin", 0x1028, 0x1C
	.global gCardIconPals
gCardIconPals: @ 0x08198950
	.incbin "build/assets/tables__scene_scripts_and_lists.bin", 0x1044, 0x2C
	.global gCardIconGfx
gCardIconGfx: @ 0x0819897C
	.incbin "build/assets/tables__scene_scripts_and_lists.bin", 0x1070, 0x2C
	.global gAttributeIconImages
gAttributeIconImages: @ 0x081989A8
	.incbin "build/assets/tables__scene_scripts_and_lists.bin", 0x109C, 0x28
	.global gSpellSubtypeIconImages
gSpellSubtypeIconImages: @ 0x081989D0
	.incbin "build/assets/tables__scene_scripts_and_lists.bin", 0x10C4, 0x1C
	.global gMonsterTypeIconImages
gMonsterTypeIconImages: @ 0x081989EC
	.incbin "build/assets/tables__scene_scripts_and_lists.bin", 0x10E0, 0x64
	.global gCardDetailWaveTable
gCardDetailWaveTable: @ 0x08198A50
	.incbin "build/assets/tables__scene_scripts_and_lists.bin", 0x1144, 0x300
	.global gDebugCardDetailSteps
gDebugCardDetailSteps: @ 0x08198D50
	.incbin "build/assets/tables__scene_scripts_and_lists.bin", 0x1444, 0xC
	.global gDebugAutoDetailSteps
gDebugAutoDetailSteps: @ 0x08198D5C
	.incbin "build/assets/tables__scene_scripts_and_lists.bin", 0x1450, 0xC
	.global gDuelResultBanners
gDuelResultBanners: @ 0x08198D68
	.incbin "build/assets/tables__scene_scripts_and_lists.bin", 0x145C, 0x24
	.global gTurnEndHandFrames
gTurnEndHandFrames: @ 0x08198D8C
	.incbin "build/assets/tables__scene_scripts_and_lists.bin", 0x1480, 0x40
	.global gEndOfTurnEffectCards
gEndOfTurnEffectCards: @ 0x08198DCC
	.incbin "build/assets/tables__scene_scripts_and_lists.bin", 0x14C0, 0x18
	.global gChainListHeaders
gChainListHeaders: @ 0x08198DE4
	.incbin "build/assets/tables__scene_scripts_and_lists.bin", 0x14D8, 0x98
	.global gLinkBattleSteps
gLinkBattleSteps: @ 0x08198E7C
	.incbin "build/assets/tables__scene_scripts_and_lists.bin", 0x1570, 0x30
	.global gCampaignSteps
gCampaignSteps: @ 0x08198EAC
	.incbin "build/assets/tables__scene_scripts_and_lists.bin", 0x15A0, 0x30
	.global gAiTurnPhases
gAiTurnPhases: @ 0x08198EDC
	.incbin "build/assets/tables__scene_scripts_and_lists.bin", 0x15D0, 0x1C
	.global gDuelSceneHandlers
gDuelSceneHandlers: @ 0x08198EF8
	.incbin "build/assets/tables__scene_scripts_and_lists.bin", 0x15EC, 0x1C
	.global gDuelSceneRunnerSteps
gDuelSceneRunnerSteps: @ 0x08198F14
	.incbin "build/assets/tables__scene_scripts_and_lists.bin", 0x1608, 0xC
	.global gOpponentDuelBGM
gOpponentDuelBGM: @ 0x08198F20
	.incbin "build/assets/tables__scene_scripts_and_lists.bin", 0x1614, 0x60
	.global gDuelPhaseTable
gDuelPhaseTable: @ 0x08198F80
	.incbin "build/assets/tables__scene_scripts_and_lists.bin", 0x1674, 0x2C
	.global gCoinTossSteps
gCoinTossSteps: @ 0x08198FAC
	.incbin "build/assets/tables__scene_scripts_and_lists.bin", 0x16A0, 0xA40
	.global gDieRollFrames
gDieRollFrames: @ 0x081999EC
	.incbin "build/assets/tables__scene_scripts_and_lists.bin", 0x20E0, 0xC
	.global gSkullDiceCharAnims
gSkullDiceCharAnims: @ 0x081999F8
	.incbin "build/assets/tables__scene_scripts_and_lists.bin", 0x20EC, 0xC
	.global gGracefulDiceCharAnims
gGracefulDiceCharAnims: @ 0x08199A04
	.incbin "build/assets/tables__scene_scripts_and_lists.bin", 0x20F8, 0xC
	.global gDiceScreenSteps
gDiceScreenSteps: @ 0x08199A10
	.incbin "build/assets/tables__scene_scripts_and_lists.bin", 0x2104, 0x18
	.global gPlainDieScreenSteps
gPlainDieScreenSteps: @ 0x08199A28
	.incbin "build/assets/tables__scene_scripts_and_lists.bin", 0x211C, 0x18
	.global gSkullDiceSceneSteps
gSkullDiceSceneSteps: @ 0x08199A40
	.incbin "build/assets/tables__scene_scripts_and_lists.bin", 0x2134, 0x18
	.global gDiceScreenGracefulSteps
gDiceScreenGracefulSteps: @ 0x08199A58
	.incbin "build/assets/tables__scene_scripts_and_lists.bin", 0x214C, 0x18
	.global gDiceScreenPlainSteps
gDiceScreenPlainSteps: @ 0x08199A70
	.incbin "build/assets/tables__scene_scripts_and_lists.bin", 0x2164, 0x258
	.global gExodiaFlameAnimList
gExodiaFlameAnimList: @ 0x08199CC8
	.incbin "build/assets/tables__scene_scripts_and_lists.bin", 0x23BC, 0xAC
	.global gExodiaPieceOamTemplates
gExodiaPieceOamTemplates: @ 0x08199D74
	.incbin "build/assets/tables__scene_scripts_and_lists.bin", 0x2468, 0x28
	.global gExodiaPiecesAnimList
gExodiaPiecesAnimList: @ 0x08199D9C
	.incbin "build/assets/tables__scene_scripts_and_lists.bin", 0x2490, 0x8
	.global gExodiaSceneSteps
gExodiaSceneSteps: @ 0x08199DA4
	.incbin "build/assets/tables__scene_scripts_and_lists.bin", 0x2498, 0x28
	.global gDestinyBoardLayerInit
gDestinyBoardLayerInit: @ 0x08199DCC
	.incbin "build/assets/tables__scene_scripts_and_lists.bin", 0x24C0, 0x30
	.global gDestinyBoardSceneSteps
gDestinyBoardSceneSteps: @ 0x08199DFC
	.incbin "build/assets/tables__scene_scripts_and_lists.bin", 0x24F0, 0x89C
	.global gDestinyBoardAnimList
gDestinyBoardAnimList: @ 0x0819A698
	.incbin "build/assets/tables__scene_scripts_and_lists.bin", 0x2D8C, 0x18
	.global gTurnOrderRpsSubsteps
gTurnOrderRpsSubsteps: @ 0x0819A6B0
	.incbin "build/assets/tables__scene_scripts_and_lists.bin", 0x2DA4, 0x20
	.global gTurnOrderChoiceSubsteps
gTurnOrderChoiceSubsteps: @ 0x0819A6D0
	.incbin "build/assets/tables__scene_scripts_and_lists.bin", 0x2DC4, 0x48
	.global gTurnOrderRpsSteps
gTurnOrderRpsSteps: @ 0x0819A718
	.incbin "build/assets/tables__scene_scripts_and_lists.bin", 0x2E0C, 0x14
	.global gTurnOrderPlayerChoiceSteps
gTurnOrderPlayerChoiceSteps: @ 0x0819A72C
	.incbin "build/assets/tables__scene_scripts_and_lists.bin", 0x2E20, 0x10
	.global gTurnOrderCpuChoiceSteps
gTurnOrderCpuChoiceSteps: @ 0x0819A73C
	.incbin "build/assets/tables__scene_scripts_and_lists.bin", 0x2E30, 0x44
	.global gTurnOrderWaitAnimList
gTurnOrderWaitAnimList: @ 0x0819A780
	.incbin "build/assets/tables__scene_scripts_and_lists.bin", 0x2E74, 0x8
	.global gCardListViewCursorSlide
gCardListViewCursorSlide: @ 0x0819A788
	.incbin "build/assets/tables__scene_scripts_and_lists.bin", 0x2E7C, 0x30
	.global gCardListViewSteps
gCardListViewSteps: @ 0x0819A7B8
	.incbin "build/assets/tables__scene_scripts_and_lists.bin", 0x2EAC, 0x10
	.global gFusionRecipes2
gFusionRecipes2: @ 0x0819A7C8
	.incbin "build/assets/tables__scene_scripts_and_lists.bin", 0x2EBC, 0x1A8
	.global gFusionRecipes3
gFusionRecipes3: @ 0x0819A970
	.incbin "build/assets/tables__scene_scripts_and_lists.bin", 0x3064, 0x20
	.global gRitualRecipes
gRitualRecipes: @ 0x0819A990
	.incbin "build/assets/tables__scene_scripts_and_lists.bin", 0x3084, 0x44
@ tables/card_effect_handlers (tables_code_effects)
	.global gCardEffects
gCardEffects: @ 0x0819A9D4
	.incbin "build/assets/tables__card_effect_handlers.bin", 0x0, 0x27F0
@ tables/pointer_tables (tables_game_layout)
	.global gTributeSummonPrompts
gTributeSummonPrompts: @ 0x0819D1C4
	.incbin "build/assets/tables__pointer_tables.bin", 0x0, 0x14
	.global gBattleStageHandlers
gBattleStageHandlers: @ 0x0819D1D8
	.incbin "build/assets/tables__pointer_tables.bin", 0x14, 0x3C
	.global gMonsterTypeNames
gMonsterTypeNames: @ 0x0819D214
	.incbin "build/assets/tables__pointer_tables.bin", 0x50, 0x50
	.global gAttributeNames
gAttributeNames: @ 0x0819D264
	.incbin "build/assets/tables__pointer_tables.bin", 0xA0, 0x18
	.global gCardJumpArc
gCardJumpArc: @ 0x0819D27C
	.incbin "build/assets/tables__pointer_tables.bin", 0xB8, 0x4
	.global gCardJumpArcDy
gCardJumpArcDy: @ 0x0819D280
	.incbin "build/assets/tables__pointer_tables.bin", 0xBC, 0x7C
	.global gAiPowerCards
gAiPowerCards: @ 0x0819D2FC
	.incbin "build/assets/tables__pointer_tables.bin", 0x138, 0x1A
	.global gAiHandPickPriority
gAiHandPickPriority: @ 0x0819D316
	.incbin "build/assets/tables__pointer_tables.bin", 0x152, 0x36
@ tables/deck_lists.json (tables_game_decks)
	.incbin "build/assets/tables__deck_lists.json.bin", 0x0, 0x920
	.global gOpponentDecks
gOpponentDecks: @ 0x0819DC6C
	.incbin "build/assets/tables__deck_lists.json.bin", 0x920, 0xC8
	.global gOpponentAltDecks
gOpponentAltDecks: @ 0x0819DD34
	.incbin "build/assets/tables__deck_lists.json.bin", 0x9E8, 0x30
@ tables/rodata2 (tables_game_layout)
	.global gAiEffectMonsters
gAiEffectMonsters: @ 0x0819DD64
	.incbin "build/assets/tables__rodata2.bin", 0x0, 0x8
	.global gAiSteps
gAiSteps: @ 0x0819DD6C
	.incbin "build/assets/tables__rodata2.bin", 0x8, 0x28
	.global gBattleSceneOpenBgX
gBattleSceneOpenBgX: @ 0x0819DD94
	.incbin "build/assets/tables__rodata2.bin", 0x30, 0x2800
	.global gBattleSceneOpenBgY
gBattleSceneOpenBgY: @ 0x081A0594
	.incbin "build/assets/tables__rodata2.bin", 0x2830, 0x2800
	.global gBattleSceneOpenBgPA
gBattleSceneOpenBgPA: @ 0x081A2D94
	.incbin "build/assets/tables__rodata2.bin", 0x5030, 0x1400
	.global gBattleSceneShakeRegs
gBattleSceneShakeRegs: @ 0x081A4194
	.incbin "build/assets/tables__rodata2.bin", 0x6430, 0x10
	.global gCardTypeIcons
gCardTypeIcons: @ 0x081A41A4
	.incbin "build/assets/tables__rodata2.bin", 0x6440, 0x54
	.global gCardAttributeIcons
gCardAttributeIcons: @ 0x081A41F8
	.incbin "build/assets/tables__rodata2.bin", 0x6494, 0x1C
	.global gTextBoxColors
gTextBoxColors: @ 0x081A4214
	.incbin "build/assets/tables__rodata2.bin", 0x64B0, 0x28
	.global gAButtonIconFrames
gAButtonIconFrames: @ 0x081A423C
	.incbin "build/assets/tables__rodata2.bin", 0x64D8, 0x40
	.global gZoneMarkerAnimTiles
gZoneMarkerAnimTiles: @ 0x081A427C
	.incbin "build/assets/tables__rodata2.bin", 0x6518, 0x20
	.global gDuelScreenLerpWeights
gDuelScreenLerpWeights: @ 0x081A429C
	.incbin "build/assets/tables__rodata2.bin", 0x6538, 0x8
	.global gDuelZonePositions
gDuelZonePositions: @ 0x081A42A4
	.incbin "build/assets/tables__rodata2.bin", 0x6540, 0x100
	.global gDuelZoneScrollTargets
gDuelZoneScrollTargets: @ 0x081A43A4
	.incbin "build/assets/tables__rodata2.bin", 0x6640, 0x40
	.global gBounceScaleCurve
gBounceScaleCurve: @ 0x081A43E4
	.incbin "build/assets/tables__rodata2.bin", 0x6680, 0x40
	.global gPulseScaleCurve
gPulseScaleCurve: @ 0x081A4424
	.incbin "build/assets/tables__rodata2.bin", 0x66C0, 0x20
	.global gShrinkScaleSteps
gShrinkScaleSteps: @ 0x081A4444
	.incbin "build/assets/tables__rodata2.bin", 0x66E0, 0x10
	.global gDuelAnimLerpWeights
gDuelAnimLerpWeights: @ 0x081A4454
	.incbin "build/assets/tables__rodata2.bin", 0x66F0, 0x20
	.global gCardFlipTiles
gCardFlipTiles: @ 0x081A4474
	.incbin "build/assets/tables__rodata2.bin", 0x6710, 0x60
	.global gCardRotateAngles
gCardRotateAngles: @ 0x081A44D4
	.incbin "build/assets/tables__rodata2.bin", 0x6770, 0x28
	.global gBannerSlideOffsets
gBannerSlideOffsets: @ 0x081A44FC
	.incbin "build/assets/tables__rodata2.bin", 0x6798, 0x20
	.global gPackSceneRasterColors
gPackSceneRasterColors: @ 0x081A451C
	.incbin "build/assets/tables__rodata2.bin", 0x67B8, 0x1110
	.global gPackContents
gPackContents: @ 0x081A562C
	.incbin "build/assets/tables__rodata2.bin", 0x78C8, 0xE0
	.global gPackRarityThresholds
gPackRarityThresholds: @ 0x081A570C
	.incbin "build/assets/tables__rodata2.bin", 0x79A8, 0x20
	.global gGetPackSteps
gGetPackSteps: @ 0x081A572C
	.incbin "build/assets/tables__rodata2.bin", 0x79C8, 0x2C
	.global gUnlockablePackIds
gUnlockablePackIds: @ 0x081A5758
	.incbin "build/assets/tables__rodata2.bin", 0x79F4, 0x9C0
	.global gListFilterAnimScripts
gListFilterAnimScripts: @ 0x081A6118
	.incbin "build/assets/tables__rodata2.bin", 0x83B4, 0x40C
	.global gDeckEditArtFrameSprites
gDeckEditArtFrameSprites: @ 0x081A6524
	.incbin "build/assets/tables__rodata2.bin", 0x87C0, 0x860
	.global gCardMoveSprite
gCardMoveSprite: @ 0x081A6D84
	.incbin "build/assets/tables__rodata2.bin", 0x9020, 0x8
	.global gDeckEditCommandLabelSprites
gDeckEditCommandLabelSprites: @ 0x081A6D8C
	.incbin "build/assets/tables__rodata2.bin", 0x9028, 0x118
	.global gDeckEditPanelCornerSprite
gDeckEditPanelCornerSprite: @ 0x081A6EA4
	.incbin "build/assets/tables__rodata2.bin", 0x9140, 0x8
	.global gDeckEditCommandTabSprite
gDeckEditCommandTabSprite: @ 0x081A6EAC
	.incbin "build/assets/tables__rodata2.bin", 0x9148, 0x8
	.global gDeckEditDigitSprites
gDeckEditDigitSprites: @ 0x081A6EB4
	.incbin "build/assets/tables__rodata2.bin", 0x9150, 0x240
	.global gNameIndexTabSprite
gNameIndexTabSprite: @ 0x081A70F4
	.incbin "build/assets/tables__rodata2.bin", 0x9390, 0x8
	.global gDeckEditAnimScripts
gDeckEditAnimScripts: @ 0x081A70FC
	.incbin "build/assets/tables__rodata2.bin", 0x9398, 0x48
	.global gCardFrameSprites
gCardFrameSprites: @ 0x081A7144
	.incbin "build/assets/tables__rodata2.bin", 0x93E0, 0x18
	.global gListFilterCursorSprites
gListFilterCursorSprites: @ 0x081A715C
	.incbin "build/assets/tables__rodata2.bin", 0x93F8, 0x70
	.global gListFilterFlashSprites
gListFilterFlashSprites: @ 0x081A71CC
	.incbin "build/assets/tables__rodata2.bin", 0x9468, 0x70
	.global gListFilterSteps
gListFilterSteps: @ 0x081A723C
	.incbin "build/assets/tables__rodata2.bin", 0x94D8, 0x10
	.global gDeckStatsSteps
gDeckStatsSteps: @ 0x081A724C
	.incbin "build/assets/tables__rodata2.bin", 0x94E8, 0x10
	.global gDeckEditSteps
gDeckEditSteps: @ 0x081A725C
	.incbin "build/assets/tables__rodata2.bin", 0x94F8, 0x44
	.global gSideDeckSwapSteps
gSideDeckSwapSteps: @ 0x081A72A0
	.incbin "build/assets/tables__rodata2.bin", 0x953C, 0x44
	.global gTradeCardSelectSteps
gTradeCardSelectSteps: @ 0x081A72E4
	.incbin "build/assets/tables__rodata2.bin", 0x9580, 0x4C
	.global gProhibitCardSelectSteps
gProhibitCardSelectSteps: @ 0x081A7330
	.incbin "build/assets/tables__rodata2.bin", 0x95CC, 0x44
	.global gLinkPacketAck
gLinkPacketAck: @ 0x081A7374
	.incbin "build/assets/tables__rodata2.bin", 0x9610, 0xE
	.global gLinkPacketDupAck
gLinkPacketDupAck: @ 0x081A7382
	.incbin "build/assets/tables__rodata2.bin", 0x961E, 0xE
	.global gLinkPacketResend
gLinkPacketResend: @ 0x081A7390
	.incbin "build/assets/tables__rodata2.bin", 0x962C, 0x10
	.global gDebugMenuItems
gDebugMenuItems: @ 0x081A73A0
	.incbin "build/assets/tables__rodata2.bin", 0x963C, 0x2EC
	.global gDebugMenuSteps
gDebugMenuSteps: @ 0x081A768C
	.incbin "build/assets/tables__rodata2.bin", 0x9928, 0x14
	.global gAsciiToSjisTable
gAsciiToSjisTable: @ 0x081A76A0
	.incbin "build/assets/tables__rodata2.bin", 0x993C, 0xC0
	.global gMapFillTile
gMapFillTile: @ 0x081A7760
	.incbin "build/assets/tables__rodata2.bin", 0x99FC, 0x4
	.global gBgHofsRegs
gBgHofsRegs: @ 0x081A7764
	.incbin "build/assets/tables__rodata2.bin", 0x9A00, 0x20
	.global gBgVofsRegs
gBgVofsRegs: @ 0x081A7784
	.incbin "build/assets/tables__rodata2.bin", 0x9A20, 0x24
	.global gSineTable128
gSineTable128: @ 0x081A77A8
	.incbin "build/assets/tables__rodata2.bin", 0x9A44, 0x100
	.global gSaveSignature
gSaveSignature: @ 0x081A78A8
	.incbin "build/assets/tables__rodata2.bin", 0x9B44, 0xC
	.global gCardCopyLimits
gCardCopyLimits: @ 0x081A78B4
	.incbin "build/assets/tables__rodata2.bin", 0x9B50, 0xBC
	.global gPasswordSteps
gPasswordSteps: @ 0x081A7970
	.incbin "build/assets/tables__rodata2.bin", 0x9C0C, 0x34
	.global gCardTradingSteps
gCardTradingSteps: @ 0x081A79A4
	.incbin "build/assets/tables__rodata2.bin", 0x9C40, 0x44
	.global gSeTrackPcmChannel
gSeTrackPcmChannel: @ 0x081A79E8
	.incbin "build/assets/tables__rodata2.bin", 0x9C84, 0x11
	.global gSeVariantTrackMap
gSeVariantTrackMap: @ 0x081A79F9
	.incbin "build/assets/tables__rodata2.bin", 0x9C95, 0x13
@ sound/lookup_tables.json (sound_seq_lookup)
	.incbin "build/assets/sound__lookup_tables.json.bin", 0x0, 0x1C00
	.global gSoundPitchTable
gSoundPitchTable: @ 0x081A960C
	.incbin "build/assets/sound__lookup_tables.json.bin", 0x1C00, 0xC00
	.global gPsgFreqTable
gPsgFreqTable: @ 0x081AA20C
	.incbin "build/assets/sound__lookup_tables.json.bin", 0x2800, 0x1A40
@ tables/sine.json (tables_game_sine)
	.global gVibratoSineTable
gVibratoSineTable: @ 0x081ABC4C
	.incbin "build/assets/tables__sine.json.bin", 0x0, 0x200
@ padding_081ABE4C (zero)
	.space 0x141B4
@ fonts/kanji_8x8.png (font1bpp)
	.global gFontKanji8x8
gFontKanji8x8: @ 0x081C0000
	.incbin "build/assets/fonts__kanji_8x8.png.bin", 0x0, 0x10200
@ fonts/kanji_10x10.png (font1bpp)
	.global gFontKanji10x10
gFontKanji10x10: @ 0x081D0200
	.incbin "build/assets/fonts__kanji_10x10.png.bin", 0x0, 0x28500
@ fonts/kanji_12x12.png (font1bpp)
	.global gFontKanji12x12
gFontKanji12x12: @ 0x081F8700
	.incbin "build/assets/fonts__kanji_12x12.png.bin", 0x0, 0x30600
@ fonts/latin_8x8.png (font1bpp)
	.global gFontLatin8x8
gFontLatin8x8: @ 0x08228D00
	.incbin "build/assets/fonts__latin_8x8.png.bin", 0x0, 0x800
@ fonts/latin_8x10.png (font1bpp)
	.global gFontLatin8x10
gFontLatin8x10: @ 0x08229500
	.incbin "build/assets/fonts__latin_8x10.png.bin", 0x0, 0xA00
@ fonts/latin_8x12.png (font1bpp)
	.global gFontLatin8x12
gFontLatin8x12: @ 0x08229F00
	.incbin "build/assets/fonts__latin_8x12.png.bin", 0x0, 0xC00
@ fonts/latin_8x16.png (font1bpp)
	.global gFontLatin8x16
gFontLatin8x16: @ 0x0822AB00
	.incbin "build/assets/fonts__latin_8x16.png.bin", 0x0, 0x1000
@ fonts/latin_8x8_bold.png (font1bpp)
	.global gFontLatin8x8Bold
gFontLatin8x8Bold: @ 0x0822BB00
	.incbin "build/assets/fonts__latin_8x8_bold.png.bin", 0x0, 0x800
@ gfx/system.pal (palette)
	.global gSystemFontPal
gSystemFontPal: @ 0x0822C300
	.incbin "build/assets/gfx__system.pal.bin", 0x0, 0x20
@ gfx/system_tiles.png (tiles4bpp)
	.global gSystemTiles
gSystemTiles: @ 0x0822C320
	.incbin "build/assets/gfx__system_tiles.png.bin", 0x0, 0x40
	.global gUnk_0822C360
gUnk_0822C360: @ 0x0822C360
	.incbin "build/assets/gfx__system_tiles.png.bin", 0x40, 0x3C0
@ cards/names.json (strings)
	.global gCardNames
gCardNames: @ 0x0822C720
	.incbin "build/assets/cards__names.json.bin", 0x0, 0xCD40
@ cards/unused_name_bank (zero)
	.space 0xCD40
@ cards/descriptions.json (strings)
	.global gCardDescriptions
gCardDescriptions: @ 0x082461A0
	.incbin "build/assets/cards__descriptions.json.bin", 0x0, 0x60360
@ cards/art (card_art)
	.global gCardArtGfx
gCardArtGfx: @ 0x082A6500
	.incbin "build/assets/cards__art.bin", 0x0, 0x361E60
	.global gCardArtPalettes
gCardArtPalettes: @ 0x08608360
	.incbin "build/assets/cards__art.bin", 0x361E60, 0x19A80
@ cards/stats.csv (card_stats)
	.global gCardStats
gCardStats: @ 0x08621DE0
	.incbin "build/assets/cards__stats.csv.bin", 0x0, 0xCD4
@ cards/id_to_number.json (u16)
	.global gCardIdToNumber
gCardIdToNumber: @ 0x08622AB4
	.incbin "build/assets/cards__id_to_number.json.bin", 0x0, 0x66A
	.global gCardIdToNumber_821
gCardIdToNumber_821: @ 0x0862311E
	.incbin "build/assets/cards__id_to_number.json.bin", 0x66A, 0x2
@ cards/passwords.csv (tables_game_passwords)
	.global gCardPasswords
gCardPasswords: @ 0x08623120
	.incbin "build/assets/cards__passwords.csv.bin", 0x0, 0x206
	.global gCardIdToNumber_1081
gCardIdToNumber_1081: @ 0x08623326
	.incbin "build/assets/cards__passwords.csv.bin", 0x206, 0xACE
@ cards/number_to_id.json (u16)
	.global gCardNumberToId
gCardNumberToId: @ 0x08623DF4
	.incbin "build/assets/cards__number_to_id.json.bin", 0x0, 0x1C
	.global gCardNumberToId_FlameSwordsman
gCardNumberToId_FlameSwordsman: @ 0x08623E10
	.incbin "build/assets/cards__number_to_id.json.bin", 0x1C, 0xE
	.global gCardNumberToId_SummonedSkull
gCardNumberToId_SummonedSkull: @ 0x08623E1E
	.incbin "build/assets/cards__number_to_id.json.bin", 0x2A, 0x1A
	.global gCardNumberToId_DarkMagician
gCardNumberToId_DarkMagician: @ 0x08623E38
	.incbin "build/assets/cards__number_to_id.json.bin", 0x44, 0x6
	.global gCardNumberToId_GaiaTheFierceKnight
gCardNumberToId_GaiaTheFierceKnight: @ 0x08623E3E
	.incbin "build/assets/cards__number_to_id.json.bin", 0x4A, 0x6
	.global gCardNumberToId_CelticGuardian
gCardNumberToId_CelticGuardian: @ 0x08623E44
	.incbin "build/assets/cards__number_to_id.json.bin", 0x50, 0x22
	.global gCardNumberToId_Kuriboh
gCardNumberToId_Kuriboh: @ 0x08623E66
	.incbin "build/assets/cards__number_to_id.json.bin", 0x72, 0x8
	.global gCardNumberToId_HarpieLady
gCardNumberToId_HarpieLady: @ 0x08623E6E
	.incbin "build/assets/cards__number_to_id.json.bin", 0x7A, 0x4
	.global gCardNumberToId_TigerAxe
gCardNumberToId_TigerAxe: @ 0x08623E72
	.incbin "build/assets/cards__number_to_id.json.bin", 0x7E, 0xA
	.global gCardNumberToId_ThousandDragon
gCardNumberToId_ThousandDragon: @ 0x08623E7C
	.incbin "build/assets/cards__number_to_id.json.bin", 0x88, 0xC2
	.global gCardNumberToId_MysteriousPuppeteer
gCardNumberToId_MysteriousPuppeteer: @ 0x08623F3E
	.incbin "build/assets/cards__number_to_id.json.bin", 0x14A, 0xE0
	.global gCardNumberToId_PetitMoth
gCardNumberToId_PetitMoth: @ 0x0862401E
	.incbin "build/assets/cards__number_to_id.json.bin", 0x22A, 0x34
	.global gCardNumberToId_AxeOfDespair
gCardNumberToId_AxeOfDespair: @ 0x08624052
	.incbin "build/assets/cards__number_to_id.json.bin", 0x25E, 0x32
	.global gCardNumberToId_DragonCaptureJar
gCardNumberToId_DragonCaptureJar: @ 0x08624084
	.incbin "build/assets/cards__number_to_id.json.bin", 0x290, 0x4A
	.global gCardNumberToId_LabyrinthWall
gCardNumberToId_LabyrinthWall: @ 0x086240CE
	.incbin "build/assets/cards__number_to_id.json.bin", 0x2DA, 0x2C
	.global gCardNumberToId_PendulumMachine
gCardNumberToId_PendulumMachine: @ 0x086240FA
	.incbin "build/assets/cards__number_to_id.json.bin", 0x306, 0x4
	.global gCardNumberToId_LauncherSpider
gCardNumberToId_LauncherSpider: @ 0x086240FE
	.incbin "build/assets/cards__number_to_id.json.bin", 0x30A, 0xAA
	.global gCardNumberToId_SinisterSerpent
gCardNumberToId_SinisterSerpent: @ 0x086241A8
	.incbin "build/assets/cards__number_to_id.json.bin", 0x3B4, 0x9C
	.global gCardNumberToId_MushroomMan2
gCardNumberToId_MushroomMan2: @ 0x08624244
	.incbin "build/assets/cards__number_to_id.json.bin", 0x450, 0xD8
	.global gUnk_0862431C
gUnk_0862431C: @ 0x0862431C
	.incbin "build/assets/cards__number_to_id.json.bin", 0x528, 0xAC
	.global gCardNumberToId_GazelleTheKingOfMythicalBeasts
gCardNumberToId_GazelleTheKingOfMythicalBeasts: @ 0x086243C8
	.incbin "build/assets/cards__number_to_id.json.bin", 0x5D4, 0x20
	.global gCardNumberToId_ParasiteParacide
gCardNumberToId_ParasiteParacide: @ 0x086243E8
	.incbin "build/assets/cards__number_to_id.json.bin", 0x5F4, 0xA6
	.global gCardNumberToId_ValkyrionTheMagnaWarrior
gCardNumberToId_ValkyrionTheMagnaWarrior: @ 0x0862448E
	.incbin "build/assets/cards__number_to_id.json.bin", 0x69A, 0xDA
	.global gCardNumberToId_ToonWorld
gCardNumberToId_ToonWorld: @ 0x08624568
	.incbin "build/assets/cards__number_to_id.json.bin", 0x774, 0x14
	.global gCardNumberToId_LightforceSword
gCardNumberToId_LightforceSword: @ 0x0862457C
	.incbin "build/assets/cards__number_to_id.json.bin", 0x788, 0x4E
	.global gCardNumberToId_Polymerization
gCardNumberToId_Polymerization: @ 0x086245CA
	.incbin "build/assets/cards__number_to_id.json.bin", 0x7D6, 0xA
	.global gUnk_086245D4
gUnk_086245D4: @ 0x086245D4
	.incbin "build/assets/cards__number_to_id.json.bin", 0x7E0, 0xA6
	.global gCardNumberToId_Graverobber
gCardNumberToId_Graverobber: @ 0x0862467A
	.incbin "build/assets/cards__number_to_id.json.bin", 0x886, 0x42
	.global gCardNumberToId_Kotodama
gCardNumberToId_Kotodama: @ 0x086246BC
	.incbin "build/assets/cards__number_to_id.json.bin", 0x8C8, 0x48
	.global gUnk_08624704
gUnk_08624704: @ 0x08624704
	.incbin "build/assets/cards__number_to_id.json.bin", 0x910, 0x2C
	.global gCardNumberToId_SwordOfDragonsSoul
gCardNumberToId_SwordOfDragonsSoul: @ 0x08624730
	.incbin "build/assets/cards__number_to_id.json.bin", 0x93C, 0x28
	.global gCardNumberToId_DarkSage
gCardNumberToId_DarkSage: @ 0x08624758
	.incbin "build/assets/cards__number_to_id.json.bin", 0x964, 0x10
	.global gCardNumberToId_1210
gCardNumberToId_1210: @ 0x08624768
	.incbin "build/assets/cards__number_to_id.json.bin", 0x974, 0x42
	.global gCardNumberToId_1243
gCardNumberToId_1243: @ 0x086247AA
	.incbin "build/assets/cards__number_to_id.json.bin", 0x9B6, 0xC
	.global gCardNumberToId_1249
gCardNumberToId_1249: @ 0x086247B6
	.incbin "build/assets/cards__number_to_id.json.bin", 0x9C2, 0x12
	.global gCardNumberToId_1258
gCardNumberToId_1258: @ 0x086247C8
	.incbin "build/assets/cards__number_to_id.json.bin", 0x9D4, 0x7A
	.global gUnk_08624842
gUnk_08624842: @ 0x08624842
	.incbin "build/assets/cards__number_to_id.json.bin", 0xA4E, 0x6
	.global gCardNumberToId_1322
gCardNumberToId_1322: @ 0x08624848
	.incbin "build/assets/cards__number_to_id.json.bin", 0xA54, 0x24
	.global gCardNumberToId_1340
gCardNumberToId_1340: @ 0x0862486C
	.incbin "build/assets/cards__number_to_id.json.bin", 0xA78, 0x82
	.global gCardNumberToId_1405
gCardNumberToId_1405: @ 0x086248EE
	.incbin "build/assets/cards__number_to_id.json.bin", 0xAFA, 0xDA
	.global gCardNumberToId_1514
gCardNumberToId_1514: @ 0x086249C8
	.incbin "build/assets/cards__number_to_id.json.bin", 0xBD4, 0xC
	.global gCardNumberToId_1520
gCardNumberToId_1520: @ 0x086249D4
	.incbin "build/assets/cards__number_to_id.json.bin", 0xBE0, 0x1A
	.global gCardNumberToId_1533
gCardNumberToId_1533: @ 0x086249EE
	.incbin "build/assets/cards__number_to_id.json.bin", 0xBFA, 0x6
	.global gCardNumberToId_1536
gCardNumberToId_1536: @ 0x086249F4
	.incbin "build/assets/cards__number_to_id.json.bin", 0xC00, 0x4
	.global gCardNumberToId_1538
gCardNumberToId_1538: @ 0x086249F8
	.incbin "build/assets/cards__number_to_id.json.bin", 0xC04, 0x12
	.global gCardNumberToId_1547
gCardNumberToId_1547: @ 0x08624A0A
	.incbin "build/assets/cards__number_to_id.json.bin", 0xC16, 0x2
	.global gCardNumberToId_1548
gCardNumberToId_1548: @ 0x08624A0C
	.incbin "build/assets/cards__number_to_id.json.bin", 0xC18, 0x2C2
	.global gCardNumberToId_TheMonarchy
gCardNumberToId_TheMonarchy: @ 0x08624CCE
	.incbin "build/assets/cards__number_to_id.json.bin", 0xEDA, 0x2
	.global gCardNumberToId_SetSailForTheKingdom
gCardNumberToId_SetSailForTheKingdom: @ 0x08624CD0
	.incbin "build/assets/cards__number_to_id.json.bin", 0xEDC, 0x2
	.global gCardNumberToId_GloryOfTheKingsHand
gCardNumberToId_GloryOfTheKingsHand: @ 0x08624CD2
	.incbin "build/assets/cards__number_to_id.json.bin", 0xEDE, 0x22
	.global gCardNumberToId_InsectMonsterToken
gCardNumberToId_InsectMonsterToken: @ 0x08624CF4
	.incbin "build/assets/cards__number_to_id.json.bin", 0xF00, 0x100
@ cards/sort_keys.json (u16)
	.incbin "build/assets/cards__sort_keys.json.bin", 0x0, 0x66C
@ gfx/card_frames (gfx_banks_bank)
	.global gCardFrameNormalGfx
gCardFrameNormalGfx: @ 0x08625460
	.incbin "build/assets/gfx__card_frames.bin", 0x0, 0x2698
	.global gCardFrameEffectGfx
gCardFrameEffectGfx: @ 0x08627AF8
	.incbin "build/assets/gfx__card_frames.bin", 0x2698, 0x2698
	.global gCardFrameFusionGfx
gCardFrameFusionGfx: @ 0x0862A190
	.incbin "build/assets/gfx__card_frames.bin", 0x4D30, 0x2698
	.global gCardFrameRitualGfx
gCardFrameRitualGfx: @ 0x0862C828
	.incbin "build/assets/gfx__card_frames.bin", 0x73C8, 0x2698
	.global gCardFrameMagicGfx
gCardFrameMagicGfx: @ 0x0862EEC0
	.incbin "build/assets/gfx__card_frames.bin", 0x9A60, 0x2698
	.global gCardFrameTrapGfx
gCardFrameTrapGfx: @ 0x08631558
	.incbin "build/assets/gfx__card_frames.bin", 0xC0F8, 0x2698
	.global gCardFrameTicketGfx
gCardFrameTicketGfx: @ 0x08633BF0
	.incbin "build/assets/gfx__card_frames.bin", 0xE790, 0x2698
@ gfx/bank_a (gfx_banks_bank)
	.incbin "build/assets/gfx__bank_a.bin", 0x0, 0xC0
	.global gTrapIconPal
gTrapIconPal: @ 0x08636348
	.incbin "build/assets/gfx__bank_a.bin", 0xC0, 0x20
	.global gMagicIconPal
gMagicIconPal: @ 0x08636368
	.incbin "build/assets/gfx__bank_a.bin", 0xE0, 0x20
	.global gDivineIconPal
gDivineIconPal: @ 0x08636388
	.incbin "build/assets/gfx__bank_a.bin", 0x100, 0x320
	.global gTrapIconGfx
gTrapIconGfx: @ 0x086366A8
	.incbin "build/assets/gfx__bank_a.bin", 0x420, 0x80
	.global gMagicIconGfx
gMagicIconGfx: @ 0x08636728
	.incbin "build/assets/gfx__bank_a.bin", 0x4A0, 0x80
	.global gDivineIconGfx
gDivineIconGfx: @ 0x086367A8
	.incbin "build/assets/gfx__bank_a.bin", 0x520, 0x530
	.global gTrapBadgeImage
gTrapBadgeImage: @ 0x08636CD8
	.incbin "build/assets/gfx__bank_a.bin", 0xA50, 0xC8
	.global gMagicBadgeImage
gMagicBadgeImage: @ 0x08636DA0
	.incbin "build/assets/gfx__bank_a.bin", 0xB18, 0x5D4
	.global gSpellTrapSubtypeIconGfx
gSpellTrapSubtypeIconGfx: @ 0x08637374
	.incbin "build/assets/gfx__bank_a.bin", 0x10EC, 0x20
	.global gSpellTrapSubtypeIconGfx_1
gSpellTrapSubtypeIconGfx_1: @ 0x08637394
	.incbin "build/assets/gfx__bank_a.bin", 0x110C, 0xC0
	.global gSpellTrapSubtypeIconPal
gSpellTrapSubtypeIconPal: @ 0x08637454
	.incbin "build/assets/gfx__bank_a.bin", 0x11CC, 0xFB8
	.global gCardStatDigitsPal
gCardStatDigitsPal: @ 0x0863840C
	.incbin "build/assets/gfx__bank_a.bin", 0x2184, 0x20
	.global gCardStatDigitsGfx
gCardStatDigitsGfx: @ 0x0863842C
	.incbin "build/assets/gfx__bank_a.bin", 0x21A4, 0x140
	.global gCardStatLabelGfx
gCardStatLabelGfx: @ 0x0863856C
	.incbin "build/assets/gfx__bank_a.bin", 0x22E4, 0x20
	.global gUnk_0863858C
gUnk_0863858C: @ 0x0863858C
	.incbin "build/assets/gfx__bank_a.bin", 0x2304, 0x20
	.global gUnk_086385AC
gUnk_086385AC: @ 0x086385AC
	.incbin "build/assets/gfx__bank_a.bin", 0x2324, 0x20
	.global gUnk_086385CC
gUnk_086385CC: @ 0x086385CC
	.incbin "build/assets/gfx__bank_a.bin", 0x2344, 0x60
	.global gPasswordKeypadBgGfx
gPasswordKeypadBgGfx: @ 0x0863862C
	.incbin "build/assets/gfx__bank_a.bin", 0x23A4, 0x1130
	.global gPasswordPanelBgGfx
gPasswordPanelBgGfx: @ 0x0863975C
	.incbin "build/assets/gfx__bank_a.bin", 0x34D4, 0x6A0
	.global gPasswordObjPal
gPasswordObjPal: @ 0x08639DFC
	.incbin "build/assets/gfx__bank_a.bin", 0x3B74, 0x20
	.global gPasswordObjGfx
gPasswordObjGfx: @ 0x08639E1C
	.incbin "build/assets/gfx__bank_a.bin", 0x3B94, 0x2C00
	.global gAtkDefIconImage
gAtkDefIconImage: @ 0x0863CA1C
	.incbin "build/assets/gfx__bank_a.bin", 0x6794, 0x80
	.global gPackSceneBgPal
gPackSceneBgPal: @ 0x0863CA9C
	.incbin "build/assets/gfx__bank_a.bin", 0x6814, 0x20
	.global gPackSceneBgTiles
gPackSceneBgTiles: @ 0x0863CABC
	.incbin "build/assets/gfx__bank_a.bin", 0x6834, 0x80
	.global gPackCursorFramePal
gPackCursorFramePal: @ 0x0863CB3C
	.incbin "build/assets/gfx__bank_a.bin", 0x68B4, 0x20
	.global gPackCursorFrameTiles
gPackCursorFrameTiles: @ 0x0863CB5C
	.incbin "build/assets/gfx__bank_a.bin", 0x68D4, 0x120
	.global gPackListPal
gPackListPal: @ 0x0863CC7C
	.incbin "build/assets/gfx__bank_a.bin", 0x69F4, 0x200
	.global gPackListBgTiles
gPackListBgTiles: @ 0x0863CE7C
	.incbin "build/assets/gfx__bank_a.bin", 0x6BF4, 0x40
	.global gUnk_0863CEBC
gUnk_0863CEBC: @ 0x0863CEBC
	.incbin "build/assets/gfx__bank_a.bin", 0x6C34, 0x40
	.global gUnk_0863CEFC
gUnk_0863CEFC: @ 0x0863CEFC
	.incbin "build/assets/gfx__bank_a.bin", 0x6C74, 0x40
	.global gStarterDeckBgImage
gStarterDeckBgImage: @ 0x0863CF3C
	.incbin "build/assets/gfx__bank_a.bin", 0x6CB4, 0x1F0
	.global gStarterDeckBoxBlackImage
gStarterDeckBoxBlackImage: @ 0x0863D12C
	.incbin "build/assets/gfx__bank_a.bin", 0x6EA4, 0x1270
	.global gStarterDeckBoxRedImage
gStarterDeckBoxRedImage: @ 0x0863E39C
	.incbin "build/assets/gfx__bank_a.bin", 0x8114, 0x11B0
	.global gStarterDeckBoxGreenImage
gStarterDeckBoxGreenImage: @ 0x0863F54C
	.incbin "build/assets/gfx__bank_a.bin", 0x92C4, 0x383F0
	.global gHandCursorPal
gHandCursorPal: @ 0x0867793C
	.incbin "build/assets/gfx__bank_a.bin", 0x416B4, 0x20
	.global gCardIconPal
gCardIconPal: @ 0x0867795C
	.incbin "build/assets/gfx__bank_a.bin", 0x416D4, 0x20
	.global gHandCursorGfx
gHandCursorGfx: @ 0x0867797C
	.incbin "build/assets/gfx__bank_a.bin", 0x416F4, 0x800
	.global gCardIconBackGfx
gCardIconBackGfx: @ 0x0867817C
	.incbin "build/assets/gfx__bank_a.bin", 0x41EF4, 0x800
	.global gCardIconNormalGfx
gCardIconNormalGfx: @ 0x0867897C
	.incbin "build/assets/gfx__bank_a.bin", 0x426F4, 0x800
	.global gCardIconEffectGfx
gCardIconEffectGfx: @ 0x0867917C
	.incbin "build/assets/gfx__bank_a.bin", 0x42EF4, 0x800
	.global gCardIconFusionGfx
gCardIconFusionGfx: @ 0x0867997C
	.incbin "build/assets/gfx__bank_a.bin", 0x436F4, 0x800
	.global gCardIconRitualGfx
gCardIconRitualGfx: @ 0x0867A17C
	.incbin "build/assets/gfx__bank_a.bin", 0x43EF4, 0x800
	.global gCardIconTrapGfx
gCardIconTrapGfx: @ 0x0867A97C
	.incbin "build/assets/gfx__bank_a.bin", 0x446F4, 0x800
	.global gCardIconMagicGfx
gCardIconMagicGfx: @ 0x0867B17C
	.incbin "build/assets/gfx__bank_a.bin", 0x44EF4, 0x800
	.global gThickPileGfx
gThickPileGfx: @ 0x0867B97C
	.incbin "build/assets/gfx__bank_a.bin", 0x456F4, 0x200
	.global gDuelFieldImage
gDuelFieldImage: @ 0x0867BB7C
	.incbin "build/assets/gfx__bank_a.bin", 0x458F4, 0x2450
	.global gTitleGridImage
gTitleGridImage: @ 0x0867DFCC
	.incbin "build/assets/gfx__bank_a.bin", 0x47D44, 0x4F0
	.global gDuelDigitsPal
gDuelDigitsPal: @ 0x0867E4BC
	.incbin "build/assets/gfx__bank_a.bin", 0x48234, 0x200
	.global gDuelDigitsGfx
gDuelDigitsGfx: @ 0x0867E6BC
	.incbin "build/assets/gfx__bank_a.bin", 0x48434, 0x780
	.global gPhaseIndicatorPal
gPhaseIndicatorPal: @ 0x0867EE3C
	.incbin "build/assets/gfx__bank_a.bin", 0x48BB4, 0x20
	.global gLpLabelGfx
gLpLabelGfx: @ 0x0867EE5C
	.incbin "build/assets/gfx__bank_a.bin", 0x48BD4, 0x40
	.global gPhaseIndicatorGfx
gPhaseIndicatorGfx: @ 0x0867EE9C
	.incbin "build/assets/gfx__bank_a.bin", 0x48C14, 0x180
	.global gPhaseBannerPal
gPhaseBannerPal: @ 0x0867F01C
	.incbin "build/assets/gfx__bank_a.bin", 0x48D94, 0x20
	.global gPhaseBannerGfx
gPhaseBannerGfx: @ 0x0867F03C
	.incbin "build/assets/gfx__bank_a.bin", 0x48DB4, 0x600
	.global gBattlePhaseBannerGfx
gBattlePhaseBannerGfx: @ 0x0867F63C
	.incbin "build/assets/gfx__bank_a.bin", 0x493B4, 0x600
	.global gCardMenuIconsPal
gCardMenuIconsPal: @ 0x0867FC3C
	.incbin "build/assets/gfx__bank_a.bin", 0x499B4, 0x20
	.global gCardMenuIconsGfx
gCardMenuIconsGfx: @ 0x0867FC5C
	.incbin "build/assets/gfx__bank_a.bin", 0x499D4, 0x800
	.global gCardMenuLabelsPal
gCardMenuLabelsPal: @ 0x0868045C
	.incbin "build/assets/gfx__bank_a.bin", 0x4A1D4, 0x20
	.global gCardMenuLabelsGfx
gCardMenuLabelsGfx: @ 0x0868047C
	.incbin "build/assets/gfx__bank_a.bin", 0x4A1F4, 0x1000
	.global gTextBoxPal
gTextBoxPal: @ 0x0868147C
	.incbin "build/assets/gfx__bank_a.bin", 0x4B1F4, 0x20
	.global gTextBoxFrameGfx
gTextBoxFrameGfx: @ 0x0868149C
	.incbin "build/assets/gfx__bank_a.bin", 0x4B214, 0x1E0
	.global gButtonIconsPal
gButtonIconsPal: @ 0x0868167C
	.incbin "build/assets/gfx__bank_a.bin", 0x4B3F4, 0x200
	.global gButtonIconsGfx
gButtonIconsGfx: @ 0x0868187C
	.incbin "build/assets/gfx__bank_a.bin", 0x4B5F4, 0x500
	.global gDuelUiIconsGfx
gDuelUiIconsGfx: @ 0x08681D7C
	.incbin "build/assets/gfx__bank_a.bin", 0x4BAF4, 0x100
	.global gYesNoLabelsGfx
gYesNoLabelsGfx: @ 0x08681E7C
	.incbin "build/assets/gfx__bank_a.bin", 0x4BBF4, 0x600
	.global gLpDigitsPal
gLpDigitsPal: @ 0x0868247C
	.incbin "build/assets/gfx__bank_a.bin", 0x4C1F4, 0x200
	.global gLpDigitsGfx
gLpDigitsGfx: @ 0x0868267C
	.incbin "build/assets/gfx__bank_a.bin", 0x4C3F4, 0x2000
	.global gZoneMarkerPal
gZoneMarkerPal: @ 0x0868467C
	.incbin "build/assets/gfx__bank_a.bin", 0x4E3F4, 0x200
	.global gZoneMarkerCanAttackGfx
gZoneMarkerCanAttackGfx: @ 0x0868487C
	.incbin "build/assets/gfx__bank_a.bin", 0x4E5F4, 0x180
	.global gZoneMarkerLinkEquipGfx
gZoneMarkerLinkEquipGfx: @ 0x086849FC
	.incbin "build/assets/gfx__bank_a.bin", 0x4E774, 0x180
	.global gZoneMarkerLinkOtherGfx
gZoneMarkerLinkOtherGfx: @ 0x08684B7C
	.incbin "build/assets/gfx__bank_a.bin", 0x4E8F4, 0x380
	.global gHeldZoneMarkGfx
gHeldZoneMarkGfx: @ 0x08684EFC
	.incbin "build/assets/gfx__bank_a.bin", 0x4EC74, 0x680
	.global gLinkWaitIndicatorPal
gLinkWaitIndicatorPal: @ 0x0868557C
	.incbin "build/assets/gfx__bank_a.bin", 0x4F2F4, 0x20
	.global gLinkWaitIndicatorGfx
gLinkWaitIndicatorGfx: @ 0x0868559C
	.incbin "build/assets/gfx__bank_a.bin", 0x4F314, 0x2600
	.global gDuelBannerPal
gDuelBannerPal: @ 0x08687B9C
	.incbin "build/assets/gfx__bank_a.bin", 0x51914, 0x20
	.global gStartDuelBannerGfx
gStartDuelBannerGfx: @ 0x08687BBC
	.incbin "build/assets/gfx__bank_a.bin", 0x51934, 0x400
	.global gAttackBannerGfx
gAttackBannerGfx: @ 0x08687FBC
	.incbin "build/assets/gfx__bank_a.bin", 0x51D34, 0x400
	.global gDirectAttackBannerGfx
gDirectAttackBannerGfx: @ 0x086883BC
	.incbin "build/assets/gfx__bank_a.bin", 0x52134, 0x400
	.global gSurrenderBannerGfx
gSurrenderBannerGfx: @ 0x086887BC
	.incbin "build/assets/gfx__bank_a.bin", 0x52534, 0x400
	.global gJustAMomentBannerGfx
gJustAMomentBannerGfx: @ 0x08688BBC
	.incbin "build/assets/gfx__bank_a.bin", 0x52934, 0x400
	.global gChainBannerPal
gChainBannerPal: @ 0x08688FBC
	.incbin "build/assets/gfx__bank_a.bin", 0x52D34, 0x1C
	.global gChainBannerGfx
gChainBannerGfx: @ 0x08688FD8
	.incbin "build/assets/gfx__bank_a.bin", 0x52D50, 0x400
	.global gLinkConnectingImage
gLinkConnectingImage: @ 0x086893D8
	.incbin "build/assets/gfx__bank_a.bin", 0x53150, 0x36E8
	.global gExplosionAnim
gExplosionAnim: @ 0x0868CAC0
	.incbin "build/assets/gfx__bank_a.bin", 0x56838, 0x10D4
	.global gNegateAnim
gNegateAnim: @ 0x0868DB94
	.incbin "build/assets/gfx__bank_a.bin", 0x5790C, 0x10A4
	.global gNegateAnimSideways
gNegateAnimSideways: @ 0x0868EC38
	.incbin "build/assets/gfx__bank_a.bin", 0x589B0, 0x20D4
	.global gTributeAnim
gTributeAnim: @ 0x08690D0C
	.incbin "build/assets/gfx__bank_a.bin", 0x5AA84, 0x419C
	.global gDeckShuffleAnim
gDeckShuffleAnim: @ 0x08694EA8
	.incbin "build/assets/gfx__bank_a.bin", 0x5EC20, 0x2874
	.global gSmokePuffAnim
gSmokePuffAnim: @ 0x0869771C
	.incbin "build/assets/gfx__bank_a.bin", 0x61494, 0x1560
	.global gCardListViewButtonsPal
gCardListViewButtonsPal: @ 0x08698C7C
	.incbin "build/assets/gfx__bank_a.bin", 0x629F4, 0x20
	.global gCardListViewButtonsGfx
gCardListViewButtonsGfx: @ 0x08698C9C
	.incbin "build/assets/gfx__bank_a.bin", 0x62A14, 0x2080
	.global gCardListViewStatusIconsPal
gCardListViewStatusIconsPal: @ 0x0869AD1C
	.incbin "build/assets/gfx__bank_a.bin", 0x64A94, 0x20
	.global gCardListViewStatusIconsGfx
gCardListViewStatusIconsGfx: @ 0x0869AD3C
	.incbin "build/assets/gfx__bank_a.bin", 0x64AB4, 0x800
	.global gCardListViewTitlesPal
gCardListViewTitlesPal: @ 0x0869B53C
	.incbin "build/assets/gfx__bank_a.bin", 0x652B4, 0x20
	.global gCardListViewTitlesGfx
gCardListViewTitlesGfx: @ 0x0869B55C
	.incbin "build/assets/gfx__bank_a.bin", 0x652D4, 0xF00
	.global gCardListViewBgImage
gCardListViewBgImage: @ 0x0869C45C
	.incbin "build/assets/gfx__bank_a.bin", 0x661D4, 0x12FC
	.global gCardListViewInfoPanelImage
gCardListViewInfoPanelImage: @ 0x0869D758
	.incbin "build/assets/gfx__bank_a.bin", 0x674D0, 0x118C
	.global gCardListViewHeaderImage
gCardListViewHeaderImage: @ 0x0869E8E4
	.incbin "build/assets/gfx__bank_a.bin", 0x6865C, 0x5E8
	.global gCardListViewCursorFramePal
gCardListViewCursorFramePal: @ 0x0869EECC
	.incbin "build/assets/gfx__bank_a.bin", 0x68C44, 0x20
	.global gCardListViewCursorFrameGfx
gCardListViewCursorFrameGfx: @ 0x0869EEEC
	.incbin "build/assets/gfx__bank_a.bin", 0x68C64, 0x2400
	.global gEgyptCorridorBitmap
gEgyptCorridorBitmap: @ 0x086A12EC
	.incbin "build/assets/gfx__bank_a.bin", 0x6B064, 0x9600
	.global gEgyptCorridorPal
gEgyptCorridorPal: @ 0x086AA8EC
	.incbin "build/assets/gfx__bank_a.bin", 0x74664, 0x200
	.global gRockCardPal
gRockCardPal: @ 0x086AAAEC
	.incbin "build/assets/gfx__bank_a.bin", 0x74864, 0x14
	.global gScissorsCardPal
gScissorsCardPal: @ 0x086AAB00
	.incbin "build/assets/gfx__bank_a.bin", 0x74878, 0x20
	.global gPaperCardPal
gPaperCardPal: @ 0x086AAB20
	.incbin "build/assets/gfx__bank_a.bin", 0x74898, 0x20
	.global gTurnChoiceBannerPal
gTurnChoiceBannerPal: @ 0x086AAB40
	.incbin "build/assets/gfx__bank_a.bin", 0x748B8, 0x20
	.global gSelectCardBannerPal
gSelectCardBannerPal: @ 0x086AAB60
	.incbin "build/assets/gfx__bank_a.bin", 0x748D8, 0x20
	.global gDuelLogoPal
gDuelLogoPal: @ 0x086AAB80
	.incbin "build/assets/gfx__bank_a.bin", 0x748F8, 0x20
	.global gWinBannerPal
gWinBannerPal: @ 0x086AABA0
	.incbin "build/assets/gfx__bank_a.bin", 0x74918, 0x1C
	.global gLoseBannerPal
gLoseBannerPal: @ 0x086AABBC
	.incbin "build/assets/gfx__bank_a.bin", 0x74934, 0x20
	.global gDrawBannerPal
gDrawBannerPal: @ 0x086AABDC
	.incbin "build/assets/gfx__bank_a.bin", 0x74954, 0x24
	.global gTurnChoiceBannerDimPal
gTurnChoiceBannerDimPal: @ 0x086AAC00
	.incbin "build/assets/gfx__bank_a.bin", 0x74978, 0x20
	.global gWaitSignPal
gWaitSignPal: @ 0x086AAC20
	.incbin "build/assets/gfx__bank_a.bin", 0x74998, 0x8
	.global gRockCardTiles
gRockCardTiles: @ 0x086AAC28
	.incbin "build/assets/gfx__bank_a.bin", 0x749A0, 0x400
	.global gScissorsCardTiles
gScissorsCardTiles: @ 0x086AB028
	.incbin "build/assets/gfx__bank_a.bin", 0x74DA0, 0x400
	.global gPaperCardTiles
gPaperCardTiles: @ 0x086AB428
	.incbin "build/assets/gfx__bank_a.bin", 0x751A0, 0x400
	.global gTurnChoiceBannerTiles
gTurnChoiceBannerTiles: @ 0x086AB828
	.incbin "build/assets/gfx__bank_a.bin", 0x755A0, 0x800
	.global gSelectCardBannerTiles
gSelectCardBannerTiles: @ 0x086AC028
	.incbin "build/assets/gfx__bank_a.bin", 0x75DA0, 0x800
	.global gDuelLogoTiles0
gDuelLogoTiles0: @ 0x086AC828
	.incbin "build/assets/gfx__bank_a.bin", 0x765A0, 0x800
	.global gDuelLogoTiles1
gDuelLogoTiles1: @ 0x086AD028
	.incbin "build/assets/gfx__bank_a.bin", 0x76DA0, 0x800
	.global gDuelLogoTiles2
gDuelLogoTiles2: @ 0x086AD828
	.incbin "build/assets/gfx__bank_a.bin", 0x775A0, 0x800
	.global gWinBannerTiles
gWinBannerTiles: @ 0x086AE028
	.incbin "build/assets/gfx__bank_a.bin", 0x77DA0, 0x800
	.global gLoseBannerTiles
gLoseBannerTiles: @ 0x086AE828
	.incbin "build/assets/gfx__bank_a.bin", 0x785A0, 0x800
	.global gDrawBannerTiles
gDrawBannerTiles: @ 0x086AF028
	.incbin "build/assets/gfx__bank_a.bin", 0x78DA0, 0x800
	.global gWaitSignTiles
gWaitSignTiles: @ 0x086AF828
	.incbin "build/assets/gfx__bank_a.bin", 0x795A0, 0x200
	.global gCoinPalette
gCoinPalette: @ 0x086AFA28
	.incbin "build/assets/gfx__bank_a.bin", 0x797A0, 0x20
	.global gCoinSpinGfx
gCoinSpinGfx: @ 0x086AFA48
	.incbin "build/assets/gfx__bank_a.bin", 0x797C0, 0x200
	.global gCoinSpinGfx_Frame1
gCoinSpinGfx_Frame1: @ 0x086AFC48
	.incbin "build/assets/gfx__bank_a.bin", 0x799C0, 0x200
	.global gCoinSpinGfx_Frame2
gCoinSpinGfx_Frame2: @ 0x086AFE48
	.incbin "build/assets/gfx__bank_a.bin", 0x79BC0, 0x200
	.global gCoinSpinGfx_Frame3
gCoinSpinGfx_Frame3: @ 0x086B0048
	.incbin "build/assets/gfx__bank_a.bin", 0x79DC0, 0x200
	.global gCoinSpinGfx_Frame4
gCoinSpinGfx_Frame4: @ 0x086B0248
	.incbin "build/assets/gfx__bank_a.bin", 0x79FC0, 0x200
	.global gCoinSpinGfx_Frame5
gCoinSpinGfx_Frame5: @ 0x086B0448
	.incbin "build/assets/gfx__bank_a.bin", 0x7A1C0, 0x200
	.global gCoinSpinGfx_Frame6
gCoinSpinGfx_Frame6: @ 0x086B0648
	.incbin "build/assets/gfx__bank_a.bin", 0x7A3C0, 0x200
	.global gCoinSpinGfx_Frame7
gCoinSpinGfx_Frame7: @ 0x086B0848
	.incbin "build/assets/gfx__bank_a.bin", 0x7A5C0, 0x200
	.global gCoinGlintGfx
gCoinGlintGfx: @ 0x086B0A48
	.incbin "build/assets/gfx__bank_a.bin", 0x7A7C0, 0x200
	.global gCoinGlintGfx_Frame1
gCoinGlintGfx_Frame1: @ 0x086B0C48
	.incbin "build/assets/gfx__bank_a.bin", 0x7A9C0, 0x200
	.global gCoinGlintGfx_Frame2
gCoinGlintGfx_Frame2: @ 0x086B0E48
	.incbin "build/assets/gfx__bank_a.bin", 0x7ABC0, 0x200
	.global gCoinGlintGfx_Frame3
gCoinGlintGfx_Frame3: @ 0x086B1048
	.incbin "build/assets/gfx__bank_a.bin", 0x7ADC0, 0x200
	.global gCoinGlintGfx_Frame4
gCoinGlintGfx_Frame4: @ 0x086B1248
	.incbin "build/assets/gfx__bank_a.bin", 0x7AFC0, 0x200
	.global gCoinGlintGfx_Frame5
gCoinGlintGfx_Frame5: @ 0x086B1448
	.incbin "build/assets/gfx__bank_a.bin", 0x7B1C0, 0x200
	.global gCoinGlintGfx_Frame6
gCoinGlintGfx_Frame6: @ 0x086B1648
	.incbin "build/assets/gfx__bank_a.bin", 0x7B3C0, 0x200
	.global gCoinGlintGfx_Frame7
gCoinGlintGfx_Frame7: @ 0x086B1848
	.incbin "build/assets/gfx__bank_a.bin", 0x7B5C0, 0x200
	.global gCoinGlintGfx_Frame8
gCoinGlintGfx_Frame8: @ 0x086B1A48
	.incbin "build/assets/gfx__bank_a.bin", 0x7B7C0, 0x200
	.global gCoinGlintGfx_Frame9
gCoinGlintGfx_Frame9: @ 0x086B1C48
	.incbin "build/assets/gfx__bank_a.bin", 0x7B9C0, 0x200
	.global gSparkleGfx
gSparkleGfx: @ 0x086B1E48
	.incbin "build/assets/gfx__bank_a.bin", 0x7BBC0, 0x80
	.global gSparkleGfx_Frame1
gSparkleGfx_Frame1: @ 0x086B1EC8
	.incbin "build/assets/gfx__bank_a.bin", 0x7BC40, 0x80
	.global gSparkleGfx_Frame2
gSparkleGfx_Frame2: @ 0x086B1F48
	.incbin "build/assets/gfx__bank_a.bin", 0x7BCC0, 0x80
	.global gSparkleGfx_Frame3
gSparkleGfx_Frame3: @ 0x086B1FC8
	.incbin "build/assets/gfx__bank_a.bin", 0x7BD40, 0x80
	.global gSparkleGfx_Frame4
gSparkleGfx_Frame4: @ 0x086B2048
	.incbin "build/assets/gfx__bank_a.bin", 0x7BDC0, 0x80
	.global gSparkleGfx_Frame5
gSparkleGfx_Frame5: @ 0x086B20C8
	.incbin "build/assets/gfx__bank_a.bin", 0x7BE40, 0x80
	.global gSparklePalette
gSparklePalette: @ 0x086B2148
	.incbin "build/assets/gfx__bank_a.bin", 0x7BEC0, 0x20
	.global gDiceSceneObjTilesLeft
gDiceSceneObjTilesLeft: @ 0x086B2168
	.incbin "build/assets/gfx__bank_a.bin", 0x7BEE0, 0x2000
	.global gDiceSceneObjTilesRight
gDiceSceneObjTilesRight: @ 0x086B4168
	.incbin "build/assets/gfx__bank_a.bin", 0x7DEE0, 0x2000
	.global gDiceSceneObjPal
gDiceSceneObjPal: @ 0x086B6168
	.incbin "build/assets/gfx__bank_a.bin", 0x7FEE0, 0x200
	.global gExodiaPiecesObjPal
gExodiaPiecesObjPal: @ 0x086B6368
	.incbin "build/assets/gfx__bank_a.bin", 0x800E0, 0x200
	.global gExodiaPiecesObjTiles
gExodiaPiecesObjTiles: @ 0x086B6568
	.incbin "build/assets/gfx__bank_a.bin", 0x802E0, 0x2000
	.global gMillenniumEyeBitmap
gMillenniumEyeBitmap: @ 0x086B8568
	.incbin "build/assets/gfx__bank_a.bin", 0x822E0, 0x9600
	.global gMillenniumEyePal
gMillenniumEyePal: @ 0x086C1B68
	.incbin "build/assets/gfx__bank_a.bin", 0x8B8E0, 0x200
	.global gExodiaFlameBgTiles0
gExodiaFlameBgTiles0: @ 0x086C1D68
	.incbin "build/assets/gfx__bank_a.bin", 0x8BAE0, 0x2000
	.global gExodiaFlameBgTiles1
gExodiaFlameBgTiles1: @ 0x086C3D68
	.incbin "build/assets/gfx__bank_a.bin", 0x8DAE0, 0x2000
	.global gExodiaFlameBgTiles2
gExodiaFlameBgTiles2: @ 0x086C5D68
	.incbin "build/assets/gfx__bank_a.bin", 0x8FAE0, 0x2000
	.global gExodiaFlameBgTiles3
gExodiaFlameBgTiles3: @ 0x086C7D68
	.incbin "build/assets/gfx__bank_a.bin", 0x91AE0, 0x2000
	.global gExodiaFlameBg2Map
gExodiaFlameBg2Map: @ 0x086C9D68
	.incbin "build/assets/gfx__bank_a.bin", 0x93AE0, 0x4B0
	.global gExodiaFlameBg1Map
gExodiaFlameBg1Map: @ 0x086CA218
	.incbin "build/assets/gfx__bank_a.bin", 0x93F90, 0x4B0
	.global gExodiaFlameBg0Map
gExodiaFlameBg0Map: @ 0x086CA6C8
	.incbin "build/assets/gfx__bank_a.bin", 0x94440, 0x4B0
	.global gExodiaFlameBgPal
gExodiaFlameBgPal: @ 0x086CAB78
	.incbin "build/assets/gfx__bank_a.bin", 0x948F0, 0x200
	.global gExodiaFlameArmsObjTiles
gExodiaFlameArmsObjTiles: @ 0x086CAD78
	.incbin "build/assets/gfx__bank_a.bin", 0x94AF0, 0x2000
	.global gExodiaFlameObjTilesB
gExodiaFlameObjTilesB: @ 0x086CCD78
	.incbin "build/assets/gfx__bank_a.bin", 0x96AF0, 0x2000
	.global gExodiaPiecesColorObjTiles
gExodiaPiecesColorObjTiles: @ 0x086CED78
	.incbin "build/assets/gfx__bank_a.bin", 0x98AF0, 0xA00
	.global gExodiaPiecesGreyObjTiles
gExodiaPiecesGreyObjTiles: @ 0x086CF778
	.incbin "build/assets/gfx__bank_a.bin", 0x994F0, 0xA00
	.global gDestinyBoardBgTiles0
gDestinyBoardBgTiles0: @ 0x086D0178
	.incbin "build/assets/gfx__bank_a.bin", 0x99EF0, 0x2000
	.global gDestinyBoardBgTiles1
gDestinyBoardBgTiles1: @ 0x086D2178
	.incbin "build/assets/gfx__bank_a.bin", 0x9BEF0, 0x2000
	.global gDestinyBoardBgTiles2
gDestinyBoardBgTiles2: @ 0x086D4178
	.incbin "build/assets/gfx__bank_a.bin", 0x9DEF0, 0x2000
	.global gDestinyBoardObjTiles0
gDestinyBoardObjTiles0: @ 0x086D6178
	.incbin "build/assets/gfx__bank_a.bin", 0x9FEF0, 0x2000
	.global gDestinyBoardObjTiles1
gDestinyBoardObjTiles1: @ 0x086D8178
	.incbin "build/assets/gfx__bank_a.bin", 0xA1EF0, 0x2000
	.global gDestinyBoardObjTiles2
gDestinyBoardObjTiles2: @ 0x086DA178
	.incbin "build/assets/gfx__bank_a.bin", 0xA3EF0, 0x2000
	.global gDestinyBoardObjTiles3
gDestinyBoardObjTiles3: @ 0x086DC178
	.incbin "build/assets/gfx__bank_a.bin", 0xA5EF0, 0x2000
	.global gFinalLetterTiles
gFinalLetterTiles: @ 0x086DE178
	.incbin "build/assets/gfx__bank_a.bin", 0xA7EF0, 0x302C
	.global gDestinyBoardBg2Map
gDestinyBoardBg2Map: @ 0x086E11A4
	.incbin "build/assets/gfx__bank_a.bin", 0xAAF1C, 0xAC8
	.global gDestinyBoardBg1Map
gDestinyBoardBg1Map: @ 0x086E1C6C
	.incbin "build/assets/gfx__bank_a.bin", 0xAB9E4, 0x564
	.global gDestinyBoardWaveMap
gDestinyBoardWaveMap: @ 0x086E21D0
	.incbin "build/assets/gfx__bank_a.bin", 0xABF48, 0x100
	.global gDestinyBoardBgPal
gDestinyBoardBgPal: @ 0x086E22D0
	.incbin "build/assets/gfx__bank_a.bin", 0xAC048, 0x200
	.global gDestinyBoardObjPal
gDestinyBoardObjPal: @ 0x086E24D0
	.incbin "build/assets/gfx__bank_a.bin", 0xAC248, 0x200
	.global gDeckEditFrameMap
gDeckEditFrameMap: @ 0x086E26D0
	.incbin "build/assets/gfx__bank_a.bin", 0xAC448, 0x960
	.global gDeckEditBgTiles
gDeckEditBgTiles: @ 0x086E3030
	.incbin "build/assets/gfx__bank_a.bin", 0xACDA8, 0x2000
	.global gDeckEditObjTiles
gDeckEditObjTiles: @ 0x086E5030
	.incbin "build/assets/gfx__bank_a.bin", 0xAEDA8, 0x2000
	.global gDeckEditCardStackObjTiles
gDeckEditCardStackObjTiles: @ 0x086E7030
	.incbin "build/assets/gfx__bank_a.bin", 0xB0DA8, 0x2000
	.global gDeckEditCardIconObjTiles
gDeckEditCardIconObjTiles: @ 0x086E9030
	.incbin "build/assets/gfx__bank_a.bin", 0xB2DA8, 0x2000
	.global gDeckEditCardFrameObjTiles
gDeckEditCardFrameObjTiles: @ 0x086EB030
	.incbin "build/assets/gfx__bank_a.bin", 0xB4DA8, 0x2000
	.global gDeckEditBgPals4to7
gDeckEditBgPals4to7: @ 0x086ED030
	.incbin "build/assets/gfx__bank_a.bin", 0xB6DA8, 0x80
	.global gDeckEditBgPals1to3
gDeckEditBgPals1to3: @ 0x086ED0B0
	.incbin "build/assets/gfx__bank_a.bin", 0xB6E28, 0xE0
	.global gDeckEditBgPal3
gDeckEditBgPal3: @ 0x086ED190
	.incbin "build/assets/gfx__bank_a.bin", 0xB6F08, 0x20
	.global gDeckEditObjPal
gDeckEditObjPal: @ 0x086ED1B0
	.incbin "build/assets/gfx__bank_a.bin", 0xB6F28, 0x200
	.global gDeckEditLabelTiles
gDeckEditLabelTiles: @ 0x086ED3B0
	.incbin "build/assets/gfx__bank_a.bin", 0xB7128, 0x2000
	.global gDeckEditCommandLabelGfx
gDeckEditCommandLabelGfx: @ 0x086EF3B0
	.incbin "build/assets/gfx__bank_a.bin", 0xB9128, 0x1C00
	.global gDeckEditSwapLabelGfx
gDeckEditSwapLabelGfx: @ 0x086F0FB0
	.incbin "build/assets/gfx__bank_a.bin", 0xBAD28, 0x400
	.global gDeckEditDecideLabelGfx
gDeckEditDecideLabelGfx: @ 0x086F13B0
	.incbin "build/assets/gfx__bank_a.bin", 0xBB128, 0x400
	.global gDeckEditMenuTilemap
gDeckEditMenuTilemap: @ 0x086F17B0
	.incbin "build/assets/gfx__bank_a.bin", 0xBB528, 0x24
	.global gDeckEditMenuTilemapFilterLabels
gDeckEditMenuTilemapFilterLabels: @ 0x086F17D4
	.incbin "build/assets/gfx__bank_a.bin", 0xBB54C, 0xC
	.global gDeckEditMenuTilemapSortLabels
gDeckEditMenuTilemapSortLabels: @ 0x086F17E0
	.incbin "build/assets/gfx__bank_a.bin", 0xBB558, 0x8
	.global gDeckEditMenuTilemapBarEnd
gDeckEditMenuTilemapBarEnd: @ 0x086F17E8
	.incbin "build/assets/gfx__bank_a.bin", 0xBB560, 0x328
	.global gDeckEditMenuTilemapStatementLabels
gDeckEditMenuTilemapStatementLabels: @ 0x086F1B10
	.incbin "build/assets/gfx__bank_a.bin", 0xBB888, 0x150
	.global gListFilterBgPal
gListFilterBgPal: @ 0x086F1C60
	.incbin "build/assets/gfx__bank_a.bin", 0xBB9D8, 0x200
	.global gListFilterObjPal
gListFilterObjPal: @ 0x086F1E60
	.incbin "build/assets/gfx__bank_a.bin", 0xBBBD8, 0x200
	.global gListFilterBgTiles0
gListFilterBgTiles0: @ 0x086F2060
	.incbin "build/assets/gfx__bank_a.bin", 0xBBDD8, 0x2000
	.global gListFilterBgTiles1
gListFilterBgTiles1: @ 0x086F4060
	.incbin "build/assets/gfx__bank_a.bin", 0xBDDD8, 0x140
	.global gListFilterBarFillTiles
gListFilterBarFillTiles: @ 0x086F41A0
	.incbin "build/assets/gfx__bank_a.bin", 0xBDF18, 0x1EC0
	.global gListFilterBgTiles2
gListFilterBgTiles2: @ 0x086F6060
	.incbin "build/assets/gfx__bank_a.bin", 0xBFDD8, 0x2000
	.global gListFilterObjTiles0
gListFilterObjTiles0: @ 0x086F8060
	.incbin "build/assets/gfx__bank_a.bin", 0xC1DD8, 0x2000
	.global gListFilterObjTiles1
gListFilterObjTiles1: @ 0x086FA060
	.incbin "build/assets/gfx__bank_a.bin", 0xC3DD8, 0x2000
	.global gListFilterBgPatternMap
gListFilterBgPatternMap: @ 0x086FC060
	.incbin "build/assets/gfx__bank_a.bin", 0xC5DD8, 0x80
	.global gListFilterPanelMap
gListFilterPanelMap: @ 0x086FC0E0
	.incbin "build/assets/gfx__bank_a.bin", 0xC5E58, 0x4B0
	.global gListFilterFilterPageMap
gListFilterFilterPageMap: @ 0x086FC590
	.incbin "build/assets/gfx__bank_a.bin", 0xC6308, 0x4B0
	.global gListFilterSortPageMap
gListFilterSortPageMap: @ 0x086FCA40
	.incbin "build/assets/gfx__bank_a.bin", 0xC67B8, 0x690
	.global gListFilterBarFrameMap
gListFilterBarFrameMap: @ 0x086FD0D0
	.incbin "build/assets/gfx__bank_a.bin", 0xC6E48, 0x4B0
	.global gListFilterNowFilteringMap
gListFilterNowFilteringMap: @ 0x086FD580
	.incbin "build/assets/gfx__bank_a.bin", 0xC72F8, 0x2D0
	.global gListFilterListIconMap
gListFilterListIconMap: @ 0x086FD850
	.incbin "build/assets/gfx__bank_a.bin", 0xC75C8, 0xD4
	.global gDeckStatsBgPal
gDeckStatsBgPal: @ 0x086FD924
	.incbin "build/assets/gfx__bank_a.bin", 0xC769C, 0x200
	.global gDeckStatsBgTiles
gDeckStatsBgTiles: @ 0x086FDB24
	.incbin "build/assets/gfx__bank_a.bin", 0xC789C, 0x2000
	.global gDeckStatsLabelTiles
gDeckStatsLabelTiles: @ 0x086FFB24
	.incbin "build/assets/gfx__bank_a.bin", 0xC989C, 0x2000
	.global gDeckStatsPatternMap
gDeckStatsPatternMap: @ 0x08701B24
	.incbin "build/assets/gfx__bank_a.bin", 0xCB89C, 0x80
	.global gDeckStatsPanelMap
gDeckStatsPanelMap: @ 0x08701BA4
	.incbin "build/assets/gfx__bank_a.bin", 0xCB91C, 0x4B0
	.global gDeckStatsBg1Map
gDeckStatsBg1Map: @ 0x08702054
	.incbin "build/assets/gfx__bank_a.bin", 0xCBDCC, 0x4B0
	.global gDeckStatsListIconMap
gDeckStatsListIconMap: @ 0x08702504
	.incbin "build/assets/gfx__bank_a.bin", 0xCC27C, 0xD4
	.global gProhibitSelectFrameMap
gProhibitSelectFrameMap: @ 0x087025D8
	.incbin "build/assets/gfx__bank_a.bin", 0xCC350, 0x4B0
	.global gProhibitSelectBgPals4to7
gProhibitSelectBgPals4to7: @ 0x08702A88
	.incbin "build/assets/gfx__bank_a.bin", 0xCC800, 0x80
	.global gProhibitSelectBgPals1to3
gProhibitSelectBgPals1to3: @ 0x08702B08
	.incbin "build/assets/gfx__bank_a.bin", 0xCC880, 0xE0
	.global gProhibitSelectBgPal3
gProhibitSelectBgPal3: @ 0x08702BE8
	.incbin "build/assets/gfx__bank_a.bin", 0xCC960, 0x20
	.global gProhibitSelectBgTiles
gProhibitSelectBgTiles: @ 0x08702C08
	.incbin "build/assets/gfx__bank_a.bin", 0xCC980, 0x2140
	.global gCardKindIconRitualGfx
gCardKindIconRitualGfx: @ 0x08704D48
	.incbin "build/assets/gfx__bank_a.bin", 0xCEAC0, 0xA0
	.global gCardKindIconEffectGfx
gCardKindIconEffectGfx: @ 0x08704DE8
	.incbin "build/assets/gfx__bank_a.bin", 0xCEB60, 0xA0
	.global gDeckEditStatIconGfx
gDeckEditStatIconGfx: @ 0x08704E88
	.incbin "build/assets/gfx__bank_a.bin", 0xCEC00, 0x60
	.global gDeckEditStatIconPal
gDeckEditStatIconPal: @ 0x08704EE8
	.incbin "build/assets/gfx__bank_a.bin", 0xCEC60, 0xC0
	.global gCardKindIconFusionGfx
gCardKindIconFusionGfx: @ 0x08704FA8
	.incbin "build/assets/gfx__bank_a.bin", 0xCED20, 0xA0
	.global gSpellSubtypeIconCounterGfx
gSpellSubtypeIconCounterGfx: @ 0x08705048
	.incbin "build/assets/gfx__bank_a.bin", 0xCEDC0, 0x140
	.global gSpellSubtypeIconContinuousGfx
gSpellSubtypeIconContinuousGfx: @ 0x08705188
	.incbin "build/assets/gfx__bank_a.bin", 0xCEF00, 0x140
	.global gSpellSubtypeIconFieldGfx
gSpellSubtypeIconFieldGfx: @ 0x087052C8
	.incbin "build/assets/gfx__bank_a.bin", 0xCF040, 0x140
	.global gSpellSubtypeIconRitualGfx
gSpellSubtypeIconRitualGfx: @ 0x08705408
	.incbin "build/assets/gfx__bank_a.bin", 0xCF180, 0x220
	.global gSpellSubtypeIconEquipGfx
gSpellSubtypeIconEquipGfx: @ 0x08705628
	.incbin "build/assets/gfx__bank_a.bin", 0xCF3A0, 0xA0
	.global gSpellSubtypeIconQuickPlayGfx
gSpellSubtypeIconQuickPlayGfx: @ 0x087056C8
	.incbin "build/assets/gfx__bank_a.bin", 0xCF440, 0xA0
	.global gTypeIconFiendGfx
gTypeIconFiendGfx: @ 0x08705768
	.incbin "build/assets/gfx__bank_a.bin", 0xCF4E0, 0xA0
	.global gTypeIconDragonGfx
gTypeIconDragonGfx: @ 0x08705808
	.incbin "build/assets/gfx__bank_a.bin", 0xCF580, 0xA0
	.global gTypeIconRockGfx
gTypeIconRockGfx: @ 0x087058A8
	.incbin "build/assets/gfx__bank_a.bin", 0xCF620, 0xA0
	.global gTypeIconReptileGfx
gTypeIconReptileGfx: @ 0x08705948
	.incbin "build/assets/gfx__bank_a.bin", 0xCF6C0, 0xA0
	.global gTypeIconPyroGfx
gTypeIconPyroGfx: @ 0x087059E8
	.incbin "build/assets/gfx__bank_a.bin", 0xCF760, 0xA0
	.global gTypeIconBeastWarriorGfx
gTypeIconBeastWarriorGfx: @ 0x08705A88
	.incbin "build/assets/gfx__bank_a.bin", 0xCF800, 0xA0
	.global gTypeIconSeaSerpentGfx
gTypeIconSeaSerpentGfx: @ 0x08705B28
	.incbin "build/assets/gfx__bank_a.bin", 0xCF8A0, 0xA0
	.global gTypeIconThunderGfx
gTypeIconThunderGfx: @ 0x08705BC8
	.incbin "build/assets/gfx__bank_a.bin", 0xCF940, 0xA0
	.global gTypeIconBeastGfx
gTypeIconBeastGfx: @ 0x08705C68
	.incbin "build/assets/gfx__bank_a.bin", 0xCF9E0, 0xA0
	.global gTypeIconMachineGfx
gTypeIconMachineGfx: @ 0x08705D08
	.incbin "build/assets/gfx__bank_a.bin", 0xCFA80, 0xA0
	.global gTypeIconInsectGfx
gTypeIconInsectGfx: @ 0x08705DA8
	.incbin "build/assets/gfx__bank_a.bin", 0xCFB20, 0xA0
	.global gTypeIconDinosaurGfx
gTypeIconDinosaurGfx: @ 0x08705E48
	.incbin "build/assets/gfx__bank_a.bin", 0xCFBC0, 0xA0
	.global gTypeIconSpellcasterGfx
gTypeIconSpellcasterGfx: @ 0x08705EE8
	.incbin "build/assets/gfx__bank_a.bin", 0xCFC60, 0xA0
	.global gTypeIconAquaGfx
gTypeIconAquaGfx: @ 0x08705F88
	.incbin "build/assets/gfx__bank_a.bin", 0xCFD00, 0xA0
	.global gTypeIconFishGfx
gTypeIconFishGfx: @ 0x08706028
	.incbin "build/assets/gfx__bank_a.bin", 0xCFDA0, 0xA0
	.global gTypeIconWarriorGfx
gTypeIconWarriorGfx: @ 0x087060C8
	.incbin "build/assets/gfx__bank_a.bin", 0xCFE40, 0xA0
	.global gTypeIconPlantGfx
gTypeIconPlantGfx: @ 0x08706168
	.incbin "build/assets/gfx__bank_a.bin", 0xCFEE0, 0xA0
	.global gTypeIconFairyGfx
gTypeIconFairyGfx: @ 0x08706208
	.incbin "build/assets/gfx__bank_a.bin", 0xCFF80, 0xA0
	.global gTypeIconWingedBeastGfx
gTypeIconWingedBeastGfx: @ 0x087062A8
	.incbin "build/assets/gfx__bank_a.bin", 0xD0020, 0xA0
	.global gTypeIconZombieGfx
gTypeIconZombieGfx: @ 0x08706348
	.incbin "build/assets/gfx__bank_a.bin", 0xD00C0, 0xA0
	.global gAttributeIconEarthGfx
gAttributeIconEarthGfx: @ 0x087063E8
	.incbin "build/assets/gfx__bank_a.bin", 0xD0160, 0x140
	.global gAttributeIconLightGfx
gAttributeIconLightGfx: @ 0x08706528
	.incbin "build/assets/gfx__bank_a.bin", 0xD02A0, 0x140
	.global gAttributeIconFireGfx
gAttributeIconFireGfx: @ 0x08706668
	.incbin "build/assets/gfx__bank_a.bin", 0xD03E0, 0x140
	.global gAttributeIconDivineGfx
gAttributeIconDivineGfx: @ 0x087067A8
	.incbin "build/assets/gfx__bank_a.bin", 0xD0520, 0x140
	.global gAttributeIconWindGfx
gAttributeIconWindGfx: @ 0x087068E8
	.incbin "build/assets/gfx__bank_a.bin", 0xD0660, 0x140
	.global gAttributeIconMagicGfx
gAttributeIconMagicGfx: @ 0x08706A28
	.incbin "build/assets/gfx__bank_a.bin", 0xD07A0, 0x140
	.global gAttributeIconWaterGfx
gAttributeIconWaterGfx: @ 0x08706B68
	.incbin "build/assets/gfx__bank_a.bin", 0xD08E0, 0x140
	.global gAttributeIconTrapGfx
gAttributeIconTrapGfx: @ 0x08706CA8
	.incbin "build/assets/gfx__bank_a.bin", 0xD0A20, 0x140
	.global gAttributeIconDarkGfx
gAttributeIconDarkGfx: @ 0x08706DE8
	.incbin "build/assets/gfx__bank_a.bin", 0xD0B60, 0x140
	.global gDeckEditCardBoxTiles0
gDeckEditCardBoxTiles0: @ 0x08706F28
	.incbin "build/assets/gfx__bank_a.bin", 0xD0CA0, 0x180
	.global gDeckEditCardBoxTiles1
gDeckEditCardBoxTiles1: @ 0x087070A8
	.incbin "build/assets/gfx__bank_a.bin", 0xD0E20, 0x180
	.global gDeckEditCardBoxTiles2
gDeckEditCardBoxTiles2: @ 0x08707228
	.incbin "build/assets/gfx__bank_a.bin", 0xD0FA0, 0x180
	.global gDeckEditCardBoxTiles4
gDeckEditCardBoxTiles4: @ 0x087073A8
	.incbin "build/assets/gfx__bank_a.bin", 0xD1120, 0x180
	.global gDeckEditCardBoxTiles5
gDeckEditCardBoxTiles5: @ 0x08707528
	.incbin "build/assets/gfx__bank_a.bin", 0xD12A0, 0x180
	.global gDeckEditCardBoxTiles3
gDeckEditCardBoxTiles3: @ 0x087076A8
	.incbin "build/assets/gfx__bank_a.bin", 0xD1420, 0x180
	.global gDeckEditSmallCardBoxTiles0
gDeckEditSmallCardBoxTiles0: @ 0x08707828
	.incbin "build/assets/gfx__bank_a.bin", 0xD15A0, 0x80
	.global gDeckEditSmallCardBoxTiles1
gDeckEditSmallCardBoxTiles1: @ 0x087078A8
	.incbin "build/assets/gfx__bank_a.bin", 0xD1620, 0x80
	.global gDeckEditSmallCardBoxTiles2
gDeckEditSmallCardBoxTiles2: @ 0x08707928
	.incbin "build/assets/gfx__bank_a.bin", 0xD16A0, 0x80
	.global gDeckEditSmallCardBoxTiles4
gDeckEditSmallCardBoxTiles4: @ 0x087079A8
	.incbin "build/assets/gfx__bank_a.bin", 0xD1720, 0x80
	.global gDeckEditSmallCardBoxTiles5
gDeckEditSmallCardBoxTiles5: @ 0x08707A28
	.incbin "build/assets/gfx__bank_a.bin", 0xD17A0, 0x80
	.global gDeckEditSmallCardBoxTiles3
gDeckEditSmallCardBoxTiles3: @ 0x08707AA8
	.incbin "build/assets/gfx__bank_a.bin", 0xD1820, 0x80
	.global gCardTradingBgImage
gCardTradingBgImage: @ 0x08707B28
	.incbin "build/assets/gfx__bank_a.bin", 0xD18A0, 0x1AB8
	.global gCardTradingButtonsGfx
gCardTradingButtonsGfx: @ 0x087095E0
	.incbin "build/assets/gfx__bank_a.bin", 0xD3358, 0x1000
	.global gCardTradingButtonsDimGfx
gCardTradingButtonsDimGfx: @ 0x0870A5E0
	.incbin "build/assets/gfx__bank_a.bin", 0xD4358, 0x1000
	.global gCardTradingButtonsPal
gCardTradingButtonsPal: @ 0x0870B5E0
	.incbin "build/assets/gfx__bank_a.bin", 0xD5358, 0x20
	.global gCardTradingButtonsDimPal
gCardTradingButtonsDimPal: @ 0x0870B600
	.incbin "build/assets/gfx__bank_a.bin", 0xD5378, 0x20
	.global gCardTradingCardGfx
gCardTradingCardGfx: @ 0x0870B620
	.incbin "build/assets/gfx__bank_a.bin", 0xD5398, 0x1000
	.global gCardTradingCardPal
gCardTradingCardPal: @ 0x0870C620
	.incbin "build/assets/gfx__bank_a.bin", 0xD6398, 0x20
@ gfx/scenes/set02 (gfx_scenes_set)
	.incbin "build/assets/gfx__scenes__set02.bin", 0x0, 0x3880
@ gfx/scenes/set00 (gfx_scenes_set)
	.incbin "build/assets/gfx__scenes__set00.bin", 0x0, 0x30D8
@ gfx/scenes/set03 (gfx_scenes_set)
	.incbin "build/assets/gfx__scenes__set03.bin", 0x0, 0x3118
@ gfx/scenes/set04 (gfx_scenes_set)
	.incbin "build/assets/gfx__scenes__set04.bin", 0x0, 0x2810
@ gfx/scenes/set01 (gfx_scenes_set)
	.incbin "build/assets/gfx__scenes__set01.bin", 0x0, 0x2D90
@ gfx/small_graphics (gfx_banks_bank)
	.global gOpponentSelectObjPal
gOpponentSelectObjPal: @ 0x0871B650
	.incbin "build/assets/gfx__small_graphics.bin", 0x0, 0x200
	.global gOpponentSelectObjTiles
gOpponentSelectObjTiles: @ 0x0871B850
	.incbin "build/assets/gfx__small_graphics.bin", 0x200, 0x1000
	.global gOpponentSelectTextPal
gOpponentSelectTextPal: @ 0x0871C850
	.incbin "build/assets/gfx__small_graphics.bin", 0x1200, 0x200
	.global gOpponentSelectDigitTiles
gOpponentSelectDigitTiles: @ 0x0871CA50
	.incbin "build/assets/gfx__small_graphics.bin", 0x1400, 0x140
	.global gOpponentSelectDimDigitTiles
gOpponentSelectDimDigitTiles: @ 0x0871CB90
	.incbin "build/assets/gfx__small_graphics.bin", 0x1540, 0x2C0
@ gfx/mode4_bitmaps (gfx_banks_bank)
	.incbin "build/assets/gfx__mode4_bitmaps.bin", 0x0, 0x2F800
@ gfx/dialogue_box (gfx_scenes_box)
	.incbin "build/assets/gfx__dialogue_box.bin", 0x0, 0xF60
	.global gDialogueHeaderLz
gDialogueHeaderLz: @ 0x0874D5B0
	.incbin "build/assets/gfx__dialogue_box.bin", 0xF60, 0x2
	.global gDialogueHeaderLzSizeHi
gDialogueHeaderLzSizeHi: @ 0x0874D5B2
	.incbin "build/assets/gfx__dialogue_box.bin", 0xF62, 0x2
	.global gDialogueHeaderLzData
gDialogueHeaderLzData: @ 0x0874D5B4
	.incbin "build/assets/gfx__dialogue_box.bin", 0xF64, 0xB50
	.global gDialogueBoxPalette
gDialogueBoxPalette: @ 0x0874E104
	.incbin "build/assets/gfx__dialogue_box.bin", 0x1AB4, 0x200
	.global gDialogueTextPalette
gDialogueTextPalette: @ 0x0874E304
	.incbin "build/assets/gfx__dialogue_box.bin", 0x1CB4, 0x20
@ gfx/scenes/set05 (gfx_scenes_set)
	.incbin "build/assets/gfx__scenes__set05.bin", 0x0, 0x4A24
@ gfx/scenes/set06 (gfx_scenes_set)
	.incbin "build/assets/gfx__scenes__set06.bin", 0x0, 0x41F0
@ gfx/scenes/set07 (gfx_scenes_set)
	.incbin "build/assets/gfx__scenes__set07.bin", 0x0, 0x44C4
@ gfx/scenes/set08 (gfx_scenes_set)
	.incbin "build/assets/gfx__scenes__set08.bin", 0x0, 0x4180
@ gfx/scenes/set09 (gfx_scenes_set)
	.incbin "build/assets/gfx__scenes__set09.bin", 0x0, 0x439C
@ gfx/scenes/set14 (gfx_scenes_set)
	.incbin "build/assets/gfx__scenes__set14.bin", 0x0, 0x45AC
@ gfx/scenes/set15 (gfx_scenes_set)
	.incbin "build/assets/gfx__scenes__set15.bin", 0x0, 0x495C
@ gfx/scenes/set16 (gfx_scenes_set)
	.incbin "build/assets/gfx__scenes__set16.bin", 0x0, 0x4B84
@ gfx/scenes/set17 (gfx_scenes_set)
	.incbin "build/assets/gfx__scenes__set17.bin", 0x0, 0x45E0
@ gfx/scenes/set18 (gfx_scenes_set)
	.incbin "build/assets/gfx__scenes__set18.bin", 0x0, 0x4398
@ gfx/scenes/set10 (gfx_scenes_set)
	.incbin "build/assets/gfx__scenes__set10.bin", 0x0, 0x48C4
@ gfx/scenes/set19 (gfx_scenes_set)
	.incbin "build/assets/gfx__scenes__set19.bin", 0x0, 0x4888
@ gfx/scenes/set20 (gfx_scenes_set)
	.incbin "build/assets/gfx__scenes__set20.bin", 0x0, 0x44AC
@ gfx/scenes/set11 (gfx_scenes_set)
	.incbin "build/assets/gfx__scenes__set11.bin", 0x0, 0x4A70
@ gfx/scenes/set21 (gfx_scenes_set)
	.incbin "build/assets/gfx__scenes__set21.bin", 0x0, 0x454C
@ gfx/scenes/set23 (gfx_scenes_set)
	.incbin "build/assets/gfx__scenes__set23.bin", 0x0, 0x46C8
@ gfx/scenes/set22 (gfx_scenes_set)
	.incbin "build/assets/gfx__scenes__set22.bin", 0x0, 0x4188
@ gfx/scenes/set24 (gfx_scenes_set)
	.incbin "build/assets/gfx__scenes__set24.bin", 0x0, 0x4730
@ gfx/scenes/set25 (gfx_scenes_set)
	.incbin "build/assets/gfx__scenes__set25.bin", 0x0, 0x3F34
@ gfx/scenes/set13 (gfx_scenes_set)
	.incbin "build/assets/gfx__scenes__set13.bin", 0x0, 0x3C68
@ gfx/scenes/set26 (gfx_scenes_set)
	.incbin "build/assets/gfx__scenes__set26.bin", 0x0, 0x4804
@ gfx/scenes/set12 (gfx_scenes_set)
	.incbin "build/assets/gfx__scenes__set12.bin", 0x0, 0x4620
@ gfx/scenes/set27 (gfx_scenes_set)
	.incbin "build/assets/gfx__scenes__set27.bin", 0x0, 0x4338
@ gfx/scenes/set28 (gfx_scenes_set)
	.incbin "build/assets/gfx__scenes__set28.bin", 0x0, 0x3A60
@ gfx/scenes/set29 (gfx_scenes_set)
	.incbin "build/assets/gfx__scenes__set29.bin", 0x0, 0x3FF8
@ gfx/scenes/set30 (gfx_scenes_set)
	.incbin "build/assets/gfx__scenes__set30.bin", 0x0, 0x4108
@ gfx/bank_b (gfx_banks_bank)
	.global gTitleLogoImage
gTitleLogoImage: @ 0x087BDAA8
	.incbin "build/assets/gfx__bank_b.bin", 0x0, 0x2AC4
	.global gTitleCopyrightImage
gTitleCopyrightImage: @ 0x087C056C
	.incbin "build/assets/gfx__bank_b.bin", 0x2AC4, 0x768
	.global gTitleCoinImage
gTitleCoinImage: @ 0x087C0CD4
	.incbin "build/assets/gfx__bank_b.bin", 0x322C, 0x10F8
	.global gTitleFlameImage
gTitleFlameImage: @ 0x087C1DCC
	.incbin "build/assets/gfx__bank_b.bin", 0x4324, 0xC08
	.global gDeletePromptBgBitmap
gDeletePromptBgBitmap: @ 0x087C29D4
	.incbin "build/assets/gfx__bank_b.bin", 0x4F2C, 0x9600
	.global gDeletePromptBgPal
gDeletePromptBgPal: @ 0x087CBFD4
	.incbin "build/assets/gfx__bank_b.bin", 0xE52C, 0x200
	.global gDeletePromptObjGfx
gDeletePromptObjGfx: @ 0x087CC1D4
	.incbin "build/assets/gfx__bank_b.bin", 0xE72C, 0x4000
	.global gDeletePromptObjPal
gDeletePromptObjPal: @ 0x087D01D4
	.incbin "build/assets/gfx__bank_b.bin", 0x1272C, 0x20
	.global gKonamiLogoImage
gKonamiLogoImage: @ 0x087D01F4
	.incbin "build/assets/gfx__bank_b.bin", 0x1274C, 0x2738
	.global gKcejLogoImage
gKcejLogoImage: @ 0x087D292C
	.incbin "build/assets/gfx__bank_b.bin", 0x14E84, 0x21F8
	.global gMainMenuSkyImage
gMainMenuSkyImage: @ 0x087D4B24
	.incbin "build/assets/gfx__bank_b.bin", 0x1707C, 0x9D34
	.global gMainMenuObjPal
gMainMenuObjPal: @ 0x087DE858
	.incbin "build/assets/gfx__bank_b.bin", 0x20DB0, 0x20
	.global gMainMenuObjGfx
gMainMenuObjGfx: @ 0x087DE878
	.incbin "build/assets/gfx__bank_b.bin", 0x20DD0, 0x4000
	.global gRecordMarkerObjPal
gRecordMarkerObjPal: @ 0x087E2878
	.incbin "build/assets/gfx__bank_b.bin", 0x24DD0, 0x200
	.global gRecordArrowObjPal
gRecordArrowObjPal: @ 0x087E2A78
	.incbin "build/assets/gfx__bank_b.bin", 0x24FD0, 0x200
	.global gRecordMarkerObjGfx
gRecordMarkerObjGfx: @ 0x087E2C78
	.incbin "build/assets/gfx__bank_b.bin", 0x251D0, 0x200
	.global gRecordArrowObjGfxTop
gRecordArrowObjGfxTop: @ 0x087E2E78
	.incbin "build/assets/gfx__bank_b.bin", 0x253D0, 0x200
	.global gRecordArrowObjGfxBottom
gRecordArrowObjGfxBottom: @ 0x087E3078
	.incbin "build/assets/gfx__bank_b.bin", 0x255D0, 0x200
	.global gRecordDigitPal
gRecordDigitPal: @ 0x087E3278
	.incbin "build/assets/gfx__bank_b.bin", 0x257D0, 0x200
	.global gRecordDigitGfx
gRecordDigitGfx: @ 0x087E3478
	.incbin "build/assets/gfx__bank_b.bin", 0x259D0, 0x140
	.global gRecordBgPatternImage
gRecordBgPatternImage: @ 0x087E35B8
	.incbin "build/assets/gfx__bank_b.bin", 0x25B10, 0xCC8
	.global gRecordFrameImage
gRecordFrameImage: @ 0x087E4280
	.incbin "build/assets/gfx__bank_b.bin", 0x267D8, 0x1024
	.global gRecordRows5Image
gRecordRows5Image: @ 0x087E52A4
	.incbin "build/assets/gfx__bank_b.bin", 0x277FC, 0xA50
	.global gRecordRows4Image
gRecordRows4Image: @ 0x087E5CF4
	.incbin "build/assets/gfx__bank_b.bin", 0x2824C, 0x1AC0
	.global gRecordUnknownPortraitImage
gRecordUnknownPortraitImage: @ 0x087E77B4
	.incbin "build/assets/gfx__bank_b.bin", 0x29D0C, 0x2F64
	.global gCalendarBgBitmap
gCalendarBgBitmap: @ 0x087EA718
	.incbin "build/assets/gfx__bank_b.bin", 0x2CC70, 0x7080
	.global gCalendarBgEventPanel
gCalendarBgEventPanel: @ 0x087F1798
	.incbin "build/assets/gfx__bank_b.bin", 0x33CF0, 0x2580
	.global gCalendarBgPal
gCalendarBgPal: @ 0x087F3D18
	.incbin "build/assets/gfx__bank_b.bin", 0x36270, 0x200
	.global gCalendarNumberPal
gCalendarNumberPal: @ 0x087F3F18
	.incbin "build/assets/gfx__bank_b.bin", 0x36470, 0x200
	.global gCalendarNumberTiles
gCalendarNumberTiles: @ 0x087F4118
	.incbin "build/assets/gfx__bank_b.bin", 0x36670, 0xC00
	.global gCalendarIconPal
gCalendarIconPal: @ 0x087F4D18
	.incbin "build/assets/gfx__bank_b.bin", 0x37270, 0xC0
	.global gCalendarIconTiles
gCalendarIconTiles: @ 0x087F4DD8
	.incbin "build/assets/gfx__bank_b.bin", 0x37330, 0x1000
	.global gCalendarMonthNamePal
gCalendarMonthNamePal: @ 0x087F5DD8
	.incbin "build/assets/gfx__bank_b.bin", 0x38330, 0x20
	.global gCalendarMonthNameTiles
gCalendarMonthNameTiles: @ 0x087F5DF8
	.incbin "build/assets/gfx__bank_b.bin", 0x38350, 0x2000
	.global gCalendarWeekdayPal
gCalendarWeekdayPal: @ 0x087F7DF8
	.incbin "build/assets/gfx__bank_b.bin", 0x3A350, 0x20
	.global gCalendarWeekdayTiles
gCalendarWeekdayTiles: @ 0x087F7E18
	.incbin "build/assets/gfx__bank_b.bin", 0x3A370, 0x750
@ padding_end (zero)
	.space 0x7A98
