/*
 * emuh: headless libmgba harness for tools/emu.py (EDS decomp dynamic analysis).
 *
 * Usage: emuh JOBFILE
 *
 * The job file is generated by tools/emu.py; one directive per line, '#' starts a comment.
 * Frame numbers count frames emulated in this job (0 = the boot or the loaded state). Actions
 * scheduled at frame F happen after F frames have run; "keys" for frame F are held while frame F runs.
 * The frame token "end" means after the last frame.
 *
 *   rom PATH                     ROM image to load (required)
 *   sram PATH                    initial SRAM image (read into memory; never written back)
 *   state PATH                   load this savestate before frame 0 (restores SRAM too)
 *   idle ignore|remove|detect    mGBA idle-loop optimisation (default ignore = exact)
 *   frames N                     number of frames to run
 *   keys FIRST LAST MASK         hold MASK (GBA KEYINPUT bit order) for frames FIRST..LAST
 *   shot FRAME PATH              PNG screenshot
 *   dump FRAME ADDR LEN PATH     raw memory dump (bus view, no side effects)
 *   dumpsram FRAME PATH          raw SRAM contents
 *   savestate FRAME PATH         mGBA savestate (includes SRAM)
 *   alias RAM LEN ROM            code at RAM..RAM+LEN is a copy of ROM (map PCs back to ROM)
 *   funcs PATH                   function start addresses (one per line); enables per-instruction probing
 *   trace OUT                    write per-function entry counts (hits, first/last frame, frames active)
 *   tracefrom FRAME              only probe from this frame on (earlier frames run at full speed)
 *   calls OUT                    record (return address, function) call edges
 *   stack                        keep a shadow call stack; watch/break events get a backtrace column
 *   break ADDR                   log every execution of ADDR with registers
 *   breakout PATH / breakmax N   break log path / maximum logged hits (counting continues)
 *   deref REG LEN                with break: also dump LEN bytes at register REG (0..15)
 *   stopat ADDR COUNT            finish the frame in which ADDR executed for the COUNT-th time, then stop
 *   until ADDR SIZE OP VALUE N   stop after the frame in which [ADDR] (SIZE 1/2/4 bytes) OP VALUE becomes true
 *                                for the N-th time (OP is eq or ne; checked at the end of every frame)
 *   settle N                     with stopat/until: release all keys and run N more frames before stopping
 *   watch ADDR LEN r|w|rw        watch memory accesses overlapping ADDR..ADDR+LEN
 *   watchout PATH / watchmax N / watchsum PATH
 *   watchchanges                 log only writes that change the value (counting and the summary see all)
 *   lua PATH                     run an mGBA 0.10 Lua script (callbacks "frame", "keysRead")
 *   luaout DIR                   value of the Lua global OUTDIR
 *   gdb PORT                     run the mGBA GDB stub on 127.0.0.1:PORT instead of the frame loop
 *   info PATH                    write a JSON summary of the run
 */
#include <mgba/flags.h>
#include <mgba/core/core.h>
#include <mgba/core/config.h>
#include <mgba/core/interface.h>
#include <mgba/core/log.h>
#include <mgba/core/serialize.h>
#include <mgba/core/timing.h>
#ifdef ENABLE_SCRIPTING
#include <mgba/core/scripting.h>
#include <mgba/script/context.h>
#include <mgba/script/types.h>
#include <mgba/internal/script/lua.h>
#endif
#include <mgba/debugger/debugger.h>
#ifdef USE_GDB_STUB
#include <mgba/internal/debugger/gdb-stub.h>
#endif
#include <mgba/internal/arm/arm.h>
#include <mgba/internal/gba/gba.h>
#include <mgba/internal/gba/video.h>
#include <mgba-util/vfs.h>

#include <errno.h>
#include <fcntl.h>
#include <stdarg.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>

#define END_FRAME 0xFFFFFFFFu

static void die(const char* fmt, ...) {
	va_list ap;
	va_start(ap, fmt);
	fputs("emuh: ", stderr);
	vfprintf(stderr, fmt, ap);
	fputc('\n', stderr);
	va_end(ap);
	exit(2);
}

static void* xcalloc(size_t n, size_t s) {
	void* p = calloc(n ? n : 1, s ? s : 1);
	if (!p) {
		die("out of memory");
	}
	return p;
}

static char* xstrdup(const char* s) {
	char* p = strdup(s);
	if (!p) {
		die("out of memory");
	}
	return p;
}

/* ---------------------------------------------------------------- logging */

static int g_quiet_levels = mLOG_DEBUG | mLOG_STUB | mLOG_INFO | mLOG_GAME_ERROR;

static void harness_log(struct mLogger* logger, int category, enum mLogLevel level, const char* format, va_list args) {
	(void) logger;
	const char* name = mLogCategoryId(category);
	bool script = name && (strcmp(name, "script") == 0);
	if (!script && (level & g_quiet_levels)) {
		return;
	}
	if (script) {
		fputs("[lua] ", stdout);
		vfprintf(stdout, format, args);
		fputc('\n', stdout);
		fflush(stdout);
		return;
	}
	fprintf(stderr, "[mgba %s] ", name ? name : "?");
	vfprintf(stderr, format, args);
	fputc('\n', stderr);
}

static struct mLogger g_logger = { .log = harness_log, .filter = NULL };

/* ---------------------------------------------------------------- job */

struct action {
	uint32_t frame;
	enum { ACT_SHOT, ACT_DUMP, ACT_DUMPSRAM, ACT_SAVESTATE } kind;
	uint32_t addr, len;
	char* path;
};

struct keyrange {
	uint32_t first, last;
	uint16_t mask;
};

struct alias {
	uint32_t ram, len, rom;
};

struct probe {
	uint32_t addr;
	uint32_t flags; /* PROBE_* */
	int func;       /* index into funcs, or -1 */
	uint32_t stopCount, stopHits;
};
#define PROBE_FUNC 1
#define PROBE_BREAK 2
#define PROBE_STOP 4

struct funcstat {
	uint32_t addr;
	uint64_t hits;
	uint32_t first, last, framesActive;
};

struct watch {
	uint32_t lo, hi; /* [lo, hi) */
	int mode;        /* 1 = read, 2 = write */
};

struct deref {
	int reg;
	uint32_t len;
};

static struct {
	char* rom;
	char* sram;
	char* state;
	char* idle;
	uint32_t frames;
	struct action* actions;
	size_t nActions;
	struct keyrange* keys;
	size_t nKeys;
	struct alias aliases[16];
	size_t nAliases;
	char* traceFuncs;
	char* traceOut;
	bool stack;
	uint32_t traceFrom;
	char* callsOut;
	uint32_t* breaks;
	size_t nBreaks;
	char* breakOut;
	uint64_t breakMax;
	struct deref derefs[8];
	size_t nDerefs;
	uint32_t stopAddr[16], stopCount[16];
	size_t nStops;
	uint32_t settle;
	uint32_t untilAddr, untilSize, untilValue, untilCount;
	int untilOp; /* 0 = none, 1 = eq, 2 = ne */
	struct watch watches[64];
	size_t nWatches;
	char* watchOut;
	char* watchSum;
	uint64_t watchMax;
	bool watchChanges;
	char* lua;
	char* luaOut;
	int gdbPort;
	char* info;
} job;

static uint32_t parse_u32(const char* s, const char* what) {
	if (!s) {
		die("missing %s", what);
	}
	if (strcmp(s, "end") == 0) {
		return END_FRAME;
	}
	char* end;
	errno = 0;
	unsigned long v = strtoul(s, &end, 0);
	if (errno || *end) {
		die("bad number for %s: %s", what, s);
	}
	return (uint32_t) v;
}

#define PUSH(arr, n, item) do { \
	arr = realloc(arr, sizeof(*(arr)) * ((n) + 1)); \
	if (!(arr)) die("out of memory"); \
	(arr)[(n)++] = (item); \
} while (0)

static void parse_job(const char* path) {
	FILE* f = fopen(path, "r");
	if (!f) {
		die("cannot open job %s: %s", path, strerror(errno));
	}
	job.idle = xstrdup("ignore");
	job.breakMax = 100000;
	job.watchMax = 100000;
	char line[4096];
	int lineno = 0;
	while (fgets(line, sizeof(line), f)) {
		++lineno;
		char* hash = strchr(line, '#');
		if (hash) {
			*hash = 0;
		}
		char* tok[8] = {0};
		int n = 0;
		for (char* t = strtok(line, " \t\r\n"); t && n < 8; t = strtok(NULL, " \t\r\n")) {
			tok[n++] = t;
		}
		if (!n) {
			continue;
		}
		const char* d = tok[0];
		if (!strcmp(d, "rom") && n == 2) {
			job.rom = xstrdup(tok[1]);
		} else if (!strcmp(d, "sram") && n == 2) {
			job.sram = xstrdup(tok[1]);
		} else if (!strcmp(d, "state") && n == 2) {
			job.state = xstrdup(tok[1]);
		} else if (!strcmp(d, "idle") && n == 2) {
			free(job.idle);
			job.idle = xstrdup(tok[1]);
		} else if (!strcmp(d, "frames") && n == 2) {
			job.frames = parse_u32(tok[1], "frames");
		} else if (!strcmp(d, "keys") && n == 4) {
			struct keyrange k = { parse_u32(tok[1], "first"), parse_u32(tok[2], "last"), (uint16_t) parse_u32(tok[3], "mask") };
			PUSH(job.keys, job.nKeys, k);
		} else if (!strcmp(d, "shot") && n == 3) {
			struct action a = { parse_u32(tok[1], "frame"), ACT_SHOT, 0, 0, xstrdup(tok[2]) };
			PUSH(job.actions, job.nActions, a);
		} else if (!strcmp(d, "dump") && n == 5) {
			struct action a = { parse_u32(tok[1], "frame"), ACT_DUMP, parse_u32(tok[2], "addr"), parse_u32(tok[3], "len"), xstrdup(tok[4]) };
			PUSH(job.actions, job.nActions, a);
		} else if (!strcmp(d, "dumpsram") && n == 3) {
			struct action a = { parse_u32(tok[1], "frame"), ACT_DUMPSRAM, 0, 0, xstrdup(tok[2]) };
			PUSH(job.actions, job.nActions, a);
		} else if (!strcmp(d, "savestate") && n == 3) {
			struct action a = { parse_u32(tok[1], "frame"), ACT_SAVESTATE, 0, 0, xstrdup(tok[2]) };
			PUSH(job.actions, job.nActions, a);
		} else if (!strcmp(d, "alias") && n == 4) {
			if (job.nAliases >= 16) die("too many aliases");
			struct alias a = { parse_u32(tok[1], "ram"), parse_u32(tok[2], "len"), parse_u32(tok[3], "rom") };
			job.aliases[job.nAliases++] = a;
		} else if (!strcmp(d, "funcs") && n == 2) {
			job.traceFuncs = xstrdup(tok[1]);
		} else if (!strcmp(d, "trace") && n == 2) {
			job.traceOut = xstrdup(tok[1]);
		} else if (!strcmp(d, "stack") && n == 1) {
			job.stack = true;
		} else if (!strcmp(d, "tracefrom") && n == 2) {
			job.traceFrom = parse_u32(tok[1], "tracefrom");
		} else if (!strcmp(d, "calls") && n == 2) {
			job.callsOut = xstrdup(tok[1]);
		} else if (!strcmp(d, "break") && n == 2) {
			uint32_t a = parse_u32(tok[1], "break");
			PUSH(job.breaks, job.nBreaks, a);
		} else if (!strcmp(d, "breakout") && n == 2) {
			job.breakOut = xstrdup(tok[1]);
		} else if (!strcmp(d, "breakmax") && n == 2) {
			job.breakMax = parse_u32(tok[1], "breakmax");
		} else if (!strcmp(d, "deref") && n == 3) {
			if (job.nDerefs >= 8) die("too many derefs");
			struct deref r = { (int) parse_u32(tok[1], "reg"), parse_u32(tok[2], "len") };
			if (r.reg < 0 || r.reg > 15 || r.len > 4096) die("bad deref");
			job.derefs[job.nDerefs++] = r;
		} else if (!strcmp(d, "stopat") && n == 3) {
			if (job.nStops >= 16) die("too many stopat");
			job.stopAddr[job.nStops] = parse_u32(tok[1], "addr");
			job.stopCount[job.nStops] = parse_u32(tok[2], "count");
			++job.nStops;
		} else if (!strcmp(d, "until") && n == 6) {
			job.untilAddr = parse_u32(tok[1], "addr");
			job.untilSize = parse_u32(tok[2], "size");
			if (job.untilSize != 1 && job.untilSize != 2 && job.untilSize != 4) die("until size must be 1, 2 or 4");
			job.untilOp = !strcmp(tok[3], "eq") ? 1 : !strcmp(tok[3], "ne") ? 2 : 0;
			if (!job.untilOp) die("until op must be eq or ne");
			job.untilValue = parse_u32(tok[4], "value");
			job.untilCount = parse_u32(tok[5], "count");
		} else if (!strcmp(d, "settle") && n == 2) {
			job.settle = parse_u32(tok[1], "settle");
		} else if (!strcmp(d, "watch") && n == 4) {
			if (job.nWatches >= 64) die("too many watches");
			struct watch w;
			w.lo = parse_u32(tok[1], "addr");
			w.hi = w.lo + parse_u32(tok[2], "len");
			w.mode = (strchr(tok[3], 'r') ? 1 : 0) | (strchr(tok[3], 'w') ? 2 : 0);
			if (!w.mode || w.hi <= w.lo) die("bad watch on line %d", lineno);
			job.watches[job.nWatches++] = w;
		} else if (!strcmp(d, "watchout") && n == 2) {
			job.watchOut = xstrdup(tok[1]);
		} else if (!strcmp(d, "watchsum") && n == 2) {
			job.watchSum = xstrdup(tok[1]);
		} else if (!strcmp(d, "watchchanges") && n == 1) {
			job.watchChanges = true;
		} else if (!strcmp(d, "watchmax") && n == 2) {
			job.watchMax = parse_u32(tok[1], "watchmax");
		} else if (!strcmp(d, "lua") && n == 2) {
			job.lua = xstrdup(tok[1]);
		} else if (!strcmp(d, "luaout") && n == 2) {
			job.luaOut = xstrdup(tok[1]);
		} else if (!strcmp(d, "gdb") && n == 2) {
			job.gdbPort = (int) parse_u32(tok[1], "port");
		} else if (!strcmp(d, "info") && n == 2) {
			job.info = xstrdup(tok[1]);
		} else {
			die("%s:%d: bad directive '%s' (%d args)", path, lineno, d, n - 1);
		}
	}
	fclose(f);
	if (!job.rom) {
		die("job has no rom");
	}
	if ((job.traceOut || job.callsOut || job.stack) && !job.traceFuncs) {
		die("trace/calls/stack need a funcs list");
	}
}

/* ---------------------------------------------------------------- emulator state */

static struct mCore* core;
static struct ARMCore* cpu;
static struct GBA* gba;
static color_t* videoBuffer;
static uint32_t g_frame;          /* frames run in this job */
static bool g_stop;               /* stop requested (stopat / Lua) */
static uint32_t g_stopFrame = END_FRAME; /* with settle: stop when g_frame reaches this */
static bool g_keysOff;            /* settling: no input */
static const char* g_stopReason = "frames";

/* stopat/until fired during frame g_frame: stop after it, or after `settle` more frames without input. */
static void trigger_stop(const char* reason) {
	if (g_stop || g_stopFrame != END_FRAME) {
		return;
	}
	g_stopReason = reason;
	if (job.settle) {
		g_stopFrame = g_frame + 1 + job.settle;
		g_keysOff = true;
	} else {
		g_stop = true;
	}
}

static bool g_untilPrev;
static uint32_t g_untilHits;

static bool until_true(void) {
	uint32_t v;
	switch (job.untilSize) {
	case 1:
		v = core->rawRead8(core, job.untilAddr, -1) & 0xFF;
		break;
	case 2:
		v = core->rawRead16(core, job.untilAddr, -1) & 0xFFFF;
		break;
	default:
		v = core->rawRead32(core, job.untilAddr, -1);
		break;
	}
	return job.untilOp == 1 ? v == job.untilValue : v != job.untilValue;
}

static inline uint32_t map_alias(uint32_t a) {
	for (size_t i = 0; i < job.nAliases; ++i) {
		if (a - job.aliases[i].ram < job.aliases[i].len) {
			return job.aliases[i].rom + (a - job.aliases[i].ram);
		}
	}
	return a;
}

/* Address of the instruction currently executing (valid inside a memory access). */
static inline uint32_t current_pc(void) {
	return cpu->gprs[ARM_PC] - (cpu->executionMode == MODE_THUMB ? 4 : 8);
}

/* ---------------------------------------------------------------- probes (trace / break / stopat) */

#define ROM_BASE 0x08000000u
#define ROM_SPAN 0x02000000u
static uint8_t* g_bitmap;          /* one bit per ROM halfword */
static struct probe* g_probes;     /* sorted by addr */
static size_t g_nProbes;
static struct funcstat* g_funcs;
static size_t g_nFuncs;
static bool g_probing;
static uint64_t g_regionInsns[16];
static FILE* g_breakFile;
static uint64_t g_breakHits, g_breakLogged;

struct edge {
	uint32_t ret;
	int32_t func;
	uint64_t count;
};
static struct edge* g_edges;
static size_t g_edgeCap, g_edgeCount;

/* Shadow call stack (job.stack). A frame is pushed when a known function start executes and popped when
 * execution reaches its return address. Frames left behind by tail calls or other non-returning exits are
 * pruned at the next function entry: any frame in the same CPU mode whose entry SP is <= the new entry SP
 * must have finished (the stack grows down). IRQ handlers run in System mode on the main stack (IntrMain
 * switches mode), so they nest naturally on top of the interrupted code. */
struct sframe {
	uint32_t func, ret, sp;
	uint8_t mode;
};
#define STACK_MAX 256
static struct sframe g_stack[STACK_MAX];
static int g_depth;
static uint32_t g_topRet = 0xFFFFFFFF;

static inline void stack_sync_top(void) {
	g_topRet = g_depth ? g_stack[g_depth - 1].ret : 0xFFFFFFFF;
}

static void stack_enter(uint32_t func) {
	uint32_t sp = cpu->gprs[ARM_SP];
	uint8_t mode = cpu->cpsr.priv;
	while (g_depth && g_stack[g_depth - 1].mode == mode && g_stack[g_depth - 1].sp <= sp) {
		--g_depth;
	}
	if (g_depth == STACK_MAX) {
		memmove(g_stack, g_stack + 1, sizeof(g_stack[0]) * (STACK_MAX - 1));
		--g_depth;
	}
	struct sframe fr = { func, cpu->gprs[ARM_LR] & ~1u, sp, mode };
	g_stack[g_depth++] = fr;
	stack_sync_top();
}

/* Backtrace, innermost first: "0x08001234<0x08005678<...". */
static const char* stack_string(void) {
	static char buf[STACK_MAX * 11 + 1];
	char* p = buf;
	*p = 0;
	for (int i = g_depth - 1; i >= 0 && i >= g_depth - 48; --i) {
		p += sprintf(p, "%s0x%08X", i == g_depth - 1 ? "" : "<", g_stack[i].func);
	}
	return buf;
}

static int cmp_probe(const void* a, const void* b) {
	uint32_t x = ((const struct probe*) a)->addr, y = ((const struct probe*) b)->addr;
	return x < y ? -1 : x > y;
}

static struct probe* add_probe(uint32_t addr, uint32_t flag) {
	addr &= ~1u;
	for (size_t i = 0; i < g_nProbes; ++i) {
		if (g_probes[i].addr == addr) {
			g_probes[i].flags |= flag;
			return &g_probes[i];
		}
	}
	struct probe p = { addr, flag, -1, 0, 0 };
	PUSH(g_probes, g_nProbes, p);
	return &g_probes[g_nProbes - 1];
}

static void setup_probes(void) {
	if (job.traceFuncs) {
		FILE* f = fopen(job.traceFuncs, "r");
		if (!f) die("cannot open %s", job.traceFuncs);
		char line[256];
		while (fgets(line, sizeof(line), f)) {
			char* end;
			unsigned long a = strtoul(line, &end, 0);
			if (end == line) continue;
			struct funcstat fs = { (uint32_t) a & ~1u, 0, END_FRAME, 0, 0 };
			PUSH(g_funcs, g_nFuncs, fs);
		}
		fclose(f);
		for (size_t i = 0; i < g_nFuncs; ++i) {
			add_probe(g_funcs[i].addr, PROBE_FUNC);
		}
	}
	for (size_t i = 0; i < job.nBreaks; ++i) {
		add_probe(job.breaks[i], PROBE_BREAK);
	}
	for (size_t i = 0; i < job.nStops; ++i) {
		struct probe* p = add_probe(job.stopAddr[i], PROBE_STOP);
		p->stopCount = job.stopCount[i] ? job.stopCount[i] : 1;
	}
	if (!g_nProbes) {
		return;
	}
	qsort(g_probes, g_nProbes, sizeof(*g_probes), cmp_probe);
	for (size_t i = 0; i < g_nProbes; ++i) {
		g_probes[i].func = -1;
		if (g_probes[i].flags & PROBE_FUNC) {
			for (size_t j = 0; j < g_nFuncs; ++j) {
				if (g_funcs[j].addr == g_probes[i].addr) {
					g_probes[i].func = (int) j;
					break;
				}
			}
		}
	}
	g_bitmap = xcalloc(ROM_SPAN / 16, 1);
	for (size_t i = 0; i < g_nProbes; ++i) {
		uint32_t a = g_probes[i].addr;
		if (a - ROM_BASE < ROM_SPAN) {
			uint32_t h = (a - ROM_BASE) >> 1;
			g_bitmap[h >> 3] |= 1 << (h & 7);
		}
	}
	if (job.nBreaks) {
		g_breakFile = fopen(job.breakOut ? job.breakOut : "break.tsv", "w");
		if (!g_breakFile) die("cannot write break log");
		fprintf(g_breakFile, "frame\tpc\tlr\tsp\tr0\tr1\tr2\tr3\tr4\tr5\tr6\tr7\tr8\tr9\tr10\tr11\tr12\tcpsr\tstack");
		for (size_t i = 0; i < job.nDerefs; ++i) {
			fprintf(g_breakFile, "\t[r%d]", job.derefs[i].reg);
		}
		fputc('\n', g_breakFile);
	}
	g_probing = true;
}

static struct probe* find_probe(uint32_t addr) {
	size_t lo = 0, hi = g_nProbes;
	while (lo < hi) {
		size_t mid = (lo + hi) / 2;
		if (g_probes[mid].addr < addr) {
			lo = mid + 1;
		} else {
			hi = mid;
		}
	}
	return (lo < g_nProbes && g_probes[lo].addr == addr) ? &g_probes[lo] : NULL;
}

static void add_edge(uint32_t ret, int32_t func) {
	if (g_edgeCount * 2 >= g_edgeCap) {
		size_t oldCap = g_edgeCap;
		struct edge* old = g_edges;
		g_edgeCap = oldCap ? oldCap * 2 : 4096;
		g_edges = xcalloc(g_edgeCap, sizeof(*g_edges));
		g_edgeCount = 0;
		for (size_t i = 0; i < oldCap; ++i) {
			if (old[i].count) {
				size_t h = ((old[i].ret * 2654435761u) ^ (uint32_t) old[i].func * 40503u) & (g_edgeCap - 1);
				while (g_edges[h].count) h = (h + 1) & (g_edgeCap - 1);
				g_edges[h] = old[i];
				++g_edgeCount;
			}
		}
		free(old);
	}
	size_t h = ((ret * 2654435761u) ^ (uint32_t) func * 40503u) & (g_edgeCap - 1);
	while (g_edges[h].count && !(g_edges[h].ret == ret && g_edges[h].func == func)) {
		h = (h + 1) & (g_edgeCap - 1);
	}
	if (!g_edges[h].count) {
		g_edges[h].ret = ret;
		g_edges[h].func = func;
		++g_edgeCount;
	}
	++g_edges[h].count;
}

static void on_probe(struct probe* p, uint32_t pc) {
	if ((p->flags & PROBE_FUNC) && job.stack) {
		stack_enter(p->addr);
	}
	if (p->func >= 0) {
		struct funcstat* fs = &g_funcs[p->func];
		if (!fs->hits) {
			fs->first = g_frame;
		}
		if (fs->last != g_frame || !fs->hits) {
			++fs->framesActive;
		}
		fs->last = g_frame;
		++fs->hits;
		if (job.callsOut) {
			add_edge(map_alias(cpu->gprs[ARM_LR] & ~1u), p->func);
		}
	}
	if (p->flags & PROBE_BREAK) {
		++g_breakHits;
		if (g_breakLogged < job.breakMax) {
			++g_breakLogged;
			FILE* f = g_breakFile;
			fprintf(f, "%u\t0x%08X\t0x%08X\t0x%08X", g_frame, pc, cpu->gprs[ARM_LR], cpu->gprs[ARM_SP]);
			for (int r = 0; r <= 12; ++r) {
				fprintf(f, "\t0x%08X", cpu->gprs[r]);
			}
			fprintf(f, "\t0x%08X\t%s", cpu->cpsr.packed, job.stack ? stack_string() : "");
			for (size_t i = 0; i < job.nDerefs; ++i) {
				uint32_t base = cpu->gprs[job.derefs[i].reg];
				fputc('\t', f);
				for (uint32_t k = 0; k < job.derefs[i].len; ++k) {
					fprintf(f, "%02X", core->rawRead8(core, base + k, -1) & 0xFF);
				}
			}
			fputc('\n', f);
		}
	}
	if (p->flags & PROBE_STOP) {
		if (++p->stopHits == p->stopCount) {
			trigger_stop("stopat");
		}
	}
}

/* One frame, checking every instruction against the probe table before it executes.
 * Mirrors _GBACoreRunFrame / ARMRunLoop exactly, so emulation is identical to a plain run. */
static void run_frame_probed(void) {
	uint32_t frameCounter = gba->video.frameCounter;
	uint32_t startCycle = mTimingCurrentTime(&gba->timing);
	while (gba->video.frameCounter == frameCounter && mTimingCurrentTime(&gba->timing) - startCycle < VIDEO_TOTAL_LENGTH + VIDEO_HORIZONTAL_LENGTH) {
		while (cpu->cycles < cpu->nextEvent) {
			uint32_t pc = cpu->gprs[ARM_PC] - (cpu->executionMode == MODE_THUMB ? 2 : 4);
			++g_regionInsns[(pc >> 24) & 0xF];
			while (pc == g_topRet) {
				--g_depth;
				stack_sync_top();
			}
			uint32_t off = pc - ROM_BASE;
			if (off < ROM_SPAN) {
				uint32_t h = off >> 1;
				if (g_bitmap[h >> 3] & (1 << (h & 7))) {
					struct probe* p = find_probe(pc);
					if (p) on_probe(p, pc);
				}
			} else if (job.nAliases) {
				uint32_t m = map_alias(pc);
				if (m != pc && m - ROM_BASE < ROM_SPAN) {
					uint32_t h = (m - ROM_BASE) >> 1;
					if (g_bitmap[h >> 3] & (1 << (h & 7))) {
						struct probe* p = find_probe(m);
						if (p) on_probe(p, m);
					}
				}
			}
			ARMRun(cpu); /* no pending events here, so this executes exactly one instruction */
		}
		cpu->irqh.processEvents(cpu);
	}
}

/* ---------------------------------------------------------------- watchpoints (memory shim) */

static struct ARMMemory g_origMem;
static FILE* g_watchFile;
static uint64_t g_watchEvents, g_watchLogged;
static uint32_t g_dmaTriggerPc[4];
static char g_dmaTriggerStack[4][48 * 11 + 1];
static uint32_t g_swiPc;
static void (*g_origSwi16)(struct ARMCore*, int);
static void (*g_origSwi32)(struct ARMCore*, int);

struct wsum {
	uint32_t pc;
	uint16_t kind; /* access size | (write ? 0x100 : 0) | via<<12 */
	uint32_t first, last;
	uint64_t count;
	uint32_t lastValue;
	char* firstStack;
};
static struct wsum* g_wsum;
static size_t g_wsumCap, g_wsumCount;

static void wsum_add(uint32_t pc, uint16_t kind, uint32_t value) {
	if (g_wsumCount * 2 >= g_wsumCap) {
		size_t oldCap = g_wsumCap;
		struct wsum* old = g_wsum;
		g_wsumCap = oldCap ? oldCap * 2 : 1024;
		g_wsum = xcalloc(g_wsumCap, sizeof(*g_wsum));
		g_wsumCount = 0;
		for (size_t i = 0; i < oldCap; ++i) {
			if (old[i].count) {
				size_t h = ((old[i].pc * 2654435761u) ^ old[i].kind) & (g_wsumCap - 1);
				while (g_wsum[h].count) h = (h + 1) & (g_wsumCap - 1);
				g_wsum[h] = old[i];
				++g_wsumCount;
			}
		}
		free(old);
	}
	size_t h = ((pc * 2654435761u) ^ kind) & (g_wsumCap - 1);
	while (g_wsum[h].count && !(g_wsum[h].pc == pc && g_wsum[h].kind == kind)) {
		h = (h + 1) & (g_wsumCap - 1);
	}
	if (!g_wsum[h].count) {
		g_wsum[h].pc = pc;
		g_wsum[h].kind = kind;
		g_wsum[h].first = g_frame;
		g_wsum[h].firstStack = !job.stack ? NULL : xstrdup((kind >> 12) ? g_dmaTriggerStack[(kind >> 12) - 1] : stack_string());
		++g_wsumCount;
	}
	g_wsum[h].last = g_frame;
	g_wsum[h].lastValue = value;
	++g_wsum[h].count;
}

static inline bool watched(uint32_t addr, uint32_t size, int mode) {
	for (size_t i = 0; i < job.nWatches; ++i) {
		const struct watch* w = &job.watches[i];
		if ((w->mode & mode) && addr < w->hi && addr + size > w->lo) {
			return true;
		}
	}
	return false;
}

static uint32_t raw_read(uint32_t addr, int size) {
	switch (size) {
	case 1:
		return core->rawRead8(core, addr, -1) & 0xFF;
	case 2:
		return core->rawRead16(core, addr & ~1u, -1) & 0xFFFF;
	default:
		return core->rawRead32(core, addr & ~3u, -1);
	}
}

static void log_access(bool write, int size, uint32_t addr, uint32_t oldv, uint32_t newv, bool multi) {
	int via = gba->performingDMA ? 1 + ((gba->performingDMA >> 1) & 3) : 0;
	uint32_t pc, ctx = 0;
	if (via) {
		pc = g_dmaTriggerPc[via - 1];
	} else {
		pc = map_alias(current_pc());
		if (pc < 0x4000) {
			ctx = g_swiPc; /* inside a BIOS call: remember who called it */
		}
	}
	++g_watchEvents;
	uint16_t kind = (uint16_t) (size | (write ? 0x100 : 0) | (via << 12));
	wsum_add(pc, kind, newv);
	if (g_watchLogged >= job.watchMax || (job.watchChanges && (!write || oldv == newv))) {
		return;
	}
	++g_watchLogged;
	static const char* const vias[] = { "cpu", "dma0", "dma1", "dma2", "dma3" };
	fprintf(g_watchFile, "%u\t0x%08X\t0x%08X\t%s\t%s%d%s\t0x%08X\t0x%0*X\t0x%0*X\t0x%08X\t%s\n", g_frame, pc,
	        via ? 0 : map_alias(cpu->gprs[ARM_LR]), vias[via], write ? "w" : "r", size * 8, multi ? "m" : "", addr,
	        size * 2, oldv, size * 2, newv, ctx, !job.stack ? "" : via ? g_dmaTriggerStack[via - 1] : stack_string());
}

static void note_dma_reg_write(uint32_t addr, uint32_t size) {
	/* DMAxCNT_H lives at 0x040000BA + 12*x; remember who started each channel */
	for (int ch = 0; ch < 4; ++ch) {
		uint32_t cnt = 0x040000BA + 12 * ch;
		if (addr <= cnt && addr + size > cnt) {
			g_dmaTriggerPc[ch] = map_alias(current_pc());
			if (job.stack) {
				snprintf(g_dmaTriggerStack[ch], sizeof(g_dmaTriggerStack[ch]), "%s", stack_string());
			}
		}
	}
}

static uint32_t w_load32(struct ARMCore* c, uint32_t a, int* cc) {
	uint32_t v = g_origMem.load32(c, a, cc);
	if (watched(a & ~3u, 4, 1)) log_access(false, 4, a & ~3u, v, v, false);
	return v;
}
static uint32_t w_load16(struct ARMCore* c, uint32_t a, int* cc) {
	uint32_t v = g_origMem.load16(c, a, cc);
	if (watched(a & ~1u, 2, 1)) log_access(false, 2, a & ~1u, v & 0xFFFF, v & 0xFFFF, false);
	return v;
}
static uint32_t w_load8(struct ARMCore* c, uint32_t a, int* cc) {
	uint32_t v = g_origMem.load8(c, a, cc);
	if (watched(a, 1, 1)) log_access(false, 1, a, v & 0xFF, v & 0xFF, false);
	return v;
}
static void w_store32(struct ARMCore* c, uint32_t a, int32_t v, int* cc) {
	if ((a >> 24) == 4) note_dma_reg_write(a & ~3u, 4);
	if (watched(a & ~3u, 4, 2)) {
		uint32_t old = raw_read(a, 4);
		g_origMem.store32(c, a, v, cc);
		log_access(true, 4, a & ~3u, old, raw_read(a, 4), false);
	} else {
		g_origMem.store32(c, a, v, cc);
	}
}
static void w_store16(struct ARMCore* c, uint32_t a, int16_t v, int* cc) {
	if ((a >> 24) == 4) note_dma_reg_write(a & ~1u, 2);
	if (watched(a & ~1u, 2, 2)) {
		uint32_t old = raw_read(a, 2);
		g_origMem.store16(c, a, v, cc);
		log_access(true, 2, a & ~1u, old, raw_read(a, 2), false);
	} else {
		g_origMem.store16(c, a, v, cc);
	}
}
static void w_store8(struct ARMCore* c, uint32_t a, int8_t v, int* cc) {
	if (watched(a, 1, 2)) {
		uint32_t old = raw_read(a, 1);
		g_origMem.store8(c, a, v, cc);
		log_access(true, 1, a, old, raw_read(a, 1), false);
	} else {
		g_origMem.store8(c, a, v, cc);
	}
}

static uint32_t lsm_start(uint32_t base, int mask, enum LSMDirection dir, int* count) {
	int n = __builtin_popcount(mask & 0xFFFF);
	if (dir & LSM_D) {
		base -= (n << 2) - 4;
		if (dir & LSM_B) base -= 4;
	} else if (dir & LSM_B) {
		base += 4;
	}
	*count = n;
	return base & ~3u;
}

static uint32_t w_loadMultiple(struct ARMCore* c, uint32_t base, int mask, enum LSMDirection dir, int* cc) {
	int n;
	uint32_t start = lsm_start(base, mask, dir, &n);
	uint32_t r = g_origMem.loadMultiple(c, base, mask, dir, cc);
	if (n && watched(start, 4 * n, 1)) {
		for (int i = 0; i < n; ++i) {
			uint32_t a = start + 4 * i;
			if (watched(a, 4, 1)) {
				uint32_t v = raw_read(a, 4);
				log_access(false, 4, a, v, v, true);
			}
		}
	}
	return r;
}
static uint32_t w_storeMultiple(struct ARMCore* c, uint32_t base, int mask, enum LSMDirection dir, int* cc) {
	int n;
	uint32_t start = lsm_start(base, mask, dir, &n);
	if (n && watched(start, 4 * n, 2)) {
		uint32_t old[16];
		for (int i = 0; i < n; ++i) old[i] = raw_read(start + 4 * i, 4);
		uint32_t r = g_origMem.storeMultiple(c, base, mask, dir, cc);
		for (int i = 0; i < n; ++i) {
			uint32_t a = start + 4 * i;
			if (watched(a, 4, 2)) log_access(true, 4, a, old[i], raw_read(a, 4), true);
		}
		return r;
	}
	return g_origMem.storeMultiple(c, base, mask, dir, cc);
}

static void w_swi16(struct ARMCore* c, int imm) {
	g_swiPc = map_alias(c->gprs[ARM_PC] - 4);
	g_origSwi16(c, imm);
}
static void w_swi32(struct ARMCore* c, int imm) {
	g_swiPc = map_alias(c->gprs[ARM_PC] - 8);
	g_origSwi32(c, imm);
}

static void setup_watch(void) {
	if (!job.nWatches) return;
	g_watchFile = fopen(job.watchOut ? job.watchOut : "watch.tsv", "w");
	if (!g_watchFile) die("cannot write watch log");
	fprintf(g_watchFile, "frame\tpc\tlr\tvia\taccess\taddr\told\tnew\tswi_caller\tstack\n");
	g_origMem = cpu->memory;
	cpu->memory.load32 = w_load32;
	cpu->memory.load16 = w_load16;
	cpu->memory.load8 = w_load8;
	cpu->memory.store32 = w_store32;
	cpu->memory.store16 = w_store16;
	cpu->memory.store8 = w_store8;
	cpu->memory.loadMultiple = w_loadMultiple;
	cpu->memory.storeMultiple = w_storeMultiple;
	g_origSwi16 = cpu->irqh.swi16;
	g_origSwi32 = cpu->irqh.swi32;
	cpu->irqh.swi16 = w_swi16;
	cpu->irqh.swi32 = w_swi32;
}

/* ---------------------------------------------------------------- Lua */

#ifdef ENABLE_SCRIPTING
static struct mScriptContext g_script;
static struct mScriptEngineContext* g_lua;
static bool g_luaActive;

static void lua_frame_cb(void* ctx) {
	(void) ctx;
	mScriptContextTriggerCallback(&g_script, "frame");
}
static void lua_keys_cb(void* ctx) {
	(void) ctx;
	mScriptContextTriggerCallback(&g_script, "keysRead");
}

static void setup_lua(void) {
	if (!job.lua) return;
	mScriptContextInit(&g_script);
	mScriptContextAttachStdlib(&g_script);
	g_lua = mScriptContextRegisterEngine(&g_script, mSCRIPT_ENGINE_LUA);
	mScriptContextAttachCore(&g_script, core);
	mScriptContextAttachLogger(&g_script, &g_logger);
	if (job.luaOut) {
		struct mScriptValue* v = mScriptStringCreateFromUTF8(job.luaOut);
		g_lua->setGlobal(g_lua, "OUTDIR", v);
		mScriptValueDeref(v);
	}
	struct VFile* vf = VFileOpen(job.lua, O_RDONLY);
	if (!vf) die("cannot open Lua script %s", job.lua);
	bool ok = g_lua->load(g_lua, job.lua, vf);
	vf->close(vf);
	if (!ok) die("Lua load failed: %s", g_lua->getError(g_lua) ? g_lua->getError(g_lua) : "?");
	struct mCoreCallbacks cbs = { 0 };
	cbs.videoFrameEnded = lua_frame_cb;
	cbs.keysRead = lua_keys_cb;
	core->addCoreCallbacks(core, &cbs);
	if (!g_lua->run(g_lua)) die("Lua run failed: %s", g_lua->getError(g_lua) ? g_lua->getError(g_lua) : "?");
	g_luaActive = true;
}

static bool lua_wants_stop(void) {
	if (!g_luaActive) return false;
	struct mScriptValue* v = g_lua->getGlobal(g_lua, "EMU_STOP");
	if (!v) return false;
	bool stop = false;
	switch (v->type->base) {
	case mSCRIPT_TYPE_SINT:
	case mSCRIPT_TYPE_UINT:
		stop = v->type->size > 4 ? v->value.u64 != 0 : v->value.u32 != 0;
		break;
	case mSCRIPT_TYPE_FLOAT:
		stop = v->type->size > 4 ? v->value.f64 != 0 : v->value.f32 != 0;
		break;
	default:
		break;
	}
	mScriptValueDeref(v);
	return stop;
}
#else
static void setup_lua(void) {
	if (job.lua) die("built without scripting");
}
static bool lua_wants_stop(void) {
	return false;
}
#endif

/* ---------------------------------------------------------------- actions */

static void write_file(const char* path, const void* data, size_t len) {
	FILE* f = fopen(path, "wb");
	if (!f) die("cannot write %s: %s", path, strerror(errno));
	if (len && fwrite(data, 1, len, f) != len) die("short write %s", path);
	fclose(f);
}

static void do_action(const struct action* a) {
	switch (a->kind) {
	case ACT_SHOT: {
		struct VFile* vf = VFileOpen(a->path, O_CREAT | O_TRUNC | O_WRONLY);
		if (!vf || !mCoreTakeScreenshotVF(core, vf)) die("screenshot %s failed", a->path);
		vf->close(vf);
		break;
	}
	case ACT_DUMP: {
		uint8_t* buf = xcalloc(a->len, 1);
		uint32_t i = 0;
		for (; i + 4 <= a->len && !((a->addr + i) & 3); i += 4) {
			uint32_t v = core->rawRead32(core, a->addr + i, -1);
			memcpy(buf + i, &v, 4);
		}
		for (; i < a->len; ++i) {
			buf[i] = core->rawRead8(core, a->addr + i, -1);
		}
		write_file(a->path, buf, a->len);
		free(buf);
		break;
	}
	case ACT_DUMPSRAM: {
		void* sram = NULL;
		size_t size = core->savedataClone(core, &sram);
		write_file(a->path, sram, size);
		free(sram);
		break;
	}
	case ACT_SAVESTATE: {
		/* O_RDWR: mGBA mmaps raw state files for writing. SAVESTATE_SCREENSHOT makes the file a PNG of the
		 * current frame with the state embedded, and lets a load restore the picture. No
		 * SAVESTATE_METADATA, so a state is a pure function of the emulated machine (same run, same bytes). */
		struct VFile* vf = VFileOpen(a->path, O_CREAT | O_TRUNC | O_RDWR);
		if (!vf || !mCoreSaveStateNamed(core, vf, SAVESTATE_SAVEDATA | SAVESTATE_RTC | SAVESTATE_SCREENSHOT)) {
			die("savestate %s failed", a->path);
		}
		vf->close(vf);
		break;
	}
	}
}

static void do_actions(uint32_t frame) {
	for (size_t i = 0; i < job.nActions; ++i) {
		if (job.actions[i].frame == frame) do_action(&job.actions[i]);
	}
}

static uint16_t keys_for(uint32_t frame) {
	uint16_t m = 0;
	for (size_t i = 0; i < job.nKeys; ++i) {
		if (frame >= job.keys[i].first && frame <= job.keys[i].last) m |= job.keys[i].mask;
	}
	return m;
}

/* ---------------------------------------------------------------- outputs */

static void write_trace(void) {
	if (!job.traceOut) return;
	FILE* f = fopen(job.traceOut, "w");
	if (!f) die("cannot write %s", job.traceOut);
	fprintf(f, "addr\thits\tfirst_frame\tlast_frame\tframes_active\n");
	for (size_t i = 0; i < g_nFuncs; ++i) {
		const struct funcstat* fs = &g_funcs[i];
		if (!fs->hits) continue;
		fprintf(f, "0x%08X\t%llu\t%u\t%u\t%u\n", fs->addr, (unsigned long long) fs->hits, fs->first, fs->last, fs->framesActive);
	}
	fclose(f);
	if (job.callsOut) {
		f = fopen(job.callsOut, "w");
		if (!f) die("cannot write %s", job.callsOut);
		fprintf(f, "callee\treturn_addr\tcount\n");
		for (size_t i = 0; i < g_edgeCap; ++i) {
			if (g_edges[i].count) {
				fprintf(f, "0x%08X\t0x%08X\t%llu\n", g_funcs[g_edges[i].func].addr, g_edges[i].ret, (unsigned long long) g_edges[i].count);
			}
		}
		fclose(f);
	}
}

static void write_watch_summary(void) {
	if (!job.nWatches) return;
	fclose(g_watchFile);
	FILE* f = fopen(job.watchSum ? job.watchSum : "watch_summary.tsv", "w");
	if (!f) die("cannot write watch summary");
	fprintf(f, "pc\tvia\taccess\tcount\tfirst_frame\tlast_frame\tlast_value\tfirst_stack\n");
	static const char* const vias[] = { "cpu", "dma0", "dma1", "dma2", "dma3" };
	for (size_t i = 0; i < g_wsumCap; ++i) {
		const struct wsum* s = &g_wsum[i];
		if (!s->count) continue;
		fprintf(f, "0x%08X\t%s\t%s%d\t%llu\t%u\t%u\t0x%X\t%s\n", s->pc, vias[(s->kind >> 12) & 7], (s->kind & 0x100) ? "w" : "r",
		        (s->kind & 0xFF) * 8, (unsigned long long) s->count, s->first, s->last, s->lastValue,
		        s->firstStack ? s->firstStack : "");
	}
	fclose(f);
}

static void write_info(double seconds, uint32_t fc0) {
	if (!job.info) return;
	FILE* f = fopen(job.info, "w");
	if (!f) die("cannot write %s", job.info);
	fprintf(f, "{\n  \"frames_run\": %u,\n  \"stop_reason\": \"%s\",\n", g_frame, g_stopReason);
	fprintf(f, "  \"frame_counter_start\": %u,\n  \"frame_counter_end\": %u,\n", fc0, gba->video.frameCounter);
	fprintf(f, "  \"rom_crc32\": \"%08X\",\n  \"seconds\": %.3f,\n", gba->romCrc32, seconds);
	fprintf(f, "  \"probing\": %s,\n", g_probing ? "true" : "false");
	if (g_probing) {
		static const char* const names[16] = { "bios", "1", "ewram", "iwram", "io", "pal", "vram", "oam", "rom", "rom_mirror9",
			                                    "a", "b", "c", "d", "sram", "f" };
		fprintf(f, "  \"instructions\": {");
		bool firstOut = true;
		for (int i = 0; i < 16; ++i) {
			if (!g_regionInsns[i]) continue;
			fprintf(f, "%s\"%s\": %llu", firstOut ? "" : ", ", names[i], (unsigned long long) g_regionInsns[i]);
			firstOut = false;
		}
		fprintf(f, "},\n");
		fprintf(f, "  \"break_hits\": %llu,\n  \"break_logged\": %llu,\n", (unsigned long long) g_breakHits, (unsigned long long) g_breakLogged);
	}
	fprintf(f, "  \"watch_events\": %llu,\n  \"watch_logged\": %llu\n}\n", (unsigned long long) g_watchEvents, (unsigned long long) g_watchLogged);
	fclose(f);
}

/* ---------------------------------------------------------------- main */

int main(int argc, char** argv) {
	if (argc != 2) {
		fprintf(stderr, "usage: %s JOBFILE\n", argv[0]);
		return 2;
	}
	parse_job(argv[1]);
	mLogSetDefaultLogger(&g_logger);

	core = mCoreFind(job.rom);
	if (!core) die("not a ROM mGBA recognises: %s", job.rom);
	if (core->platform(core) != mPLATFORM_GBA) die("not a GBA ROM: %s", job.rom);
	core->init(core);
	mCoreInitConfig(core, NULL);
	mCoreConfigSetValue(&core->config, "idleOptimization", job.idle);
	mCoreConfigSetIntValue(&core->config, "useBios", 0);
	core->opts.useBios = false;
	core->opts.skipBios = true;
	core->loadConfig(core, &core->config);

	unsigned w, h;
	core->desiredVideoDimensions(core, &w, &h);
	videoBuffer = xcalloc((size_t) w * h, BYTES_PER_PIXEL);
	core->setVideoBuffer(core, videoBuffer, w);

	if (!mCoreLoadFile(core, job.rom)) die("cannot load ROM %s", job.rom);
	/* SRAM lives in memory only: never touch a .sav next to the ROM. */
	struct VFile* save;
	if (job.sram) {
		struct VFile* in = VFileOpen(job.sram, O_RDONLY);
		if (!in) die("cannot open SRAM %s", job.sram);
		ssize_t size = in->size(in);
		void* buf = xcalloc((size_t) size, 1);
		in->read(in, buf, size);
		in->close(in);
		save = VFileMemChunk(buf, size);
		free(buf);
	} else {
		save = VFileMemChunk(NULL, 0);
	}
	core->loadSave(core, save);
	core->reset(core);

	cpu = core->cpu;
	gba = core->board;

	if (job.state) {
		struct VFile* vf = VFileOpen(job.state, O_RDONLY);
		if (!vf) die("cannot open state %s", job.state);
		if (!mCoreLoadStateNamed(core, vf, SAVESTATE_SAVEDATA | SAVESTATE_RTC | SAVESTATE_SCREENSHOT)) {
			die("cannot load state %s", job.state);
		}
		vf->close(vf);
	}

	uint32_t fc0 = gba->video.frameCounter;
	struct timespec t0, t1;
	clock_gettime(CLOCK_MONOTONIC, &t0);

#ifdef USE_GDB_STUB
	if (job.gdbPort) {
		struct GDBStub* stub = xcalloc(1, sizeof(*stub));
		GDBStubCreate(stub);
		struct Address local = { .version = IPV4, .ipv4 = 0x7F000001 };
		if (!GDBStubListen(stub, job.gdbPort, &local, GDB_WATCHPOINT_STANDARD_LOGIC)) die("cannot listen on port %d", job.gdbPort);
		mDebuggerAttach(&stub->d, core);
		fprintf(stdout, "emuh: GDB stub listening on 127.0.0.1:%d\n", job.gdbPort);
		fflush(stdout);
		mDebuggerEnter(&stub->d, DEBUGGER_ENTER_ATTACHED, NULL);
		while (stub->d.state != DEBUGGER_SHUTDOWN) {
			mDebuggerRun(&stub->d);
		}
		GDBStubShutdown(stub);
		core->deinit(core);
		return 0;
	}
#endif

	setup_probes();
	setup_watch();
	setup_lua();
	if (job.untilOp) {
		g_untilPrev = until_true(); /* a condition already true at the start must become true again */
	}

	for (g_frame = 0;; ++g_frame) {
		do_actions(g_frame);
		if (g_frame >= job.frames || g_stop || g_frame >= g_stopFrame) break;
		if (job.nKeys || !job.lua) core->setKeys(core, g_keysOff ? 0 : keys_for(g_frame));
		if (g_probing && g_frame >= job.traceFrom) {
			run_frame_probed();
		} else {
			core->runFrame(core);
		}
		if (job.untilOp) {
			bool now = until_true();
			if (now && !g_untilPrev && ++g_untilHits == (job.untilCount ? job.untilCount : 1)) {
				trigger_stop("until");
			}
			g_untilPrev = now;
		}
		if (lua_wants_stop() && !g_stop) {
			g_stop = true;
			g_stopReason = "lua";
		}
	}
	do_actions(END_FRAME);

	clock_gettime(CLOCK_MONOTONIC, &t1);
	double secs = (t1.tv_sec - t0.tv_sec) + (t1.tv_nsec - t0.tv_nsec) / 1e9;

	write_trace();
	write_watch_summary();
	if (g_breakFile) fclose(g_breakFile);
	write_info(secs, fc0);
	fprintf(stdout, "emuh: ran %u frames in %.2fs (%.0f fps), stop=%s\n", g_frame, secs, secs > 0 ? g_frame / secs : 0.0, g_stopReason);
	core->deinit(core);
	return 0;
}
