#!/usr/bin/env python3
"""Define addresses for symbols that are referenced but not defined anywhere and whose
name ends in an 8-digit hex address (gUnk_03001234, sub_08012345, ...).
Emits an assembly file: `sub_*` code addresses become Thumb functions (.thumb_set) so the
linker never inserts interworking glue; everything else is a plain absolute symbol.
Usage: autosyms.py out.s obj...   (runs arm-none-eabi-nm)"""
import re
import subprocess
import sys

out, objs = sys.argv[1], sys.argv[2:]
res = subprocess.run(['arm-none-eabi-nm', '-o'] + objs, capture_output=True, text=True, check=True)
defined, undefined = set(), set()
for line in res.stdout.splitlines():
    m = re.match(r'^\S+:\s+U (\S+)$', line)
    if m:
        undefined.add(m.group(1))
    else:
        p = line.split()
        if len(p) >= 3:
            defined.add(p[-1])
manual = set(re.findall(r'^\s*([A-Za-z_]\w*)\s*=', open('symbols.ld').read(), re.M))
lines = ['@ Generated by tools/autosyms.py - do not edit.', '\t.text']
for sym in sorted(undefined - defined - manual):
    m = re.search(r'_([0-9A-Fa-f]{8})$', sym)
    if not m:
        continue
    addr = int(m.group(1), 16)
    lines.append(f'\t.global {sym}')
    if sym.startswith('sub_') and 0x08000000 <= addr < 0x08080A20:
        lines.append(f'\t.thumb_set {sym}, 0x{addr:08X}')
    else:
        lines.append(f'\t.set {sym}, 0x{addr:08X}')
with open(out, 'w') as f:
    f.write('\n'.join(lines) + '\n')
