#!/usr/bin/env python3
"""Write config/symbols.txt: addresses of global symbols that can't be derived from their name.

  python3 tools/dumpsyms.py [build/eds.elf] [config/symbols.txt]

Run after a full link (the Makefile does it). The file lets tools work without the baserom and without
a full build (tools/target.py, tools/check.py): every symbol a unit can reference is either in
config/functions.tsv, symbols.ld, carries its address as a _XXXXXXXX suffix, or is listed here.
Format: `name address kind` with kind t (Thumb code), a (ARM code) or d (data/absolute).
Only rewrites the file when its content changes.
"""
import os
import re
import subprocess
import sys

elf = sys.argv[1] if len(sys.argv) > 1 else 'build/eds.elf'
out = sys.argv[2] if len(sys.argv) > 2 else 'config/symbols.txt'
known = set()
for line in open('config/functions.tsv'):
    if not line.startswith('#'):
        known.add(line.split('\t')[3])
for line in open('symbols.ld'):
    m = re.match(r'\s*(\w+)\s*=', line)
    if m:
        known.add(m.group(1))
rows = {}
for line in subprocess.run(['arm-none-eabi-readelf', '-sW', elf], capture_output=True, text=True).stdout.splitlines():
    p = line.split()
    if len(p) < 8 or not p[0].endswith(':') or p[4] != 'GLOBAL' or p[6] == 'UND':
        continue
    name, v, typ = p[7], int(p[1], 16), p[3]
    if name in known or name.startswith('$'):
        continue
    thumb = typ == 'FUNC' and v & 1
    addr = v & ~1 if thumb else v
    m = re.search(r'_([0-9A-Fa-f]{8})$', name)
    if m and int(m.group(1), 16) == addr:
        continue  # derivable from the name
    kind = 't' if thumb else ('a' if typ == 'FUNC' else 'd')
    rows[name] = f'{name} {addr:08X} {kind}'
text = ('# Generated by tools/dumpsyms.py from the last full link; symbols not derivable from their name.\n'
        + '\n'.join(rows[k] for k in sorted(rows)) + '\n')
if not os.path.exists(out) or open(out).read() != text:
    open(out, 'w').write(text)
    print(f'wrote {out} ({len(rows)} symbols)')
