#!/usr/bin/env python3
"""Build the shared-header plan: which header owns every struct, enum, global and function prototype.

  tools/dr python3 tools/genprotos.py          # first: exact prototypes as defined (build/readability/protos.json)
  python3 tools/headerplan.py                   # -> build/readability/header_plan.json (+ a summary on stdout)
  python3 tools/headerplan.py --header duel.h   # print one header's entry
  python3 tools/headerplan.py --owner ChainState  # which header owns a struct/enum/global/function

Inputs: build/names/types.json (structs, enums), build/names/final.txt (subsystems, names, summaries),
build/names/prototypes.json (proposed parameter names, comments), build/readability/protos.json (exact
definitions and every unit's local declarations, from tools/genprotos.py), build/readability/unit_names.tsv
(old code_<addr> unit names -> current names), config/functions.tsv, include/*.h (legacy headers).

The layout below (HEADERS, the function/global name rules, STRUCT_HOME, ENUM_HOME, GROUPS) is the decision;
everything else is computed from it. Every struct and enum of types.json has exactly one owner, every function of
config/functions.tsv one header, and the include graph (by-value struct use only; pointers use forward
declarations) must be acyclic: the script fails otherwise.
"""
import argparse
import collections
import datetime
import json
import os
import re
import sys

sys.path.insert(0, os.path.dirname(__file__))

OUT = 'build/readability/header_plan.json'

# ----------------------------------------------------------------------------------------------- layout

# path -> (group, description). Paths are relative to include/.
HEADERS = {
    # base
    'global.h': ('core', 'Base types (u8..s32, vu*, bool8/bool32), TRUE/FALSE/NULL, INCLUDE_ASM and the asm macros '
                         'include (keep that behaviour), generic macros (ARRAY_COUNT, STATIC_ASSERT). Existing file: '
                         'additive edits only, verified with check_all.'),
    'gba.h': ('core', 'GBA hardware: memory map, IO registers and their bit values (DISPCNT, BGxCNT, BLDCNT, DMA, '
                      'timers, IE/IF, KEYINPUT), OAM attribute and SIO register layouts, BIOS calls (libagbsyscall).'),
    # constants (no includes; enums and #defines only)
    'constants/cards.h': ('cards', 'GENERATED by tools/gencards.py: enum CardNumber, one CARD_<NAME> per card number '
                                   '(card names from assets/cards/names.json), CARD_<n> for effect keys with no EDS '
                                   'card. Do not edit by hand.'),
    'constants/card_stats.h': ('cards', 'Card stat values: enum CardType, CardAttribute, CardKind, SpellSubtype, '
                                        'CardFrame; bit layout of gCardStats words (shift/mask defines).'),
    'constants/game.h': ('cards', 'Game-wide catalogs: enum DuelistId, BoosterPackId, Language.'),
    'constants/sound.h': ('system_io', 'Sound ids: enum SoundEffect (and song ids when named).'),
    'constants/duel.h': ('duel_core', 'Duel-wide constants: zones, areas, phases, results, zone links and status '
                                      'flags, battle stages, chain/response kinds, card-menu commands, prompt kinds, '
                                      'summon-action kinds, field-pick masks, start field and duel format.'),
    'constants/duel_cmds.h': ('duel_cmd', 'enum DuelCmdId (the ~164 duel command ids, | 0x8000 for player 1) and '
                                          'command operand constants (TokenKind).'),
    # system
    'main.h': ('core', 'struct Main gMain, IntrTable and interrupt handlers, the main loop, input (ReadKeys), scene '
                       'callbacks (SetMainCallback), frame sync (FrameSyncUpdate, FlushOamBuffer), VBlank flags.'),
    'util.h': ('core', 'Memory, string and number helpers (MemClear16, StrCopy, FormatInt, RoundTo10...), Random, '
                       '8.8 fixed-point maths, Timer/Ease/Tween/Line steppers, callback queues and step lists, '
                       'generic small structs (Coords16).'),
    'palette.h': ('core', 'Screen fades and blending: brightness/alpha fades (FadeToBlack, ClearBlend...), '
                          'struct Fade, PalFade/PalFadeStrided palette fades, SetBldAlpha/SetBldY.'),
    'bg.h': ('gfx', 'BG maps and tiles: image-pack loaders (LoadBgImage*), map rect fill/copy/crop helpers, tile '
                    'sheet copies, LZSSDecompress, card art loaders, BG scroll/affine registers.'),
    'sprite.h': ('gfx', 'Sprites: direct OAM emitters (AddSprite*, AddAffineSprite*), the OAM layer list '
                        '(OamList*), sprite frame streams (SprAnim*), script animations (AnimBlock*/AnimState*), '
                        'OBJ affine sets, number sprites.'),
    'text.h': ('gfx', 'Text rendering: the text canvas (gTextCanvas, TextDraw*), glyph/string/number to tile '
                      'renderers, bitmap printers, Shift-JIS helpers, decimal parsers.'),
    'save.h': ('system_io', 'Save data (struct SaveData gSaveData), SRAM save/verify, the card collection (trunk, '
                            'saved decks, copy limits) and duel records.'),
    'sound.h': ('system_io', 'Konami sound driver state (gSoundDriver, tracks, PCM channels), driver entry points '
                             'and the game-side API (PlaySE, PlayBGM, StopBGM, FadeOutBGM).'),
    'link.h': ('system_io', 'Link cable: multi-player SIO driver (gLinkSio), BASICSIO packet layer (gLinkBuf), '
                            'two-player value sync (LinkSync*).'),
    'debug.h': ('core', 'Debug menu, debug card viewers, debug print stubs.'),
    'card_data.h': ('cards', 'Read-only card database: gCardStats, gCardNames, gCardDescriptions, '
                             'gCardIdToNumber/gCardNumberToId, gCardPasswords, card art and frame tables; optional '
                             'accessor macros (keep the matching-relevant access forms in units).'),
    # front end
    'title_screen.h': ('cards', 'Boot license screens and the title screen (gTitleState).'),
    'main_menu.h': ('cards', 'Main menu and the Record (Duel Score) screen.'),
    'bustup.h': ('cards', 'Bust-up dialogue scenes (gBustup and its sprites/fade/cursor/mouth animation).'),
    'calendar.h': ('frontend', 'Calendar screen and date logic (day counter, weekdays, holidays, calendar events).'),
    'campaign.h': ('frontend', 'Campaign day loop, Link Battle, opponent selection (gOpponentSelect), unlocks.'),
    'card_detail.h': ('cards', 'Full-screen Card Detail viewer (gCardDetail).'),
    'deck_edit.h': ('deck_edit', 'Deck Edit and the card-list screens (Side Deck swap, Trading and Prohibition '
                                'pickers, List Filter, Statistics) on gDeckEdit.'),
    'booster.h': ('frontend', 'Booster packs: pack list, pack generator, Get-a-pack scene (gPackOpenWork), '
                              'starter deck choice.'),
    'password_trade.h': ('frontend', 'Password scene (gPassword) and Card Trading scene (gCardTrading).'),
    # duel
    'duel.h': ('duel_core', 'Duel data model: struct DuelCard, DuelZone, DuelPlayer, DuelState (gDuel, '
                            'gDuelPlayers, gDuelZones and the per-pile alias symbols), DuelLoc, CardMenu, '
                            'ZoneCardStats; card list/zone/link/stat helpers.'),
    'duel_actions.h': ('duel_core', 'Field actions that queue animated duel commands: destroy, send to graveyard, '
                                    'banish, return, flip, move, life points, draws.'),
    'duel_cmd.h': ('duel_cmd', 'Duel command runner: struct DuelCmd gDuelCmd, the queue (DuelCmd_Push, '
                               'DuelCmdQueue_Run, DuelCmd_Dispatch) and every DuelCmd_* handler.'),
    'duel_flow.h': ('duel_flow', 'Duel step machine and phases (DuelMainStep, DuelPhase_*), duel setup, win checks, '
                                 'struct DuelCtrl gDuelCtrl, phase menu, duel BGM.'),
    'battle.h': ('duel_flow', 'Battle Phase: struct Battle gBattle, BattleSide, CalcBattle, BattleStage_* '
                              'handlers, attack eligibility.'),
    'chain.h': ('duel_flow', 'Chain and event responses: struct ChainState gChain, ChainEntry, ChainList, '
                             'DeckReorderState, Chain_*, EventResponse_*.'),
    'summon.h': ('duel_flow', 'Summons: struct SummonAction gSummonAction, summon checks, queued summon actions, '
                              'summon steps, position menu.'),
    'card_menu.h': ('duel_flow', 'Card command menu (CardMenu_*: available commands, execution, drawing).'),
    'duel_prompt.h': ('duel_flow', 'Player prompts (DuelPrompt_*): discard/tribute/banish pickers, type and '
                                   'attribute menus, deck reorder, five-card menu.'),
    'effect.h': ('effects_ai', 'Card effect support: struct CardEffect (gCardEffects rows), FindCardEffect, '
                               'CanActivateEffect, target collection, fusion/ritual recipes, passive hooks.'),
    'effect_handlers.h': ('effects_ai', 'Prototypes of every gCardEffects handler '
                                        '(Effect<Card>Prepare/Check/ChainA/ChainB/Resolve and the shared ones).'),
    'ai.h': ('effects_ai', 'CPU opponent: gAiState, gAiWork, AiRunTurn/AiRunStep, attack/summon simulation, '
                           'strategies, opponent decks.'),
    'duel_screen.h': ('duel_ui', 'Duel field screen: struct DuelScreen gDuelScreen, BG card cells, scrolling, '
                                 'cursor (DuelCursor_*), card animations (DuelAnim_*), info bar (DuelInfo_*, '
                                 'TextCells*), LP/phase indicators, chain list screen.'),
    'text_box.h': ('duel_cmd', 'Duel text box (struct TextBox gTextBox): messages, Yes/No and choice menus.'),
    'card_list_view.h': ('deck_edit', 'Card-list viewer for graveyards, decks and targets (struct CardListView '
                                    'gCardListView).'),
    'battle_scene.h': ('duel_cmd', 'Card-vs-card battle scene (struct BattleScene gBattleScene).'),
    'duel_scenes.h': ('duel_ui', 'Duel overlay scenes (gDuelScene, gSceneWork): coin toss, dice, Exodia, Destiny '
                                 'Board, and the pre-duel turn-order (rock-paper-scissors) screen.'),
    'turn_order.h': ('cards', 'Pre-duel turn-order screen (rock-paper-scissors card carousel, FIRST/SECOND choice, '
                              'DUEL logo): TurnOrder_* steps, carousel scrollers, its enums and graphics tables. '
                              'Its work struct is gSceneWork.u.turnOrder (duel_scenes.h).'),
    'duel_link.h': ('duel_cmd', 'Duel link protocol: struct LinkState gLinkState, enum LinkMsgId, prompt and '
                                'command mirroring (DuelLink_*).'),
}

# Total include order: a header may include only headers that come EARLIER in this list (no cycles possible).
INCLUDE_ORDER = [
    'global.h', 'constants/cards.h', 'constants/card_stats.h', 'constants/game.h', 'constants/sound.h',
    'constants/duel.h', 'constants/duel_cmds.h',
    'gba.h', 'main.h', 'util.h', 'palette.h', 'bg.h', 'sprite.h', 'text.h',
    'save.h', 'sound.h', 'link.h', 'debug.h', 'card_data.h',
    'calendar.h', 'title_screen.h', 'main_menu.h', 'bustup.h', 'card_detail.h', 'booster.h', 'deck_edit.h',
    'password_trade.h', 'campaign.h',
    'duel.h', 'duel_cmd.h', 'duel_actions.h', 'chain.h', 'battle_scene.h', 'battle.h', 'summon.h', 'card_menu.h',
    'duel_prompt.h', 'duel_flow.h', 'effect.h', 'effect_handlers.h', 'ai.h',
    'duel_screen.h', 'text_box.h', 'card_list_view.h', 'duel_scenes.h', 'turn_order.h',
    'duel_link.h',
]

# Headers that exist today (moved to include/legacy/ before the writers start; see NOTES).
LEGACY = {'main.h': 'main.h', 'duel.h': 'duel.h', 'duel_ui.h': ['duel_cmd.h', 'duel_screen.h', 'duel.h'],
          'sound.h': 'sound.h', 'gba.h': 'gba.h'}

# Writer groups: name -> description. Header membership comes from HEADERS[path][0].
GROUPS = {
    'core': 'Base, hardware and system core: global.h, gba.h, main.h, util.h, palette.h, debug.h',
    'gfx': 'Graphics and text libraries: bg.h, sprite.h, text.h',
    'system_io': 'Sound driver and API, link cable, save data and collection: sound.h, constants/sound.h, link.h, '
                 'save.h',
    'cards': 'Card constants (run tools/gencards.py for constants/cards.h), card data, Card Detail, title, main '
             'menu, bust-up dialogue, turn-order screen',
    'frontend': 'Calendar, Campaign/Link Battle, booster packs, Password and Card Trading',
    'deck_edit': 'Deck Edit and its card-list screens, and the duel card-list viewer: deck_edit.h, '
                 'card_list_view.h',
    'duel_core': 'Duel data model and field actions: constants/duel.h, duel.h, duel_actions.h',
    'duel_cmd': 'Duel commands and what they drive: constants/duel_cmds.h, duel_cmd.h, duel_link.h, text_box.h, '
                'battle_scene.h',
    'duel_flow': 'Duel flow: duel_flow.h, battle.h, chain.h, summon.h, card_menu.h, duel_prompt.h',
    'effects_ai': 'Card effects (support + handler prototypes) and the CPU AI: effect.h, effect_handlers.h, ai.h',
    'duel_ui': 'Duel field screen and overlay scenes: duel_screen.h, duel_scenes.h',
}

# subsystem section prefix in final.txt -> key
SUBSYSTEMS = [
    ('System core', 'sys'), ('Graphics library', 'gfx'), ('Text rendering', 'text'),
    ('Save data, card collection', 'save'), ('Sound', 'sound'), ('Link cable', 'link'),
    ('Card database', 'carddb'), ('Debug menu', 'debug'), ('Boot license and title', 'title'),
    ('Main menu and the Record', 'mainmenu'), ('Dialogue (Bustup)', 'bustup'), ('Calendar', 'calendar'),
    ('Campaign, Link Battle', 'campaign'), ('Card Detail viewer', 'carddetail'), ('Deck Edit', 'deckedit'),
    ('Booster packs', 'booster'), ('Password and Card Trading', 'password'), ('Duel engine', 'duelstate'),
    ('Duel command queue', 'duelcmd'), ('Duel flow', 'duelflow'), ('Card effects', 'effects'),
    ('CPU opponent AI', 'ai'), ('Duel screen and presentation', 'duelscreen'), ('Duel overlay scenes', 'duelscenes'),
    ('Duel link protocol', 'duellink'), ('Alias symbols', 'alias'),
]
SUB_DEFAULT = {
    'sys': 'main.h', 'gfx': 'bg.h', 'text': 'text.h', 'save': 'save.h', 'sound': 'sound.h', 'link': 'link.h',
    'carddb': 'card_data.h', 'debug': 'debug.h', 'title': 'title_screen.h', 'mainmenu': 'main_menu.h',
    'bustup': 'bustup.h', 'calendar': 'calendar.h', 'campaign': 'campaign.h', 'carddetail': 'card_detail.h',
    'deckedit': 'deck_edit.h', 'booster': 'booster.h', 'password': 'password_trade.h', 'duelstate': 'duel.h',
    'duelcmd': 'duel_cmd.h', 'duelflow': 'duel_flow.h', 'effects': 'effect.h', 'ai': 'ai.h',
    'duelscreen': 'duel_screen.h', 'duelscenes': 'duel_scenes.h', 'duellink': 'duel_link.h',
}
# (subsystem or '*', regex on the name without a leading g/gStr for globals) -> header; first match wins
NAME_RULES = [
    ('sys', r'^(MemClear16|MemCopy16|CopyDoubleWords|Str|FormatStr|FormatInt|RoundTo10|Halve|Random)', 'util.h'),
    ('sys', r'^(SetBrightness|ClearBlend|Fade)', 'palette.h'),
    ('sys', r'^SineTable', 'util.h'),
    ('gfx', r'^(AddSprite|AddAffineSprite|SetOam|ClearObjPalettes|SprAnim|OamList|AnimState|AnimBlock|ObjAffine|'
            r'DrawNumberSprites|SpriteShape|Sprite)', 'sprite.h'),
    ('gfx', r'^(FadeStart|FadeTick|PalFade|SetBld)', 'palette.h'),
    ('gfx', r'^(CallbackQueue_|StepList_|Timer_|Ease_|Tween|Line(Init|Step)|MulFix8|DivFix8|ReciprocalFix8|Sine)',
     'util.h'),
    ('duelstate', r'^@unit:(duel_send_to_grave|duel_field_moves|duel_card_actions)$', 'duel_actions.h'),
    ('duelflow', r'^(CalcBattle|Battle_|BattleStage|BattlePhase|MarkMonsterAttacked|CanAttackDirectly|'
                 r'IsTypeForbiddenToAttack|CanMonsterAttack|BuildAttackableMask|CanEnterBattlePhase|'
                 r'IsBattleEffectBlocked)', 'battle.h'),
    ('duelflow', r'^(Chain_|Chain[A-Z]|EventResponse|IsZoneInChainList|CanActivateFieldCard|CanActivateHandCard)',
     'chain.h'),
    ('duelflow', r'^(CardMenu|CanActivateMonsterEffect)', 'card_menu.h'),
    ('duelflow', r'^(Summon|Queue\w*Summon|ExecuteSummonAction|CanNormalSummon|CanSpecialSummon|CanSummon|'
                 r'CanPayBanishSummonCost|TributeSummon)', 'summon.h'),
    ('duelflow', r'^(DuelPrompt|DiscardPrompt|CountDiscardableHandCards|TypeMenu|AttributeMenu|DeckReorder|'
                 r'FiveCardMenu)', 'duel_prompt.h'),
    ('effects', r'^Effect\w*(Prepare|Check|ChainA|ChainB|Resolve)$', 'effect_handlers.h'),
    ('duelscenes', r'^(TurnOrder|Scroller_|JudgeRockPaperScissors|TurnChoice|DuelLogo|HandCardTileNums|'
                   r'EgyptCorridor|RockCard|ScissorsCard|PaperCard|SelectCardBanner|WinBanner|LoseBanner|DrawBanner|'
                   r'WaitSign)', 'turn_order.h'),
    ('duelscreen', r'^TextBox', 'text_box.h'),
    ('duelscreen', r'^CardListView', 'card_list_view.h'),
    ('duelscreen', r'^BattleScene', 'battle_scene.h'),
]
# (regex on the global name without g/gStr) -> header, for RAM and ROM globals of any subsystem; first match wins
GLOBAL_RULES = [
    (r'^(CardIcon|CardFrame|CardArt|CardStatDigits|AttributeIcon|SpellSubtypeIcon|MonsterTypeIcon)', 'card_data.h'),
    (r'^Font|^SystemFont', 'text.h'),
    (r'^HandCursor', 'sprite.h'),
    (r'^(SquareTable|Sine)', 'util.h'),
    (r'^Main_', 'main.h'),
    (r'^(OpponentSelect|UnknownOpponentName)', 'campaign.h'),
]
# canonical types decided here (the proposals disagree or name unit-local structs)
GLOBAL_TYPE = {
    'gDuelHands': 'struct DuelCard[]', 'gDuelDecks': 'struct DuelCard[]', 'gDuelGraveyards': 'struct DuelCard[]',
    'gDuelFusionDecks': 'struct DuelCard[]', 'gDuelBanished': 'struct DuelCard[]',
    'gSineTable128': 'const s16 []',    # s16 sine values; main.c's u16 view (ldrh) stays local
}
GLOBAL_TYPE_NOTE = ('player 0 pile; player p is at + p * 0xD64 bytes: a stride view struct like DuelZonesPlayer '
                    '(cards[80] + padding to 0xD64) is the readable choice if the units\' accesses allow it')

# RAM/ROM globals whose owner is not the header of their subsystem (after GLOBAL_RULES and NAME_RULES)
GLOBAL_HOME = {
    'gChainListScreen': 'duel_screen.h', 'gTextBox': 'text_box.h', 'gCardListView': 'card_list_view.h',
    'gCardListViewCards': 'card_list_view.h', 'gBattleScene': 'battle_scene.h', 'gBattle': 'battle.h',
    'gChain': 'chain.h', 'gChainEffectWork': 'chain.h', 'gEventResponseEntry': 'chain.h',
    'gChainQueryEntry': 'chain.h', 'gChainQueryEntryRaw': 'chain.h', 'gChainProxyLink': 'chain.h',
    'gSummonAction': 'summon.h', 'gDuelCtrl': 'duel_flow.h', 'gBgTileBuffer': 'bg.h', 'gScratchBuffer': 'util.h',
    'gSineTable': 'util.h', 'gSineTable128': 'util.h', 'gDuelCmdCard': 'duel_cmd.h',
    'gOpponentSelectSlotPos': 'campaign.h', 'gDaysPerMonth': 'calendar.h',
    'gWinLoseDrawLabels': 'campaign.h',     # used by campaign_select and main_menu's record display
}

# struct -> owning header (every struct of types.json, plus the ones only the legacy headers define)
STRUCT_HOME = {
    # core / gfx
    'Main': 'main.h', 'BgScrollReg': 'main.h', 'OamEntry': 'gba.h', 'SioMultiCnt': 'gba.h',
    'CallbackQueue': 'util.h', 'StepList': 'util.h', 'Timer': 'util.h', 'Ease': 'util.h', 'Tween': 'util.h',
    'Line': 'util.h', 'Coords16': 'util.h',
    'Fade': 'palette.h', 'PalFade': 'palette.h', 'PalFadeStrided': 'palette.h', 'PalDelta': 'palette.h',
    'ImagePackCell': 'bg.h', 'ImagePackCount': 'bg.h',
    'OamList': 'sprite.h', 'OamListEntry': 'sprite.h', 'OamTemplate': 'sprite.h', 'ObjAffine': 'sprite.h',
    'SprAnim': 'sprite.h', 'SprAnimHeader': 'sprite.h', 'SprAnimPiece': 'sprite.h', 'AnimBlock': 'sprite.h',
    'AnimSeq': 'sprite.h', 'AnimState': 'sprite.h',
    'TextCanvas': 'text.h', 'TextFlags': 'text.h',
    # system io
    'SaveData': 'save.h', 'TrunkEntry': 'save.h', 'CardCopyLimit': 'save.h', 'DuelRecord': 'save.h',
    'SoundDriver': 'sound.h', 'SoundBgmTrack': 'sound.h', 'SoundSeTrack': 'sound.h', 'SoundPcmChannel': 'sound.h',
    'SoundChannelOutput': 'sound.h', 'SoundFifoPos': 'sound.h', 'SoundSample': 'sound.h', 'SoundSeDef': 'sound.h',
    'SoundSong': 'sound.h',
    'LinkSio': 'link.h', 'LinkBuf': 'link.h', 'LinkPacket': 'link.h', 'LinkSync': 'link.h',
    'LinkSyncPacket': 'link.h',
    'DebugMenuItem': 'debug.h', 'CalendarEventName': 'debug.h',
    # front end
    'TitleState': 'title_screen.h', 'StarterDeckPool': 'booster.h', 'RecordScreen': 'main_menu.h',
    'BustupState': 'bustup.h', 'BustupTextBox': 'bustup.h', 'BytePos': 'bustup.h', 'DialogueEntry': 'bustup.h',
    'Duelist': 'bustup.h', 'SceneSet': 'bustup.h',
    'Calendar': 'calendar.h', 'CalendarEventEntry': 'calendar.h', 'Date': 'calendar.h',
    'OpponentSelect': 'campaign.h', 'OpponentResultTexts': 'campaign.h', 'Mode4Bitmap': 'campaign.h',
    'CardDetail': 'card_detail.h',
    'DeckEdit': 'deck_edit.h', 'DeckEditCommandMenu': 'deck_edit.h', 'DeckEditListRow': 'deck_edit.h',
    'DeckEditScrollBar': 'deck_edit.h', 'DeckStatsRow': 'deck_edit.h', 'CardMove': 'deck_edit.h',
    'FrameSlot': 'deck_edit.h', 'FrameSlotRing': 'deck_edit.h', 'SortRange': 'deck_edit.h',
    'SpriteDef': 'deck_edit.h',
    'PackContentsEntry': 'booster.h', 'PackCursor': 'booster.h', 'PackInfo': 'booster.h',
    'PackListWork': 'booster.h', 'PackOpenWork': 'booster.h', 'PackSlot': 'booster.h', 'PackSlots': 'booster.h',
    'StarterDeckSelectWork': 'booster.h',
    'CardTradingState': 'password_trade.h', 'PasswordArrowFrame': 'password_trade.h',
    'PasswordKey': 'password_trade.h', 'PasswordState': 'password_trade.h',
    # duel
    'DuelCard': 'duel.h', 'DuelZone': 'duel.h', 'DuelPlayer': 'duel.h', 'DuelState': 'duel.h',
    'DuelZonesPlayer': 'duel.h', 'DuelLoc': 'duel.h', 'CardMenu': 'duel.h', 'ZoneCardStats': 'duel.h',
    'DuelStateBattleWord': 'duel.h', 'DuelCardStatusBytes': 'duel.h',
    'DuelCmd': 'duel_cmd.h', 'DuelCmdEntry': 'duel_cmd.h', 'DuelCmdTimer16': 'duel_cmd.h',
    'DuelResultBanner': 'duel_cmd.h',
    'DuelCtrl': 'duel_flow.h', 'OpponentBGM': 'duel_flow.h',
    'Battle': 'battle.h', 'BattleSide': 'battle.h',
    'ChainState': 'chain.h', 'ChainEntry': 'chain.h', 'ChainList': 'chain.h', 'DeckReorderState': 'chain.h',
    'SummonAction': 'summon.h',
    'CardEffect': 'effect.h', 'FusionRecipe': 'effect.h', 'RitualRecipe': 'effect.h',
    'AiState': 'ai.h', 'AiWork': 'ai.h', 'AiSimResult': 'ai.h', 'AttackPlan': 'ai.h', 'DeckList': 'ai.h',
    'DuelScreen': 'duel_screen.h', 'DuelAnimZoneArg': 'duel_screen.h', 'DuelZonePos': 'duel_screen.h',
    'CardJumpArcEntry': 'duel_screen.h', 'ChainListScreen': 'duel_screen.h', 'ChainListHeader': 'duel_screen.h',
    'TextBox': 'text_box.h', 'CardListView': 'card_list_view.h', 'BattleScene': 'battle_scene.h',
    'DuelScene': 'duel_scenes.h', 'SceneWork': 'duel_scenes.h', 'CoinTossWork': 'duel_scenes.h',
    'CoinToss': 'duel_scenes.h', 'Coin': 'duel_scenes.h', 'Sparkle': 'duel_scenes.h',
    'SparklePool': 'duel_scenes.h', 'DiceScreen': 'duel_scenes.h', 'ExodiaSceneWork': 'duel_scenes.h',
    'DestinyBoardSceneWork': 'duel_scenes.h', 'FinalLetter': 'duel_scenes.h', 'ScrollLayer': 'duel_scenes.h',
    'Scroller': 'duel_scenes.h', 'TurnOrderSceneWork': 'duel_scenes.h', 'ChoiceBob': 'duel_scenes.h',
    'LinkState': 'duel_link.h', 'LinkMessage': 'duel_link.h',
}
# structs only the legacy headers define (not in types.json), with the types.json struct that replaces them
LEGACY_ONLY_STRUCTS = {
    'DuelZonesPlayer': ('duel.h', None, 'view of the zones of one player with the player stride (gDuelZones)'),
    'DuelCmdEntry': ('duel_cmd.h', None, 'one queued command (8 bytes), DuelCmd.queue[]'),
    'SoundTrack': (None, 'SoundBgmTrack / SoundSeTrack', 'legacy sound.h uses one struct for both track kinds'),
    'SoundPcmVoice': (None, 'SoundPcmChannel', 'renamed'),
}

# RAM alias symbols inside another global that only one unit uses through its own view: not declared in a header
UNIT_LOCAL_ALIASES = {
    'gDuelAnimArgs': 'gDuelScreen + 0x834 (animArg .. sprAnim.frameIndex); duel_card_anim loads this address from its own '
                     'literal through its local struct Pick, so the alias stays unit-local',
}

# functions defined `static` in their unit (no header prototype): the SRAM routines ReadSram/VerifySram copy to the
# stack and run from there (src/sdk/agb_sram.c)
STATIC_FUNCTIONS = {'ReadSram_Core', 'VerifySram_Core'}

# unit-local struct tags used in definitions' prototypes or global declarations that types.json does not map
TAG_FIXES = {
    ('gfx_util', 'CallbackList'): 'StepList', ('deck_edit_panel', 'Flag0'): 'TextFlags',
    ('duel_field_view', 'ZoneAnimEntry'): 'DuelZonePos', ('turn_order_steps', 'Entry'): 'DuelCard',
    ('dice_scene', 'Mover'): 'Line', ('dice_scene', 'Reel'): 'ScrollLayer', ('coin_toss_scene', 'Sparkles'): 'SparklePool',
    # header integration (2026-10-03): unit-local tags that reuse a canonical name for a different struct.
    # An exact (unit, tag) entry here wins over the "tag is already canonical" shortcut in translate_tags.
    ('bitmap_text', 'OamEntry'): 'OamListEntry', ('link_sio', 'OamEntry'): 'OamListEntry',   # 12-byte list entry
    ('bustup_scene', 'TextBox'): 'BustupTextBox',            # the 0xFC bust-up box, not text_box.h's TextBox
    ('deck_edit_list', 'Slide'): 'DeckEditCommandMenu',      # gDeckEdit+0x1C3C here (PackListWork in deck_edit_panel)
    ('deck_edit_list', 'CellArr_x'): 'AnimState',            # gDeckEdit.anims (+0x1718), 20-byte stride
}

# types.json field types that name a unit-local struct which is a different canonical struct
FIELD_TYPE_FIXES = {
    ('BustupState', 'textBox'): 'struct BustupTextBox',      # was "struct TextBox (0xFC)", the bustup text box
}

ENUM_HOME = {
    # constants
    'CardNumber': 'constants/cards.h',
    'CardType': 'constants/card_stats.h', 'CardAttribute': 'constants/card_stats.h',
    'CardKind': 'constants/card_stats.h', 'SpellSubtype': 'constants/card_stats.h',
    'CardFrame': 'constants/card_stats.h',
    'DuelistId': 'constants/game.h', 'BoosterPackId': 'constants/game.h', 'Language': 'constants/game.h',
    'SoundEffect': 'constants/sound.h',
    'DuelPhase': 'constants/duel.h', 'DuelResult': 'constants/duel.h', 'DuelZoneIndex': 'constants/duel.h',
    'DuelArea': 'constants/duel.h', 'ZoneLinkKind': 'constants/duel.h', 'ZoneStatusFlag': 'constants/duel.h',
    'BanishKind': 'constants/duel.h', 'BattleStage': 'constants/duel.h', 'ResponseEventKind': 'constants/duel.h',
    'ChainEntryKind': 'constants/duel.h', 'CardMenuCommand': 'constants/duel.h',
    'CardMenuCommandMask': 'constants/duel.h', 'DuelPromptKind': 'constants/duel.h',
    'SummonActionKind': 'constants/duel.h', 'FieldPickMask': 'constants/duel.h', 'DuelField': 'constants/duel.h',
    'DuelFormat': 'constants/duel.h', 'DuelStep': 'constants/duel.h',
    'DuelCmdId': 'constants/duel_cmds.h', 'TokenKind': 'constants/duel_cmds.h',
    # system / gfx / text
    'IntrSlot': 'main.h', 'VBlankFlag': 'main.h',
    'TickState': 'util.h', 'LineState': 'util.h', 'TweenMode': 'util.h', 'TweenState': 'util.h',
    'FadeColor': 'palette.h', 'FadeState': 'palette.h',
    'NumberDrawMode': 'bg.h', 'TileColors': 'bg.h',
    'SpriteShape': 'sprite.h', 'AnimActive': 'sprite.h', 'OamGroupMode': 'sprite.h', 'OamTileFormat': 'sprite.h',
    'NumberSpriteMode': 'sprite.h',
    'MapCellMode': 'text.h', 'NumberMode': 'text.h', 'NumberPadMode': 'text.h',
    # system io
    'SaveOptionFlags': 'save.h', 'SavedDeckCapacity': 'save.h',
    'SoundBgmChannel': 'sound.h', 'SoundBgmTrackFlags': 'sound.h', 'SoundChannelCommand': 'sound.h',
    'SoundDriverFlags': 'sound.h', 'SoundPcmFlags': 'sound.h', 'SoundSeSlot': 'sound.h',
    'SoundSeTrackFlags': 'sound.h',
    'LinkPacketType': 'link.h', 'LinkSioPacketType': 'link.h', 'LinkSioStatus': 'link.h', 'LinkSioType': 'link.h',
    'LinkStepFlags': 'link.h', 'LinkSyncPhase': 'link.h', 'LinkSyncState': 'link.h',
    'DebugMenuItemId': 'debug.h', 'DebugMenuStep': 'debug.h',
    # front end
    'TitleStep': 'title_screen.h', 'MainMenuItem': 'main_menu.h', 'RecordScroll': 'main_menu.h',
    'BustupStep': 'bustup.h', 'BustupTextState': 'bustup.h', 'TextBoxState': 'bustup.h', 'TextColor': 'bustup.h',
    'CalendarEvent': 'calendar.h', 'HolidayFlag': 'calendar.h', 'Weekday': 'calendar.h',
    'CampaignStep': 'campaign.h', 'LinkBattleStep': 'campaign.h', 'OpponentSelectStep': 'campaign.h',
    'CardDetailState': 'card_detail.h',
    'AttributeIcon': 'deck_edit.h', 'CardIconSet': 'deck_edit.h', 'CardListMode': 'deck_edit.h',
    'CardMoveStep': 'deck_edit.h', 'CommandMenuAnim': 'deck_edit.h', 'DeckEditCommand': 'deck_edit.h',
    'DeckEditExitMode': 'deck_edit.h', 'DeckEditList': 'deck_edit.h', 'DeckEditMenuSlideCmd': 'deck_edit.h',
    'DeckEditMenuVariant': 'deck_edit.h', 'DeckEditScrollDir': 'deck_edit.h', 'DeckEditSlide': 'deck_edit.h',
    'DeckEditStep': 'deck_edit.h', 'DeckStatsCategory': 'deck_edit.h', 'ListFilter': 'deck_edit.h',
    'ListFilterPhase': 'deck_edit.h', 'ListSort': 'deck_edit.h', 'SideDeckSwapState': 'deck_edit.h',
    'GetPackDetailState': 'booster.h', 'GetPackStep': 'booster.h', 'PackCursorAnim': 'booster.h',
    'PackRevealFrame': 'booster.h', 'StarterDeck': 'booster.h', 'StarterDeckInitState': 'booster.h',
    'StarterDeckSelectStep': 'booster.h',
    'CardTradingStep': 'password_trade.h', 'PasswordStep': 'password_trade.h', 'PasswordKeyId': 'password_trade.h',
    # duel
    'DrawPhaseStep': 'duel_flow.h', 'EndPhaseStep': 'duel_flow.h', 'MainPhaseStep': 'duel_flow.h',
    'StandbyStep': 'duel_flow.h', 'TurnEndStep': 'duel_flow.h', 'TurnStartStep': 'duel_flow.h',
    'PhaseMenuChoice': 'duel_flow.h', 'PhaseMenuState': 'duel_flow.h',
    'EventResponseStep': 'chain.h', 'LinkQueryStep': 'chain.h', 'DeckReorderMode': 'chain.h',
    'CardMenuState': 'card_menu.h', 'DiscardPromptStep': 'duel_prompt.h',
    'EffectStep': 'effect.h', 'RitualStep': 'effect.h', 'ChosenPlayer': 'effect.h', 'CoinFace': 'effect.h',
    'SevenCompletedStat': 'effect.h', 'FusionSlot': 'effect.h', 'SpellSpeed': 'effect.h',
    'AiFlag': 'ai.h', 'AiMainState': 'ai.h', 'AiSimpleSpellsPhase': 'ai.h', 'AiSpellState': 'ai.h', 'AiStep': 'ai.h',
    'AiStrategy': 'ai.h',
    'ChainListScreenState': 'duel_screen.h', 'FieldCellTile': 'duel_screen.h', 'ZoneMarkerTile': 'duel_screen.h',
    'CursorDirection': 'duel_screen.h', 'DuelAnimKind': 'duel_screen.h',
    'TextBoxFlags': 'text_box.h', 'TextBoxMenuKind': 'text_box.h', 'TextBoxMenuState': 'text_box.h',
    'TextBoxStep': 'text_box.h',
    'CardListSource': 'card_list_view.h', 'CardListViewButton': 'card_list_view.h',
    'CardListViewInputState': 'card_list_view.h', 'CardListViewMode': 'card_list_view.h',
    'CardListViewStep': 'card_list_view.h',
    'BattleResultStep': 'battle_scene.h', 'BattleSceneState': 'battle_scene.h', 'BattleSideFlags': 'battle_scene.h',
    'DuelSceneId': 'duel_scenes.h', 'CoinFaceFrame': 'duel_scenes.h', 'CoinGlintState': 'duel_scenes.h',
    'CoinHighlightState': 'duel_scenes.h', 'CoinLaunchMode': 'duel_scenes.h', 'CoinState': 'duel_scenes.h',
    'DestinyBoardAnimPhase': 'duel_scenes.h', 'DestinyBoardSceneStep': 'duel_scenes.h', 'DiceStep': 'duel_scenes.h',
    'DiceVariant': 'duel_scenes.h', 'ExodiaPiecesState': 'duel_scenes.h', 'ExodiaSceneStep': 'duel_scenes.h',
    'FinalLetterState': 'duel_scenes.h', 'RpsHand': 'turn_order.h', 'RpsResult': 'turn_order.h',
    'TurnChoice': 'turn_order.h', 'TurnOrderBanner': 'turn_order.h', 'TurnOrderBlendBit': 'turn_order.h',
    'TurnOrderLinkMsg': 'turn_order.h', 'TurnOrderPhase': 'turn_order.h', 'TurnOrderScroller': 'turn_order.h',
    'LinkMsgId': 'duel_link.h',
}

# header -> hazards and decisions the writer must know (in addition to NOTES and the types.json notes)
HEADER_NOTES = {
    'global.h': ['Existing file included by every unit: only add macros/typedefs that no unit defines (grep src/), '
                 'then run check_all. Keep INCLUDE_ASM (both the OBJDIFF_BASE and the normal form) and the '
                 'asm/macros.inc include exactly as they are.'],
    'gba.h': ['tools/xref.py reads IO register names from include/gba.h lines of the form '
              '`#define REG_X REG16(0x...)` / REG32(...): keep that form.',
              'Replaces include/legacy/gba.h: keep every macro name it has (units switch over unchanged). The BIOS '
              'stubs (CpuSet, CpuFastSet, Div) are defined in src/sdk/libagbsyscall.s.',
              'OamEntry is the OAM attribute layout (gMain.oamBuffer, gMain_oamBuffer); SioMultiCnt the SIOCNT '
              'multi-player register layout.'],
    'main.h': ['struct Main replaces include/legacy/main.h (legacy_renames maps its field names). gMain_intrCheck, '
               'gMain_callback and gMain_oamBuffer are linker aliases of gMain fields that some units use for '
               'matching; declare them with a comment, never fold their uses in a header.',
               'AgbMain, IntrMain and the interrupt handlers live in crt0/main units; IntrMain is in crt0 (asm).'],
    'util.h': ['gScratchBuffer is a 0x02030000 work buffer used with different element types; declare a u8 array and '
               'let units keep typed views.'],
    'save.h': ['agb_sram.h (Nintendo SDK) typedefs u8/u16/u32 itself and must never be included next to global.h: '
               'save.h redeclares ReadSram/WriteSram/VerifySram/WriteSramEx with the same prototypes instead.'],
    'sound.h': ['sound_driver.c is compiled by agbcc -fprologue-bugfix, not old_agbcc: hdrcheck compiles with both.',
                'Legacy struct SoundTrack (one type for both track kinds) becomes SoundBgmTrack and SoundSeTrack; '
                'legacy SoundPcmVoice becomes SoundPcmChannel.',
                'SoundMixAll, SoundMixChannel, SoundMixFifo are ARM code in src/sound_mixer_arm.s (asm prototypes '
                'from build/names/prototypes.json).'],
    'card_data.h': ['Units read the card tables both through symbols and through integer-constant addresses '
                    '(((const u32 *)0x08621DE0)[id]); both forms are matching choices and stay in the units. Accessor '
                    'macros here are optional; the static inline helpers duplicated across units (genprotos '
                    '"statics": CardNumberToId x7, GetCardSubtype x6, ...) differ in matching-relevant details, '
                    'so do not replace them from the header.'],
    'duel.h': ['Replaces include/legacy/duel.h (legacy_renames per struct). DuelState embeds struct CardMenu at '
               '+0x1B2C, so CardMenu lives here, not in card_menu.h.',
               'Per-pile alias symbols (gDuelHands, gDuelDecks, gDuelGraveyards, gDuelFusionDecks, gDuelBanished, '
               'gDuelZonesP1, gDuelHandP1, ...) are separate linker symbols the units use for matching: declare '
               'them with their canonical element types and a comment.'],
    'chain.h': ['ChainState +0x53C: DeckReorderState (Big Eye) overlaps effectCards (+0x544): a union, per '
                'types.json. ChainEntry lists a field "countB (+0x3C0, in ActionLists)" that belongs to '
                'ChainState: check before copying.'],
    'duel_cmd.h': ['Keep the operand names arg2/arg4/arg6 (types.json note). DuelCmdTimer16 is a FAKEMATCH u16 '
                   'container view of gDuelCmd.timer: keep it as a separate view struct.'],
    'duel_screen.h': ['Replaces the DuelScreen part of include/legacy/duel_ui.h (legacy_renames).'],
    'duel_scenes.h': ['gSceneWork.u holds the per-scene structs (ExodiaSceneWork, DestinyBoardSceneWork, '
                      'TurnOrderSceneWork); types.json gives their member offsets from the gSceneWork base '
                      '(subtract 0xAAC). PackListWork and StarterDeckSelectWork (booster.h) are 0x8070-byte views '
                      'of the same address: alias externs (asm("gSceneWork")) or unit-local views.'],
    'booster.h': ['PackCursor is a 1-byte bitfield struct but agbcc pads structs to 4 bytes: PackOpenWork.cursor at '
                  '+0x114 is followed by +0x115, so embed it as a u8 bitfield group, not as a struct.'],
    'deck_edit.h': ['DeckEdit is 0x1C5C bytes with 60 planned fields; see layout_warnings (scrollBar, menuPanel '
                    'overlap their neighbours: unions or bitfield groups).'],
    'effect_handlers.h': ['Handlers are referenced only from gCardEffects (data/.s), so no unit needs these '
                          'prototypes to compile; they document the table. Group them by card number order.'],
    'constants/cards.h': ['Generated: python3 tools/gencards.py (needs assets/ from make setup). CARDNO_* names in '
                          'types.json map to CARD_* through build/readability/cards_aliases.json.'],
    'constants/duel_cmds.h': ['DuelCmdId: 164 values from types.json, prefix DUEL_CMD_; player 1 commands are '
                              'id | 0x8000 (define DUEL_CMD_PLAYER 0x8000).'],
}

NOTES = [
    'H0 (coordinator, one atomic commit before the writers start): git mv include/{gba,main,duel,duel_ui,sound}.h '
    'include/legacy/ and rewrite the includes (src/*.c: "gba.h" -> "legacy/gba.h" etc.; legacy/duel_ui.h includes '
    '"legacy/duel.h"); global.h and agb_sram.h stay. check_all + make compare must be unchanged (no codegen change). '
    'This frees the canonical names and lets every writer create files no unit includes yet.',
    'H1 (writers, parallel): each group creates ONLY its own headers (header_plan.json groups). No edits to src/, '
    'include/legacy/ or another group\'s header. global.h belongs to core and may only gain macros/typedefs that no '
    'unit defines (verify with check_all). New headers cannot break the build because no unit includes them yet; '
    'verify each header with tools/hdrcheck.py (standalone compile with old_agbcc and agbcc, double inclusion, '
    'struct sizes/offsets against types.json, prototypes against protos.json, ownership against this plan).',
    'Includes: a header includes global.h, the headers listed in its "includes" (only by-value struct use: '
    'embedded members and extern arrays of structs), and any constants/*.h it uses. Pointer-only uses get a '
    'forward declaration (`struct X;`, listed in "forward_decls"), never an include. constants/*.h include nothing. '
    'Any extra include must come earlier in include_order ("may_include"), so no cycle can form. '
    'All names are fixed in this plan, so a writer can reference another group\'s types before that header exists.',
    'Prototypes: use "proto" (the definition exactly as compiled today: types, return type, variadic) with the '
    'parameter names of "param_names" when given. A header prototype must match the DEFINITION, never a caller\'s '
    'view; units whose local view differs (protos.json views, proto_mismatches.txt: abi/arity/unprototyped/type) '
    'keep a local alias prototype (`T LocalName(...) asm("Sym");`, commented) when they migrate. K&R definitions '
    '(kr: true) take "header_proto" (promoted parameter types).',
    'Struct fields: use types.json names/types/offsets; add STATIC_ASSERT (typedef char ...[cond ? 1 : -1]) checks '
    'for the size and key offsets like the legacy headers. Bitfield containers (u8/u16/u32) are codegen-relevant: '
    'keep the container type types.json gives. Keep packed/aligned attributes where a unit needs them (see '
    'src/duel_main.c, duel_response.c, sound_driver.c, duel_field_screen.c, duel_card_lists.c).',
    'Globals: declare RAM globals with the canonical type ("canonical_type"); "declared_as" lists how units declare '
    'them today. ROM data is declared in a header only when >= 2 units reference it by symbol ("rom_data"); data '
    'used by one unit stays a local extern in that unit ("local_rom_data", for reference). Never turn an '
    'integer-constant address access into a symbol access or the reverse: these are matching choices.',
    'H2 (migration, one agent per unit, after all headers exist): replace the legacy includes and local '
    'definitions with the new headers; keep local views where codegen needs them; tools/check.py <unit> must '
    'report unit bytes MATCH. Legacy field names map to canonical ones through "legacy_renames" (computed by '
    'offset). When no unit includes include/legacy/ any more, delete it.',
    'Constants: CARD_* (constants/cards.h) replaces the CARDNO_* names of types.json CardNumber '
    '(alias map in build/readability/cards_aliases.json); DuelCmdId keeps the DUEL_CMD_ prefix.',
    'tools/structmap.py (field offsets across units) now takes a symbol or an address and reads every C unit '
    '(it used to glob src/code_*.c, which the unit rename broke); tools/mkheader.py and tools/typesurvey.py too.',
    'Writing order inside H1: the headers other groups include by value come first: core (gba.h, util.h, '
    'palette.h), gfx (sprite.h), system_io (link.h), duel_core (duel.h), duel_flow (chain.h); see each header\'s '
    '"includes" and "tier". A header whose required include does not exist yet fails hdrcheck at the cpp step: '
    'finish the rest and re-run.',
    'Tools: tools/genprotos.py (exact prototypes and every unit\'s views -> build/readability/protos.json, '
    'proto_mismatches.txt), tools/headerplan.py (this plan; --header X, --owner NAME), tools/hdrcheck.py '
    '(verify a header: compile, ownership, layout, prototypes, include order), tools/gencards.py '
    '(constants/cards.h), tools/structmap.py SYMBOL (how every unit lays out a global), tools/mkheader.py.',
]

H0_COMMANDS = [
    'mkdir -p include/legacy',
    'git mv include/gba.h include/main.h include/duel.h include/duel_ui.h include/sound.h include/legacy/',
    'tools/dr sed -i -E \'s/#include "(gba|main|duel|duel_ui|sound)\\.h"/#include "legacy\\/\\1.h"/\' '
    'src/*.c src/sdk/*.c include/legacy/*.h',
    'tools/dr python3 tools/check_all.py && tools/dr make -j8 compare   # must be unchanged: 112/112, eds.gba: OK',
]


# ----------------------------------------------------------------------------------------------- loading

def load_old2new():
    m = {}
    for line in open('build/readability/unit_names.tsv'):
        p = line.split()
        if len(p) == 2 and not line.startswith('#'):
            m[p[0]] = p[1]
            m[p[0][5:]] = p[1]
    return m


def sub_key(title):
    for prefix, key in SUBSYSTEMS:
        if title.startswith(prefix):
            return key
    raise ValueError(f'unknown subsystem section: {title}')


def load_final():
    """-> {name: {addr, sub, kind (functions|ram|rom), summary, confidence}}"""
    out, sec, kind = {}, None, None
    for line in open('build/names/final.txt'):
        if line.startswith('## '):
            sec = sub_key(line[3:].strip())
            continue
        if line.startswith('### '):
            k = line[4:].split('(')[0].strip()
            kind = {'functions': 'function', 'RAM globals': 'ram', 'ROM data': 'rom'}[k]
            continue
        m = re.match(r'(0x[0-9A-Fa-f]+) (\S+)\s*(?:#\s*(.*?))?\s*(?:\[(high|medium|low)\])?\s*$', line.rstrip('\n'))
        if m and sec and sec != 'alias':
            out[m.group(2)] = {'addr': m.group(1), 'sub': sec, 'kind': kind, 'summary': (m.group(3) or '').strip(),
                               'confidence': m.group(4)}
    return out


def load_functions():
    fs = {}
    for line in open('config/functions.tsv'):
        if line.startswith('#'):
            continue
        f = line.rstrip('\n').split('\t')
        fs[f[3]] = {'addr': f[0], 'mode': f[1], 'size': f[2], 'unit': f[4]}
    return fs


def rule_header(sub, name, unit=None):
    bare = re.sub(r'^gStr|^g(?=[A-Z])', '', name)
    for s, rx, h in NAME_RULES:
        if s not in ('*', sub):
            continue
        if rx.startswith('^@unit:'):
            if unit and re.match(rx[7:], unit):
                return h
            continue
        if re.match(rx, bare) or re.match(rx, name):
            return h
    return SUB_DEFAULT[sub]


STRUCT_REF = re.compile(r'\b(struct|union)\s+(\w+)')


def by_value_structs(ctype):
    """Struct tags used by value in a C type string (members, arrays); pointers and function pointers excluded."""
    t = re.sub(r'\([^()]*\)', lambda m: '' if '*' in m.group(0) else m.group(0), ctype)  # drop (...) groups w/ ptr
    out = []
    for m in STRUCT_REF.finditer(ctype):
        rest = ctype[m.end():].lstrip()
        if rest.startswith('*'):
            continue
        # inside a function-pointer parameter list?
        before = ctype[:m.start()]
        if before.count('(') > before.count(')'):
            continue
        out.append(m.group(2))
    del t
    return out


def ptr_structs(ctype):
    out = []
    for m in STRUCT_REF.finditer(ctype):
        if m.group(2) not in by_value_structs(ctype):
            out.append(m.group(2))
    return out


CTYPE_RE = re.compile(r'^void\s*\(\*\s*\[[^\]]*\]\)\s*\(void\)'
                      r'|^(?:(?:const|volatile)\s+)*(?:struct\s+\w+|union\s+\w+|unsigned\s+\w+|[us]8|[us]16|[us]32|'
                      r'vu8|vu16|vu32|bool8|bool32|char|short|int|void)(?:\s*\*)*(?:\s*\[[^\]]*\])*')


def clean_type(s):
    """Leading C type of a proposal's type text ("struct DuelCard[80] per player, ..." -> "struct DuelCard[80]");
    None when the text does not start with a type."""
    s = (s or '').strip()
    m = CTYPE_RE.match(s)
    return m.group(0).strip() if m else None


def translate_tags(proto, unit, tagmap, tagmap_any):
    """Replace the unit-local struct tags of a definition's prototype with the canonical struct names."""
    unresolved = []

    def rep(m):
        tag = m.group(2)
        if (unit, tag) in TAG_FIXES:
            return f'struct {TAG_FIXES[(unit, tag)]}'
        if tag in LEGACY_ONLY_STRUCTS:
            path_, repl, _ = LEGACY_ONLY_STRUCTS[tag]
            if path_ is None and repl and re.match(r'^\w+$', repl):    # renamed: SoundPcmVoice -> SoundPcmChannel
                return f'struct {repl}'
            return m.group(0)
        if tag in STRUCT_HOME:
            return m.group(0)
        new = tagmap.get((unit, tag)) or TAG_FIXES.get((unit, tag))
        if new is None and unit is None:
            new = next((v for (u, t), v in TAG_FIXES.items() if t == tag), None)
        if new is None and len(tagmap_any.get(tag, ())) == 1:
            new = next(iter(tagmap_any[tag]))
        if new is None:
            unresolved.append(tag)
            return m.group(0)
        return f'struct {new}'
    out = STRUCT_REF.sub(rep, proto)
    return out, sorted(set(unresolved))


SCALAR_SIZE = {'u8': 1, 's8': 1, 'char': 1, 'bool8': 1, 'vu8': 1, 'u16': 2, 's16': 2, 'vu16': 2, 'u32': 4, 's32': 4,
               'int': 4, 'vu32': 4, 'bool32': 4, 'unsigned': 4, 'long': 4}


def _hex(x):
    m = re.match(r'\s*(0x[0-9A-Fa-f]+|\d+)', str(x))
    return int(m.group(1), 0) if m else None


def field_size(ftype, S):
    """Byte size of a non-bitfield member type string, or None when unknown (agbcc: structs padded to 4)."""
    t = re.sub(r'\s*\((?![^()]*\*)[^()]*\)\s*$', '', ftype).strip()
    if '(*' in t or '( *' in t:                     # pointer to array / function
        return 4
    dims = [d for d in re.findall(r'\[([^\]]*)\]', t)]
    base = re.sub(r'\[[^\]]*\]', '', t).strip()
    n = 1
    for d in dims:
        v = _hex(d)
        if v is None:
            return None
        n *= v
    if '*' in base or '(' in base:
        return 4 * n
    m = re.match(r'^(?:const\s+|volatile\s+)*(struct|union)\s+(\w+)$', base)
    if m:
        st = S.get(m.group(2))
        sz = _hex(st['size']) if st else None
        return None if sz is None else -(-sz // 4) * 4 * n
    base = re.sub(r'^(const|volatile)\s+', '', base)
    base = re.sub(r'\s*\(enum \w+\)$', '', base).strip()
    sz = SCALAR_SIZE.get(base.split()[0] if base else '')
    return None if sz is None else sz * n


def layout_warnings(name, size, fields, S):
    """Overlaps between consecutive members (a union or a view is needed) and by-value structs that agbcc pads
    to 4 bytes but the next member starts sooner."""
    out = []
    rows = []
    for f in fields:
        if f.get('bits'):
            continue
        off = _hex(f['offset'])
        if off is None:
            continue
        rows.append((off, f))
    rows.sort(key=lambda r: r[0])
    total = _hex(size)
    rng = re.search(r'\((0x[0-9A-Fa-f]+)\.\.(0x[0-9A-Fa-f]+)\)', str(size))
    if rng:                                          # union member documented with gSceneWork-based offsets
        total = int(rng.group(2), 16)
    for i, (off, f) in enumerate(rows):
        sz = field_size(f['type'], S)
        if sz is None:
            continue
        nxt = next((o for o, _ in rows[i + 1:] if o > off), total)
        if nxt is not None and off + sz > nxt:
            kind = 'padded struct' if re.search(r'\bstruct\b', f['type']) and '*' not in f['type'] else 'member'
            out.append(f"{f['name']} (+0x{off:X}, {f['type']}) is {sz:#x} bytes ({kind}) but the next member starts "
                       f"at +0x{nxt:X}: needs a union, a smaller type or an unpadded view")
    return out


# ----------------------------------------------------------------------------------------------- legacy renames

def legacy_renames(types_structs):
    """Map legacy include/*.h (or include/legacy/*.h) field names to types.json names by bit offset."""
    try:
        import structmap
        from pycparser import c_parser
    except ImportError:
        return {}, 'pycparser not available (run under tools/dr)'
    res = {}
    base = 'include/legacy' if os.path.isdir('include/legacy') else 'include'
    for hdr in ('main.h', 'duel.h', 'duel_ui.h', 'sound.h'):
        path = os.path.join(base, hdr)
        if not os.path.exists(path):
            continue
        import genprotos as gp
        text = gp.strip_attrs(gp.fold_asm(gp.strip_bodies(gp.clean(gp.cpp(path)))[0]))   # keeps line markers
        ast = c_parser.CParser().parse(text, path)
        lay = structmap.Layout(ast)
        for (_kind, tag), body in lay.structs.items():
            if tag not in types_structs:
                continue
            if body.coord and os.path.basename(str(body.coord.file)) != hdr:
                continue                      # defined by an included header (duel_ui.h includes duel.h)
            fields = {}
            for f in types_structs[tag]['fields']:
                try:
                    off = int(f['offset'], 16)
                except ValueError:
                    continue
                b = f.get('bits')
                if b:
                    lo = int(str(b).split('-')[0])
                    hi = int(str(b).split('-')[-1])
                    fields[(off * 8 + lo, hi - lo + 1)] = f['name']
                else:
                    fields[(off * 8, None)] = f['name']
            ren = {}
            for name, bit, w, size, ty in lay.members(body)[0]:
                key = (bit, w)
                new = fields.get(key)
                if new and new != name:
                    ren[name] = new
            res[tag] = {'legacy_header': f'include/legacy/{hdr}', 'renames': ren}
    return res, None


# ----------------------------------------------------------------------------------------------- build

def main():
    ap = argparse.ArgumentParser(description=__doc__.split('\n')[0])
    ap.add_argument('--out', default=OUT)
    ap.add_argument('--header')
    ap.add_argument('--owner')
    a = ap.parse_args()
    if a.header or a.owner:
        plan = json.load(open(a.out))
        if a.header:
            print(json.dumps(plan['headers'][a.header], indent=1))
        else:
            print(plan['owners'].get(a.owner, f'{a.owner}: not in the plan'))
        return
    plan = build()
    os.makedirs(os.path.dirname(a.out), exist_ok=True)
    json.dump(plan, open(a.out, 'w'), indent=1)
    summary(plan)
    print(f'wrote {a.out}')


def build():
    old2new = load_old2new()
    types = json.load(open('build/names/types.json'))
    protos_prop = {f['name']: f for f in json.load(open('build/names/prototypes.json'))['functions']}
    pdb = json.load(open('build/readability/protos.json'))
    final = load_final()
    funcs = load_functions()
    S = {s['name']: s for s in types['structs']}
    E = {e['name']: e for e in types['enums']}
    errors = []

    # every header
    H = {}
    for path, (group, desc) in HEADERS.items():
        H[path] = {'path': f'include/{path}', 'group': group, 'description': desc,
                   'kind': 'constants' if path.startswith('constants/') else
                   ('base' if path in ('global.h', 'gba.h') else 'subsystem'),
                   'generated_by': 'tools/gencards.py' if path == 'constants/cards.h' else None,
                   'existing': path == 'global.h',
                   'replaces_legacy': [f'include/legacy/{k}' for k, v in LEGACY.items()
                                       if (v == path if isinstance(v, str) else path in v)],
                   'subsystems': set(), 'structs': [], 'enums': [], 'ram_globals': [], 'rom_data': [],
                   'local_rom_data': [], 'functions': [], 'includes': set(), 'forward_decls': set(),
                   'weight': 0.0}
        if path == 'constants/cards.h':
            H[path]['existing'] = False

    owners = {}

    def own(name, path, what):
        if name in owners and owners[name] != path:
            errors.append(f'{what} {name}: owned by both {owners[name]} and {path}')
        owners[name] = path

    # -------- structs
    for name, s in S.items():
        path = STRUCT_HOME.get(name)
        if path is None:
            errors.append(f'struct {name}: no owner in STRUCT_HOME')
            continue
        own(name, path, 'struct')
        locs = [{'unit': old2new.get(d['unit'], d['unit']), 'local_tags': d['local_tags']}
                for d in s.get('local_definitions') or []]
        fields = []
        for f in s['fields']:
            ft = FIELD_TYPE_FIXES.get((name, f['name']), f['type'])
            e = {'offset': f['offset'], 'bits': f.get('bits'), 'name': f['name'], 'type': ft,
                 'summary': f.get('summary'), 'confidence': f.get('confidence')}
            if ft != f['type']:
                e['type_in_types_json'] = f['type']
            fields.append(e)
        H[path]['structs'].append({
            'name': name, 'size': s['size'], 'globals': s.get('globals') or [], 'confidence': s.get('confidence'),
            'note': s.get('note'), 'fields': fields, 'unit_local_definitions': locs,
            'legacy_header': s.get('existing_header'),
            'applies_to': s.get('applies_to'),
            'layout_warnings': layout_warnings(name, s['size'], fields, S),
        })
        H[path]['subsystems'].add('types')
    for name, (path, repl, why) in LEGACY_ONLY_STRUCTS.items():
        if path:
            own(name, path, 'struct')
            H[path]['structs'].append({'name': name, 'size': None, 'globals': [], 'fields': None,
                                       'note': f'only in the legacy header ({why}); copy its layout',
                                       'legacy_header': 'include/legacy/' + ('duel.h' if path == 'duel.h'
                                                                             else 'duel_ui.h'),
                                       'unit_local_definitions': []})
    for name in STRUCT_HOME:
        if name not in S and name not in LEGACY_ONLY_STRUCTS:
            errors.append(f'STRUCT_HOME has {name}, which is not in types.json')

    # -------- enums
    for name, e in E.items():
        path = ENUM_HOME.get(name)
        if path is None:
            errors.append(f'enum {name}: no owner in ENUM_HOME')
            continue
        own(name, path, 'enum')
        H[path]['enums'].append({
            'name': name, 'values': len(e['values']), 'confidence': e.get('confidence'),
            'context': e.get('context'),
            'used_by_units': sorted({old2new.get(p, p) for p in e.get('proposed_by') or []}),
            'note': ('generated from assets (tools/gencards.py); the types.json CARDNO_* names are aliases'
                     if name == 'CardNumber' else None),
        })
    for name in ENUM_HOME:
        if name not in E:
            errors.append(f'ENUM_HOME has {name}, which is not in types.json')

    tagmap, tagmap_any = {}, collections.defaultdict(set)
    for name_, s_ in S.items():
        for d_ in s_.get('local_definitions') or []:
            for tag in d_['local_tags']:
                tagmap[(old2new.get(d_['unit'], d_['unit']), tag)] = name_
                tagmap_any[tag].add(name_)

    # -------- globals (RAM and ROM): canonical types
    struct_of_global = {}
    for name, s in S.items():
        for g in s.get('globals') or []:
            struct_of_global.setdefault(g, name)
    prop_types = collections.defaultdict(collections.Counter)
    import glob
    for f in glob.glob('build/names/*.json'):
        if f.endswith(('types.json', 'prototypes.json')):
            continue
        d = json.load(open(f))
        for x in d.get('globals') or []:
            if x.get('type') and clean_type(x['type']):
                prop_types[x['name']][clean_type(x['type'])] += 1
    gdecl = pdb['globals']
    for name, info in final.items():
        if info['kind'] not in ('ram', 'rom'):
            continue
        decl = gdecl.get(name)
        units = sorted({d['unit'] for d in decl['decls']}) if decl else []
        declared_as = decl['types'] if decl else {}
        st = struct_of_global.get(name)
        if info['kind'] == 'ram':
            if st:
                canon = None
                for t_, _ in prop_types[name].most_common():
                    if re.match(rf'^struct {st}\b', t_):
                        canon = t_
                        break
                canon = canon or f'struct {st}'
            else:
                canon = (prop_types[name].most_common(1)[0][0] if prop_types[name] else
                         (max(declared_as, key=declared_as.get) if declared_as else None))
        else:
            canon = None
            if declared_as:
                consts = {k: v for k, v in declared_as.items() if k.startswith('const')}
                pool = consts or declared_as
                canon = max(pool, key=pool.get)
                if not canon.startswith('const'):
                    canon = 'const ' + canon
        unres = []
        if name in GLOBAL_TYPE:
            canon = GLOBAL_TYPE[name]
        if canon:
            canon, unres = translate_tags(canon, units[0] if len(units) == 1 else None, tagmap, tagmap_any)
        path = GLOBAL_HOME.get(name)
        if path is None:
            bare = re.sub(r'^gStr|^g(?=[A-Z])', '', name)
            path = next((h for rx, h in GLOBAL_RULES if re.match(rx, bare)), None)
        if path is None:
            path = rule_header(info['sub'], name)
        entry = {'name': name, 'addr': info['addr'], 'canonical_type': canon, 'declared_as': declared_as,
                 'declared_by_units': units, 'summary': info['summary'][:240], 'confidence': info['confidence']}
        if unres:
            entry['unresolved_struct_tags'] = unres
        if name in GLOBAL_TYPE and GLOBAL_TYPE[name] == 'struct DuelCard[]':
            entry['type_note'] = GLOBAL_TYPE_NOTE
        if canon and declared_as:
            entry['views_differ'] = sorted(k for k in declared_as if k.replace('const ', '') != canon.replace(
                'const ', ''))
        if info['kind'] == 'ram' and name in UNIT_LOCAL_ALIASES:
            entry['unit'] = units[0] if units else None
            entry['note'] = UNIT_LOCAL_ALIASES[name]
            H[path].setdefault('local_ram_aliases', []).append(entry)
        elif info['kind'] == 'ram':
            own(name, path, 'global')
            H[path]['ram_globals'].append(entry)
        elif len(units) >= 2:
            own(name, path, 'global')
            H[path]['rom_data'].append(entry)
        else:
            entry['unit'] = units[0] if units else None
            H[path]['local_rom_data'].append({'name': name, 'addr': info['addr'], 'unit': entry['unit'],
                                              'declared_as': declared_as})
        H[path]['subsystems'].add(info['sub'])

    # -------- functions
    unit_sub = collections.defaultdict(collections.Counter)
    for name, f in funcs.items():
        if name in final:
            unit_sub[f['unit']][final[name]['sub']] += 1
    for name, f in sorted(funcs.items(), key=lambda kv: kv[1]['addr']):
        if name in STATIC_FUNCTIONS:      # file-local definitions: no prototype in any header
            continue
        info = final.get(name)
        sub = info['sub'] if info else (unit_sub[f['unit']].most_common(1)[0][0] if unit_sub[f['unit']] else None)
        if f['unit'] in ('sdk/libagbsyscall',):
            path = 'gba.h'
        elif f['unit'] == 'sdk/agb_sram':
            path = 'save.h'
        elif f['unit'] == 'sound_mixer_arm':
            path = 'sound.h'
        elif f['unit'] == 'crt0':
            path = 'main.h'
        elif sub is None:
            errors.append(f'function {name}: no subsystem')
            continue
        else:
            path = rule_header(sub, name, f['unit'])
        own(name, path, 'function')
        d = pdb['functions'].get(name)
        pp = protos_prop.get(name)
        entry = {'name': name, 'addr': f['addr'], 'unit': f['unit'], 'mode': f['mode'],
                 'summary': (info or {}).get('summary', '')[:300] or None,
                 'confidence': (info or {}).get('confidence')}
        if d:
            entry['proto'] = d['proto']
            if d.get('kr'):
                entry['kr'] = True
            hp, unresolved = translate_tags(d.get('hproto') or d['proto'], f['unit'], tagmap, tagmap_any)
            if hp != d['proto']:
                entry['header_proto'] = hp
            if unresolved:
                entry['unresolved_struct_tags'] = unresolved
            names_now = [p['name'] for p in d['params']]
            if pp and pp.get('params') and len(pp['params']) == len(d['params']):
                pn = [re.split(r'[\s*]+', x.strip())[-1].strip('[]') for x in pp['params']]
                pn = [re.sub(r'\[.*$', '', x) for x in pn]
                if all(re.match(r'^[A-Za-z_]\w*$', x) for x in pn) and pn != names_now:
                    entry['param_names'] = pn
            if pp and pp.get('comments'):
                entry['comments'] = pp['comments']
            v = [x for x in d['views'] if x['status'] in ('abi', 'unprototyped', 'arity')]
            if v:
                entry['units_with_abi_views'] = sorted({x['unit'] for x in v})
            tv = [x for x in d['views'] if x['status'] == 'type']
            if tv:
                entry['units_with_type_views'] = sorted({x['unit'] for x in tv})
        else:
            a_ = pdb['asm_functions'].get(name, {})
            entry['asm'] = True
            entry['proto'] = None
            entry['declared_as'] = sorted({x['proto'] for x in a_.get('views', [])})
            if pp:
                entry['proposed'] = f"{pp.get('returns')} {name}({', '.join(pp.get('params') or ['void'])})"
        H[path]['functions'].append(entry)
        if sub:
            H[path]['subsystems'].add(sub)

    # -------- includes / forward declarations
    for path, h in H.items():
        deps, fwd = set(), set()
        for s in h['structs']:
            for f in s['fields'] or []:
                for tag in by_value_structs(f['type']):
                    deps.add(tag)
                for tag in ptr_structs(f['type']):
                    fwd.add(tag)
        for g in h['ram_globals'] + h['rom_data']:
            if g['canonical_type']:
                for tag in by_value_structs(g['canonical_type']):
                    deps.add(tag)
        for fn in h['functions']:
            p = fn.get('header_proto') or fn.get('proto') or ''
            for tag in STRUCT_REF.findall(p):
                fwd.add(tag[1])
        own_structs = {s['name'] for s in h['structs']}
        inc = set()
        for tag in deps:
            o = STRUCT_HOME.get(tag) or (LEGACY_ONLY_STRUCTS.get(tag, (None,))[0])
            if o and o != path:
                inc.add(o)
        h['includes'] = sorted(inc)
        h['forward_decls'] = sorted(t for t in fwd - own_structs - deps
                                    if t in STRUCT_HOME and STRUCT_HOME[t] != path)
        h['unknown_struct_tags'] = sorted(t for t in (fwd | deps) - own_structs if t not in STRUCT_HOME
                                          and t not in LEGACY_ONLY_STRUCTS)
        h['subsystems'] = sorted(h['subsystems'] - {'types'})
    # cycle check + tiers
    tiers, done = {}, set()
    remaining = set(H)
    level = 0
    while remaining:
        ready = {p for p in remaining if all(i in done for i in H[p]['includes'])}
        if not ready:
            errors.append(f'include cycle among: {sorted(remaining)}')
            break
        for p in ready:
            tiers[p] = level
        done |= ready
        remaining -= ready
        level += 1
    if sorted(INCLUDE_ORDER) != sorted(H):
        errors.append(f'INCLUDE_ORDER and HEADERS differ: {sorted(set(INCLUDE_ORDER) ^ set(H))}')
    for p, h in H.items():
        h['may_include'] = [f'include/{x}' for x in INCLUDE_ORDER[:INCLUDE_ORDER.index(p)]] if p in INCLUDE_ORDER \
            else []
        for inc in h['includes']:
            if p in INCLUDE_ORDER and inc in INCLUDE_ORDER and INCLUDE_ORDER.index(inc) > INCLUDE_ORDER.index(p):
                errors.append(f'{p} needs {inc}, which comes later in INCLUDE_ORDER (cycle risk)')
        h['includes'] = [f'include/{x}' for x in h['includes']]
    for p, h in H.items():
        h['tier'] = tiers.get(p)
        h['weight'] = round(len(h['functions']) * (0.25 if p == 'effect_handlers.h' else 0.5)
                            + sum(4 + 0.5 * len(s['fields'] or []) for s in h['structs'])
                            + sum(1 + 0.05 * e['values'] for e in h['enums'] if e['name'] != 'CardNumber')
                            + (5 if any(e['name'] == 'CardNumber' for e in h['enums']) else 0)
                            + 0.5 * (len(h['ram_globals']) + len(h['rom_data'])), 1)
        h['counts'] = {'structs': len(h['structs']), 'enums': len(h['enums']), 'functions': len(h['functions']),
                       'ram_globals': len(h['ram_globals']), 'rom_data': len(h['rom_data'])}

    # legacy renames
    ren, err = legacy_renames(S)
    for tag, r in ren.items():
        path = STRUCT_HOME.get(tag)
        if path:
            for s in H[path]['structs']:
                if s['name'] == tag:
                    s['legacy_renames'] = r['renames']
                    s['legacy_header'] = r['legacy_header']
    if err:
        errors.append('legacy renames not computed: ' + err)

    # notes: HEADER_NOTES, types.json notes (by keyword), alias folds (by target global)
    kw = [('DuelState', 'duel.h'), ('DuelZone', 'duel.h'), ('ChainEntry', 'chain.h'), ('ChainState', 'chain.h'),
          ('gTextBox', 'text_box.h'), ('gCalendar', 'calendar.h'), ('gOpponentSelect', 'campaign.h'),
          ('SaveData', 'save.h'), ('Card type values', 'constants/card_stats.h'), ('DuelCmd operands', 'duel_cmd.h'),
          ('Non-EDS effect keys', 'constants/cards.h')]
    for p, h in H.items():
        h['notes'] = list(HEADER_NOTES.get(p, []))
    for n in types.get('notes', []):
        for k, p in kw:
            if k in n and n not in H[p]['notes']:
                H[p]['notes'].append('types.json: ' + n)
    unattached = []
    for a_ in types.get('alias_folds', []):
        tgt = (a_['fold_to'] or [''])[0]
        m = re.search(r'\b(g[A-Z]\w*)', ' '.join(a_['fold_to']))
        gname = {'gDialogueScene': 'gBustup', 'gActionLists': 'gChain'}.get(m.group(1), m.group(1)) if m else None
        o = owners.get(gname) if gname else None
        rec = {'addr': a_['addr'], 'symbol': a_['symbol'], 'fold_to': a_['fold_to'],
               'units': sorted({old2new.get(u, u) for u in a_['units']}), 'summary': a_['summary'][:200]}
        if o:
            H[o].setdefault('alias_folds', []).append(rec)
        else:
            unattached.append(rec)
        del tgt

    groups = []
    for g, desc in GROUPS.items():
        hs = [p for p, h in H.items() if h['group'] == g]
        groups.append({'name': g, 'description': desc, 'headers': [f'include/{p}' for p in hs],
                       'weight': round(sum(H[p]['weight'] for p in hs), 1),
                       'functions': sum(len(H[p]['functions']) for p in hs),
                       'structs': sum(len(H[p]['structs']) for p in hs),
                       'enums': sum(len(H[p]['enums']) for p in hs),
                       'subsystems': sorted({s for p in hs for s in H[p]['subsystems']})})
    for p, h in H.items():
        if h['group'] not in GROUPS:
            errors.append(f'{p}: unknown group {h["group"]}')
    if errors:
        for e in errors:
            print('ERROR', e, file=sys.stderr)
        if any('cycle' in e or 'owned by both' in e or 'no owner' in e for e in errors):
            sys.exit(1)
    return {
        'generated': datetime.date.today().isoformat(), 'tool': 'tools/headerplan.py',
        'inputs': ['build/names/types.json', 'build/names/final.txt', 'build/names/prototypes.json',
                   'build/readability/protos.json', 'build/readability/unit_names.tsv', 'config/functions.tsv'],
        'notes': NOTES,
        'h0_commands': H0_COMMANDS,
        'include_order': [f'include/{p}' for p in INCLUDE_ORDER],
        'include_rule': 'A header includes global.h, the headers in its "includes" (by-value struct uses, required) '
                        'and optionally other headers listed in its "may_include" (only earlier ones in include_order); '
                        'pointer-only uses get forward declarations. constants/*.h include nothing.',
        'groups': groups,
        'headers': {p: h for p, h in H.items()},
        'owners': {k: f'include/{v}' for k, v in sorted(owners.items())},
        'alias_folds_unattached': unattached,
        'errors': errors,
    }


def summary(plan):
    print(f"{len(plan['headers'])} headers, {len(plan['owners'])} owned names")
    for g in plan['groups']:
        print(f"  {g['name']:11s} w={g['weight']:6.1f} fn={g['functions']:4d} st={g['structs']:3d} "
              f"en={g['enums']:3d}  {' '.join(h.replace('include/', '') for h in g['headers'])}")
    for p, h in plan['headers'].items():
        if h['includes'] or h['unknown_struct_tags']:
            print(f"  {p:22s} tier {h['tier']} includes {h['includes']}"
                  + (f" UNKNOWN {h['unknown_struct_tags']}" if h['unknown_struct_tags'] else ''))
    if plan['errors']:
        print(f"{len(plan['errors'])} errors (see 'errors')")


if __name__ == '__main__':
    main()
