#!/usr/bin/env python3
"""Generate the linker script from units.txt and the resolved object list.
Usage: mkld.py units.txt out.ld obj...   (objs in unit order, one per unit)"""
import sys

units_file, out, objs = sys.argv[1], sys.argv[2], sys.argv[3:]
units = []
for line in open(units_file):
    line = line.split('#')[0].strip()
    if line:
        units.append(line)
real = [u for u in units if not u.startswith('@')]
rodata_moved = {u.split()[1] for u in units if u.startswith('@rodata ')}
assert len(real) == len(objs), (len(real), len(objs))
obj_of = dict(zip(real, objs))

text, rodata = [], []
for u in units:
    if u == '@libs':
        # Explicit member order = order in the original ROM (0x0807EE98-0x08080A18).
        for m in ('_call_via_rX', '_divsi3', '_dvmd_tls', '_modsi3', '_muldi3', '_udivsi3', '_umodsi3',
                  'dp-bit', 'fp-bit', '_lshrdi3', '_negdi2'):
            text.append(f'        *libgcc.a:{m}.o(.text)')
        for m in ('memcpy', 'memset', 'strcpy'):
            text.append(f'        *libc.a:{m}.o(.text)')
        text.append('        *libgcc.a:*(.text) *libc.a:*(.text)')
        continue
    if u.startswith('@rodata '):
        rodata.append(f'        {obj_of[u.split()[1]]}(.rodata)')
        continue
    o = obj_of[u]
    text.append(f'        {o}(.text)')
    if u not in rodata_moved:
        rodata.append(f'        {o}(.rodata)')

with open(out, 'w') as f:
    f.write(f'''/* Generated by tools/mkld.py from units.txt - do not edit. */
OUTPUT_ARCH(arm)
ENTRY(_start)
INCLUDE symbols.ld

SECTIONS
{{
    . = 0x08000000;
    .text :
    {{
{chr(10).join(text)}
    }} =0

    .rodata :
    {{
{chr(10).join(rodata)}
    }} =0

    /* Anything else that would land in ROM is appended here so `make compare` catches it. */
    .data : {{ *(.data*) *(.rodata*) }}

    /* libgcc soft-float statics live at fixed IWRAM addresses in the original link. */
    . = 0x03005B38;
    .bss.libgcc (NOLOAD) :
    {{
        *libgcc.a:dp-bit.o(.bss)
        . = 0x03005B50 - 0x03005B38;
        *libgcc.a:fp-bit.o(.bss)
    }}

    . = 0x02000000;
    .ewram (NOLOAD) : {{ *(.bss*) *(COMMON) }}

    /DISCARD/ : {{ *(.comment) *(.note*) }}
}}
''')
